### ISSUE TITLE
Error for missing transitive dependencies could be better.

### ISSUE THREAD

**Issue by docwhat** [berkshelf/berkshelf#1008]
## Scenario
1. cookbook "foo" is in git and is version 1.0.0.
2. cookbook "bar" version 0.0.4 is in git and requires cookbook "foo".
3. I'm working on cookbook "baz" (version 0.0.1)

In my `Berksfile` I have something like this:

``` ruby
# Berksfile
source "https://api.berkshelf.com"

cookbook 'bar', git: 'http://example.com/bar.git', tag: 'v0.0.4'

metadata
```

In my `metadata.rb` I have something like this:

``` ruby
# metadata.rb
name             'baz'
version          '0.0.1'

depends 'bar', '0.0.4'
```
## Error message

```
$ berks
Fetching 'bar' from git: 'http://example.com/bar.git' with branch: 'v0.0.4'
building universe...
Unable to find a solution for demands: bar (0.0.4), baz (0.0.1)
```
## What I would have like to see

```
$ berks
Fetching 'bar' from git: 'http://example.com/bar.git' with branch: 'v0.0.4'
building universe...
Unable to find a solution for demands: bar (0.0.4), baz (0.0.1)
Missing transitive dependency: foo (1.0.0)
```
## Solution

``` ruby
# Berksfile
source "https://api.berkshelf.com"

cookbook 'bar', git: 'http://example.com/bar.git', tag: 'v0.0.4'
cookbook 'foo', git: 'http://example.com/foo.git', tag: 'v1.0.0'

metadata
```
## Notes

Ideally, I'd like to add the git references on the `depends` line in the `metadata.rb` file.  Or better yet, set up an internal berksfile-api server.  But alas, that isn't to be (this week, anyway).

**Comment by nozpheratu** [comment]
@sethvargo Should this issue be closed? Doesn't look like the issue has actually been fixed yet.
