### ISSUE TITLE
"gem install berkshelf" fails with Ruby 2.1.1 - "Failed to build gecode library"

### ISSUE THREAD

**Issue by evgeny-goldin** [berkshelf/berkshelf#1138]
Attempting to "gem install berkshelf" with Ruby 2.1.1 fails, see this [log file](https://gist.github.com/evgeny-goldin/b346ad1e7182c2491c6b). Same problem was recently raised in [AWS forum](https://forums.aws.amazon.com/thread.jspa?messageID=535762).

Ubuntu 14.04 but I had the same problem with, I believe, 12.04.

**Comment by acoulton** [comment]
I had problems downloading the packages from the URLs in @pghalliday's comment above, but was able to get them OK from the Ubuntu 12.04 repositories.

This worked for me:
```bash
  apt-get install -y -q  libqtcore4 libqtgui4 libqt4-dev libboost-dev
  wget "http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gecode/libgecode30_3.7.1-3_amd64.deb"
  wget "http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gecode/libgecode-dev_3.7.1-3_amd64.deb"
  wget "http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gecode/libgecodegist30_3.7.1-3_amd64.deb"
  wget "http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gecode/libgecodeflatzinc30_3.7.1-3_amd64.deb"
  dpkg -i libgecode30_3.7.1-3_amd64.deb libgecodegist30_3.7.1-3_amd64.deb libgecodeflatzinc30_3.7.1-3_amd64.deb libgecode-dev_3.7.1-3_amd64.deb
```

**Comment by axsuul** [comment]
If you are getting `unknown pseudo-op` error, it means you forgot the `USE_SYSTEM_GECODE=1`

**Comment by suda** [comment]
Alternative way is to install `dep-selector` gem via apt-get:
`apt-get install -y ruby-dep-selector`

**Comment by avecchio** [comment]
On a Mac I had to compile gecode before I installed dep_selector and later berkshelf.
