### ISSUE TITLE
Berkshelf does not use the latest versions

### ISSUE THREAD

**Issue by chulkilee** [berkshelf/berkshelf#1140]
Berkshelf does not use the latest versions when cookbook metadata dependencies do not have version constraints.

Tested on Berkshelf 3.1.0
- [metadata.rb](https://github.com/chulkilee/berkshelf-test/blob/master/metadata.rb)
- [Berkshelf.lock without version constraint](https://github.com/chulkilee/berkshelf-test/blob/without-constraint/Berksfile.lock): use nginx 1.8
- [Berkshelf.lock with version constraint](https://github.com/chulkilee/berkshelf-test/blob/with-constraint/Berksfile.lock): use nginx 2.6.2

`berks update` does not update the versions.

**Comment by yasselpiloto** [comment]
This can be worked around by removing the berkshelf cache under ~/.berkshelf and removing the Berksfile.lock
