### ISSUE TITLE
Really need to put /opt/chefdk/embedded/bin in $PATH?

### ISSUE THREAD

**Issue by rberger** [berkshelf/berkshelf#1147]
The new http://berkshelf.com/ page says:

```
Add the Chef-DK binaries directory to your path once you’ve installed the Chef-DK.

$ export PATH=/opt/chefdk/embedded/bin:$PATH
$ which berks
/opt/chefdk/embedded/bin/berks
```

But when installing ChefDK, it creates symlinks for most of the binaries installed including berks:

```
lrwxr-xr-x   1 root   wheel        21 Apr 21 11:23 berks -> /opt/chefdk/bin/berks
```

In general I'm feeling very quesy with ChefDK. Isn't this just like the same pain as Vagrant going from gems to packages? 
- How does ChefDK installed gems interact with general development and use of other gems that have chef, berkshelf, etc as dependencies?
- How does this work with bundler and rvm/rbenv?

**Comment by allaire** [comment]
@reset @rberger Sorry to bring this up but I think it's safe now to remove these instructions from Berkshelf website? ChefDK has an updated README that gives the right instructions depending on different usage scenarios.

Thanks!
