### ISSUE TITLE
Cygwin support / git clone bug?

### ISSUE THREAD

**Issue by tuxinaut** [berkshelf/berkshelf#1211]
Hello,

after hours of debugging i think berkshelf under cygwin it's completely broken with the following setup.
- Windows7 64Bit Pro
- cygwin 2.850 32Bit
- vagrant 1.6.2
- virtualbox 4.3.12
- git  1.8.5.5
- vagrant-berkshelf 2.0.1

vagrant-berkshelf works but if berkshelf tries to clone the cookbook from local path it fails.

```
tuxinaut@tuxi-win7-test ~/portal
$ LANG=C NIO4R_PURE="yes" vagrant up --provision
Bringing machine 'default' up with 'virtualbox' provider...
==> default: The cookbook path 'C:/cygwin/home/tuxinaut/.berkshelf/default/vagrant/berkshelf-20140523-3036-mfyx37-default' doesn't exist. Ignoring...
DEPRECATED: Your Berksfile contains a site location pointing to the Opscode Community Site (site :opscode). Site locations have been replaced by the source location. Change this to: 'source "https://api.berkshelf.com"' to remove this warning. For more information visit https://github.com/berkshelf/berkshelf/wiki/deprecated-locations
Updating Vagrant's berkshelf: 'C:/cygwin/home/tuxinaut/.berkshelf/default/vagrant/berkshelf-20140523-3036-mfyx37-default'
Resolving cookbook dependencies...
Fetching 'byobu' from git://github.com/karellm/cookbook-byobu.git (at master)
Berkshelf::GitLocation::GitCommandError: Git error: command `git clone --no-checkout "C:/cygwin/home/tuxinaut/.berkshelf/default/.cache/git/4eaa78bb863a6ba420dfc98b1d86009da3965080" "C:/cygwin/tmp/d20140523-2792-13m1msw"` failed. If this error persists, try removing the cache directory at 'C:/cygwin/home/tuxinaut/.berkshelf/default/.cache/git/4eaa78bb863a6ba420dfc98b1d86009da3965080'.Output from the command:

Cloning into 'C:/cygwin/tmp/d20140523-2792-13m1msw'...
fatal: '/home/tuxinaut/portal/C:/cygwin/home/tuxinaut/.berkshelf/default/.cache/git/4eaa78bb863a6ba420dfc98b1d86009da3965080' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The windows paths are the problem _git clone_ adds the current folder at the beginning of the clone url. WFT :worried: as a result the clone fails.

I don't know how i exactly resolve the problem in a easy way.

In my opinion is a solution is that berkshelf support cygwin paths. The other to explore whats going wrong with _git clone_ or give it a simple third way?

**Comment by djmittens** [comment]
Is there any solutions to this? currently getting things to work between chef and vagrant on windows is a total cluster, i must have rsync support but dammit that doesnt work in CMD, powershell has a different problem, and trying to get it to work from cygwin AND having cookbook dependencies i get this stuff.  So is there any workarounds i can try?

```
==> default: Updating Vagrant's Berkshelf...
The following berks command failed to execute:

    C:\opscode\chefdk\bin/berks.BAT vendor C:/Users/Nick/.babun/cygwin/home/Nick/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150407-1992-t7jek5-default --berksfile C:/Users/Nick/Documents/erewhon/cookbook/Berksfile

The stdout and stderr are shown below:

    stdout: Resolving cookbook dependencies...
Fetching 'erewhon' from source at .
Fetching 'nodejs' from git@github.com:redguide/nodejs.git (at master)

    stderr: Git error: command `git clone --no-checkout "C:/Users/Nick/.babun/cygwin/home/Nick/.berkshelf/.cache/git/026d6809aef553e8d5b60bcea9a1b6c940660f86" "C:/Users/Nick/AppData/Local/Temp/d20150407-6652-1fdymf9"` failed. If this error persists, try removing the cache directory at 'C:/Users/Nick/.babun/cygwin/home/Nick/.berkshelf/.cache/git/026d6809aef553e8d5b60bcea9a1b6c940660f86'.Output from the command:

fatal: failed to open '/home/Nick/documents/erewhon/cookbook/C:/Users/Nick/.babun/cygwin/home/Nick/.berkshelf/.cache/git/026d6809aef553e8d5b60bcea9a1b6c940660f86/objects': No such file or directory
```

**Comment by Monstrel** [comment]
I was able to solve this issue by removing the Cygwin version of Git, and installing Windows Git from git-scm.com

During install of Git, choose the option to modify the Windows path to include Git.  This build of Git works with Windows paths correctly and allows berkshelf to run successfully using cygwin terminal and a configuration similar to the issue opener, including cygwin, vagrant, plugin-berkshelf, Windows Git, and ChefDK.

**Comment by lamont-granquist** [comment]
we'll most likely not support cygwin.  chef-dk can be used to install berkshelf, but we don't support cygwin there either.

if that doesn't work for you, then you're largely on your own, nobody internally at chef uses cygwin.  we will happily mash green merge buttons for cygwin users, but the priority of devs at chef doing work to support cygwin is lower than low.  without PRs we cannot help you.
