### ISSUE TITLE
`berks install` does not install everything

### ISSUE THREAD

**Issue by cbandy** [berkshelf/berkshelf#1216]
The first time I run `berks install`, hard dependencies are installed and recommended dependencies are included in the lock file:

```
$ berks --version
3.1.2
```

```
$ rm Berksfile.lock
$ cat Berksfile
source 'http://api.berkshelf.com'

cookbook 'elasticsearch'
```

```
$ berks install
Resolving cookbook dependencies...
Fetching cookbook index from http://api.berkshelf.com...
Installing ark (0.8.2)
Installing elasticsearch (0.3.9)

$ cat Berksfile.lock
DEPENDENCIES
  elasticsearch

GRAPH
  ark (0.8.2)
  elasticsearch (0.3.9)
    ark (>= 0.2.4)
    build-essential (>= 0.0.0)
    java (>= 0.0.0)
    monit (>= 0.0.0)
    xml (>= 0.0.0)
```

The second time I run `berks install`, the recommended dependencies are installed:

```
$ berks install
Resolving cookbook dependencies...
Fetching cookbook index from http://api.berkshelf.com...
Using ark (0.8.2)
Installing build-essential (2.0.2)
Using elasticsearch (0.3.9)
Installing java (1.22.0)
Installing monit (0.7.1)
Installing xml (1.2.4)
```

---

Without these recommended dependencies, `vagrant-berkshelf` complains:

```
Uploading cookbooks to 'http://192.168.33.1:4000'
Berkshelf::DependencyNotFound: Dependency 'monit' was not found. Please make sure it is in your Berksfile, and then run `berks install` to download and install the missing dependencies.
```

**Comment by jujugrrr** [comment]
I have the same error as well.
`berks install` will add the `recommends` to my Berksfile.lock. If I run `berks upload` I get 
```
Dependency 'curl' was not found. Please make sure it is in your Berksfile, and then run berks install to download and install the missing dependencies.
```

So `berks upload` requires the `recommends` but `berks install` doesn't get them ?

It forces us to add the recommended cookbook (by other cookbooks) to our own metatada, which kind of defeats the purpose of letting Berkshelf follow the metadata from other cookbook.

**Comment by 8la** [comment]
Updates?

**Comment by abhinandankothari** [comment]
I too got the same error , did what @jujugrrr suggested to make `berks upload` successful. Any updates on resolving this issue ?

**Comment by mlanin** [comment]
Same here. I'm using `zabbix-agent` cookbook. It recommends `libzabbix` cookbook. `berks install` adds it to the Berksfile.lock, but doesn't install it. And `berks upload` fails.

```bash
$ berks -v
4.0.1
```

**Comment by lamont-granquist** [comment]
foodcritic has warned not to use `recommends` or `suggests` for a long time.  they were never supported at all.  there is an approved RFC to remove them permanently from chef:

https://github.com/chef/chef-rfc/pull/245

the cookbooks that use them should be updated.
