### ISSUE TITLE
berks install broken (v2.0.*)

### ISSUE THREAD

**Issue by dhawal55** [berkshelf/berkshelf#1235]
First, gem install berkshelf -v 2.0.\* is broken as it cannot resolve buff-extensions dependency.

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: ridley requires buff-extensions (~> 0.3); buff-config requires buff-extensions (~> 0.3)

I got past that issue by manually install buff-extensions.

Now i get an error when using berks install:
 `raise_if_conflicts': Unable to activate buff-config-0.4.0, because buff-extensions-1.0.0 conflicts with buff-extensions (~> 0.3) (Gem::LoadError)

I'm using ruby version 1.9.3p484 (2013-11-22) [i386-mingw32]

**Comment by jacketattack** [comment]
I was having this issue whenever I tried to run any berks command and found a solution by specifically installing version 0.3.2 of varia_model. This removes the need for buff-extensions 1.0.0.

`gem uninstall varia_model --force`
`gem install varia_model -v 0.3.2`
