### ISSUE TITLE
can't upload cookbook only with berks 

### ISSUE THREAD

**Issue by baryonicdm** [berkshelf/berkshelf#1266]
hello.
there seems to be some issue with uploading cookbook with berks
you can see that cookbook upload works well with normal knife cookbook upload command

``` text
$ knife cookbook upload iptables-0.13.2 -o ~/.berkshelf/cookbooks/
Uploading iptables-0.13.2 [0.13.2]
Uploaded 1 cookbook.
```

``` text
$ knife cookbook list
iptables-0.13.2   0.13.2
```

but .. berks command does'nt work 
it says "There was an error connecting to the Chef Server"
you can find berks file here : https://github.com/stackforge/openstack-chef-repo/blob/master/Berksfile

``` text
$ berks upload -b ./Berksfile 
Using apache2 (1.9.6)
Using apt (2.3.8)
Using aws (2.1.1)
Using build-essential (1.4.2)
Using database (2.0.0)
Using erlang (1.4.2)
Using memcached (1.7.2)
Using mysql (4.1.2)
Using openssl (1.1.0)
Using postgresql (3.3.4)
Using python (1.4.6)
Using rabbitmq (3.0.4)
Using xfs (1.1.0)
Using yum (3.1.4)
Using selinux (0.7.2)
Using yum-epel (0.3.4)
Installing statsd (0.1.6) from git: 'git://github.com/att-cloud/cookbook-statsd.git' with branch: 'master' at ref: 'd3298ae4ec4a6d8cc2ca166f0688a92753ced338'
Installing openstack-block-storage (9.4.0) from git: 'git://github.com/stackforge/cookbook-openstack-block-storage.git' with branch: 'master' at ref: 'ff5c57b7ae2d7a435e0fb6f45a5759591dfc5ac0'
Installing openstack-common (9.7.0) from git: 'git://github.com/stackforge/cookbook-openstack-common.git' with branch: 'master' at ref: '0c30f2f4e9730029e7ad6aa33f0fc6e1fa8da8b6'
Installing openstack-compute (9.3.1) from git: 'git://github.com/stackforge/cookbook-openstack-compute.git' with branch: 'master' at ref: '46c30ed4d10e20b1caa177ccac4c4dfa524eeaab'
Installing openstack-dashboard (9.1.0) from git: 'git://github.com/stackforge/cookbook-openstack-dashboard.git' with branch: 'master' at ref: '4e64a26fb327a33e25c97dd874837bbd49fe2063'
Installing openstack-identity (9.3.1) from git: 'git://github.com/stackforge/cookbook-openstack-identity.git' with branch: 'master' at ref: 'a0b82401fb589ab9b88c624f40a608e755a04385'
Installing openstack-image (9.2.0) from git: 'git://github.com/stackforge/cookbook-openstack-image.git' with branch: 'master' at ref: '05e2e9b310c013bccea1be744e6a971d9a6db090'
Installing openstack-network (9.1.1) from git: 'git://github.com/stackforge/cookbook-openstack-network.git' with branch: 'master' at ref: '905ae152abd2d52c352c1df5888a41bb9694a0fc'
Installing openstack-object-storage (9.0.3) from git: 'git://github.com/stackforge/cookbook-openstack-object-storage.git' with branch: 'master' at ref: '3aa81b766c946fa1ccbf84111d2e5cc644a78afd'
Installing openstack-ops-database (9.1.0) from git: 'git://github.com/stackforge/cookbook-openstack-ops-database.git' with branch: 'master' at ref: '86d87c4827655adb31dbf0f4c8d5cf8f59bd4e69'
Installing openstack-ops-messaging (9.0.1) from git: 'git://github.com/stackforge/cookbook-openstack-ops-messaging.git' with branch: 'master' at ref: 'a5eb4edef4abab10b783ed9884aacd95c6248595'
Installing openstack-orchestration (9.2.0) from git: 'git://github.com/stackforge/cookbook-openstack-orchestration.git' with branch: 'master' at ref: '05e0da7907f03a305a768939f68a24a956382d85'
Installing openstack-telemetry (9.3.0) from git: 'git://github.com/stackforge/cookbook-openstack-telemetry.git' with branch: 'master' at ref: '762493d48d7da43812d4e7bac37a8bd25a08807b'
Using iptables (0.13.2)
Using logrotate (1.6.0)
Using pacman (1.1.1)
Using yum-erlang_solutions (0.2.0)
Using runit (1.5.10)
Using homebrew (1.7.2)
Using windows (1.32.3)
Using chef_handler (1.1.6)
Using git (4.0.2)
Using dmg (2.2.0)
Uploading apache2 (1.9.6) to: 'https://stackforge:443/'
There was an error connecting to the Chef Server
```

it's strange that roles are uploaded well.. but only cookbooks doesn't

``` text
$ knife role list
allinone-compute
os-base
os-block-storage
os-block-storage-api
os-block-storage-scheduler
os-block-storage-volume
os-client
os-compute-api
os-compute-api-ec2
os-compute-api-metadata
os-compute-api-os-compute
os-compute-cert
os-compute-conductor
os-compute-scheduler
os-compute-setup
os-compute-single-controller
os-compute-vncproxy
os-compute-worker
os-dashboard
os-identity
os-image
os-image-api
os-image-registry
os-image-upload
os-network
os-network-dhcp-agent
os-network-l3-agent
os-network-metadata-agent
os-network-openvswitch
os-network-server
os-object-storage
os-object-storage-account
os-object-storage-container
os-object-storage-management
os-object-storage-object
os-object-storage-proxy
os-ops-caching
os-ops-database
os-ops-messaging
os-telemetry-agent-central
os-telemetry-agent-compute
os-telemetry-api
os-telemetry-collector
```

is this even possible? 

``` text
$ ls
Berksfile       CHANGELOG.md  Gemfile       infrastructure.yml       LICENSE    roles       Vagabondfile             Vagrantfile-aio-nova
Berksfile.lock  environments  Gemfile.lock  infrastructure.yml.back  README.md  TESTING.md  Vagrantfile-aio-neutron  Vagrantfile-multi-neutron
```

``` text
$ ls ~/.berkshelf/cookbooks/
apache2-1.9.6                                                     openstack-image-05e2e9b310c013bccea1be744e6a971d9a6db090
apt-2.3.8                                                         openstack-network-905ae152abd2d52c352c1df5888a41bb9694a0fc
aws-2.1.1                                                         openstack-object-storage-3aa81b766c946fa1ccbf84111d2e5cc644a78afd
build-essential-1.4.2                                             openstack-ops-database-86d87c4827655adb31dbf0f4c8d5cf8f59bd4e69
chef_handler-1.1.6                                                openstack-ops-messaging-a5eb4edef4abab10b783ed9884aacd95c6248595
database-2.0.0                                                    openstack-orchestration-05e0da7907f03a305a768939f68a24a956382d85
dmg-2.2.0                                                         openstack-telemetry-762493d48d7da43812d4e7bac37a8bd25a08807b
erlang-1.4.2                                                      pacman-1.1.1
git-4.0.2                                                         postgresql-3.3.4
homebrew-1.7.2                                                    python-1.4.6
iptables-0.13.2                                                   rabbitmq-3.0.4
logrotate-1.6.0                                                   runit-1.5.10
memcached-1.7.2                                                   selinux-0.7.2
mysql-4.1.2                                                       statsd-d3298ae4ec4a6d8cc2ca166f0688a92753ced338
openssl-1.1.0                                                     windows-1.32.3
openstack-block-storage-ff5c57b7ae2d7a435e0fb6f45a5759591dfc5ac0  xfs-1.1.0
openstack-common-0c30f2f4e9730029e7ad6aa33f0fc6e1fa8da8b6         yum-3.1.4
openstack-compute-46c30ed4d10e20b1caa177ccac4c4dfa524eeaab        yum-epel-0.3.4
openstack-dashboard-4e64a26fb327a33e25c97dd874837bbd49fe2063      yum-erlang_solutions-0.2.0
openstack-identity-a0b82401fb589ab9b88c624f40a608e755a04385
```

**Comment by acqant** [comment]
I have the same issue with a purchased certificate and knife verify works.

**Comment by glenjamin** [comment]
I just ran into this, and found that the way to use the `knife verify` trusted certifcate is to do:

```sh
SSL_CERT_FILE=.chef/trusted_certs/<hostname>.crt berks upload
```

**Comment by germs12** [comment]
:+1: Also having this issue. `--no-ssl-verify` works great for me, but agree with @sethvargo that we should be using SSL.

Aside from using @glenjamin suggestion, is their a solution?  Thanks!

**Comment by rambler** [comment]
I ran into a similar problem that I'm noting here in case anyone else has the same symptoms: I could upload one cookbook via berks upload but would consistently fail on another. 

The issue was a stray large .csv file. Perhaps it took too long to transfer? When I removed this file, the problem went away.

**Comment by Joseph-R** [comment]
I ran into the same issue today.  

```
$ chef -v
Chef Development Kit Version: 0.5.1
chef-client version: 12.3.0
berks version: 3.2.3
kitchen version: 1.4.0
```

Temporarily working around it with `berks upload --no-ssl-verify`, but I agree that it would be a) good to get SSL working and b) get it working based off the settings in the `.chef` directory and `knife.rb` configs without having to edit the `.berkshelf/config.json`.

**Comment by ivanovteo** [comment]
A solution would be to have config.json with only the bellow entries. In this way you can modify the knife.rb and berkshelf will know about them but will override only the ssl part.
{
  "ssl": {
    "verify": false
  }
}

**Comment by afiune** [comment]
Just letting you all know that the `chefdk` version `0.7.0` has a bug with `berkshelf` using SSL Certificates. It will get fixed with https://github.com/berkshelf/berkshelf-api-client/pull/11 on the new version `0.8.0` coming soon. 

Hope this helps!

**Comment by dbarrell** [comment]
@glenjamin I also solved this by adding the following to my ~/.bash_profile:

```
export SSL_CERT_FILE="$HOME/.chef/trusted_certs/<hostname>.crt"
```
Now you won't need to use ```--no-ssl-verify```

**Comment by drahamim** [comment]
I just updated to ChefDK v 0.9.0 
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

berks -v = 4.0.1
I am encountering this issue. I am using an internal Chef server with a self signed certificate. Knife works fine but Berkshelf is still reporting errors with certificates.

**Comment by steowens** [comment]
I am getting the same error.  But it was working earlier today.

**Comment by jwalton** [comment]
I ran into this bug today, but after doing a little digging, and scrolling up a bit further in the log, I discovered I had a syntax error in one of my .rb files, and fixing it made this problem go away.  O_o

**Comment by spuder** [comment]
I'm also encountering this error. I have 2 chef servers. (chef-lab, chef-prod) I use a gitlab-ci node to automate uploading cookbooks when a git repo changes. 

```
CHEF_ENV=nd-prod chef --version
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```
This problem began when I upgraded chef server to from 12.4 to 12.5.1 today. The server has a publicly signed certificate and all other knife and berks commands succeed. 

```
gitlab-runner@gitci01:~/builds/ac48e546/0/foo/bar$ CHEF_ENV=nd-lab BERKSHELF_DEBUG=1 berks upload
Skipping chef_handler (1.2.0) (frozen)
Skipping iis (4.1.1) (frozen)
/home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each': task was terminated (Celluloid::Task::TerminatedError)
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/actor.rb:321:in `handle_crash'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/actor.rb:166:in `rescue in run'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/actor.rb:148:in `run'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/berkshelf-4.0.1/lib/berkshelf/uploader.rb:55:in `block (2 levels) in upload'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/berkshelf-4.0.1/lib/berkshelf/uploader.rb:51:in `each'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/berkshelf-4.0.1/lib/berkshelf/uploader.rb:51:in `block in upload'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/ridley-4.3.2/lib/ridley/client.rb:38:in `open'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/ridley-4.3.2/lib/ridley.rb:53:in `open'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/berkshelf-4.0.1/lib/berkshelf.rb:144:in `ridley_connection'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/berkshelf-4.0.1/lib/berkshelf/uploader.rb:50:in `upload'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/berkshelf-4.0.1/lib/berkshelf/uploader.rb:37:in `run'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/berkshelf-4.0.1/lib/berkshelf/berksfile.rb:545:in `upload'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/berkshelf-4.0.1/lib/berkshelf/cli.rb:208:in `upload'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/berkshelf-4.0.1/lib/berkshelf/cli.rb:52:in `dispatch'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/berkshelf-4.0.1/lib/berkshelf/cli.rb:27:in `execute!'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/gems/berkshelf-4.0.1/bin/berks:5:in `<top (required)>'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/bin/berks:23:in `load'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/bin/berks:23:in `<main>'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/gitlab-runner/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
gitlab-runner@devops-gitci01:~/builds/ac48e546/0/devops/nd-web$
```

I've [run into this problem months ago](http://pastebin.com/hA0mxQX8), and in the past fixed it by modifying my $PATH. That did not fix the problem today

**Comment by faizalzakaria** [comment]
I encounter the same problem as mentioned by @spuder . 

This is using berks version `4.2.1` with chef server hosted by Opscode/Chef.

**Comment by Deserved** [comment]
Ran onto same problem:

berks v4.3.1, knife can upload berks can not.

Has it something to do with cookbooks being on S3?

**Comment by leonardodavinte** [comment]
# berks -v
4.3.3

Works for me:

1.
export SSL_CERT_FILE=$HOME/chef-repo/.chef/trusted_certs/chef-server-01.crt
berks upload

Or

2.
berks upload --no-ssl-verify

Thanks.

**Comment by meganuke19** [comment]
Any news about add ssl_verify = false option in knife.rb?

**Comment by yanxinyuan** [comment]
Same problem. @obazoud 's suggestion of --no-ssl-verify works well.
E, [2016-09-27T18:14:12.251728 #14166] ERROR -- : Ridley::Errors::ClientError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
E, [2016-09-27T18:14:12.253015 #14166] ERROR -- : /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/responses.rb:29:in `value'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
(celluloid):0:in `remote procedure call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.6.1/lib/ridley/resource.rb:132:in `raw_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.6.1/lib/ridley/resource.rb:123:in `request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.6.1/lib/ridley/resources/cookbook_resource.rb:96:in `find'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.6.1/lib/ridley/resources/cookbook_resource.rb:190:in `upload'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
(celluloid):0:in `remote procedure call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/uploader.rb:55:in `block (2 levels) in upload'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/uploader.rb:51:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/uploader.rb:51:in `block in upload'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.6.1/lib/ridley/client.rb:38:in `open'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.6.1/lib/ridley.rb:56:in `open'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf.rb:144:in `ridley_connection'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/uploader.rb:50:in `upload'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/uploader.rb:37:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:592:in `upload'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/cli.rb:208:in `upload'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/cli.rb:52:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/cli.rb:27:in `execute!'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/bin/berks:5:in `<top (required)>'
/opt/chefdk/embedded/bin/berks:22:in `load'
/opt/chefdk/embedded/bin/berks:22:in `<main>'
There was an error connecting to the Chef Server
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf.rb:147:in `rescue in ridley_connection'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf.rb:122:in `ridley_connection'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/uploader.rb:50:in `upload'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/uploader.rb:37:in `run'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:592:in `upload'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/cli.rb:208:in `upload'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/cli.rb:52:in `dispatch'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/cli.rb:27:in `execute!'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/bin/berks:5:in `<top (required)>'
	/opt/chefdk/embedded/bin/berks:22:in `load'
	/opt/chefdk/embedded/bin/berks:22:in `<main>'
[root@delta push-jobs]# berks upload --no-ssl-verify
Uploaded chef-ingredient (0.21.0) to: 'https://delta.chef.server:443/organizations/delta'
Uploaded compat_resource (12.14.7) to: 'https://delta.chef.server:443/organizations/delta'
Uploaded packagecloud (0.2.5) to: 'https://delta.chef.server:443/organizations/delta'
Uploaded push-jobs (3.2.2) to: 'https://delta.chef.server:443/organizations/delta'
Uploaded runit (3.0.0) to: 'https://delta.chef.server:443/organizations/delta'
Uploaded test (1.0.0) to: 'https://delta.chef.server:443/organizations/delta'
Uploaded yum (4.0.0) to: 'https://delta.chef.server:443/organizations/delta'
Uploaded yum-epel (1.0.1) to: 'https://delta.chef.server:443/organizations/delt

**Comment by scarolan** [comment]
I was also able to replicate this issue.  We have config.json with this in it:
```
  "ssl": {
      "verify": false
    }
```
But berks is apparently not honoring that file.  Adding --no-ssl-verify fixes the issue.

**Comment by giladsh1** [comment]
`echo '{"ssl": { "verify": false }}' > ~/.berkshelf/config.json` worked for me.
Chef Development Kit Version: 1.1.16
chef-client version: 12.17.44
berks version: 5.2.0
kitchen version: 1.14.2

**Comment by lamont-granquist** [comment]
declaring bankruptcy on this issue.  please file new well-formed issues if there are concrete issues to solve with berkshelf.
