### ISSUE TITLE
Integrate with Chef configuration

### ISSUE THREAD

**Issue by reset** [berkshelf/berkshelf#1271]
Now that Berkshelf is part of the ChefDK we should work at covering any seams which are present that indicate that Berkshelf is a separate entity. It should work well with the ecosystem installed by ChefDK and the instructions to get started should be dead simple.

Let's move from our own JSON configuration file to using the Chef configuration. It is most ideal to define a [new config context like Chef Zero](https://github.com/opscode/chef/blob/master/lib/chef/config.rb#L324-L329) or Knife has within the Chef configuration.

An alternative approach is to define a Berkshelf hash inside of the Knife config context which we can merge defaults and validate with.

/cc @sethvargo @ivey

**Comment by thommay** [comment]
I think this has been implemented; at least to the extent that ridley and berkshelf load the chef client config and make it available.
