### ISSUE TITLE
Add option or new command to generate an environment file from Berksfile.lock

### ISSUE THREAD

**Issue by jperry** [berkshelf/berkshelf#1273]
Instead of applying directly to the chef server it would be nice if you could generate the environment file rather having it write directly to the chef server for cases where you want to source control it first then have your CI server push the environment file.

**Comment by bbaugher** [comment]
I wrote a [gem](https://github.com/bbaugher/chef-berksfile-env) which allows an envrionment in `.rb` format to load the `Berksfile.lock` version constraints. Effectively the same thing but reverse in implementation.

**Comment by jsirex** [comment]
@bbaugher, really nice solution! You saved me :)

**Comment by thommay** [comment]
Given the existence of the above gem, and also Policyfiles, we are treating berkshelf as feature complete at this time. I'm going to close this ticket, thanks for your interest.
