### ISSUE TITLE
Support of multiple cookbook with same name

### ISSUE THREAD

**Issue by dieend** [berkshelf/berkshelf#1306]
I would like berks have this feature. Currently, if Berksfile contain 2 cookbooks with same name, it will raise an error:

```
Your Berksfile contains multiple entries named 'apache2'. Please remove duplicate dependencies, or put them in different groups.
```

Why I'd like to have this feature? It is because amazon opswork have this flow:

```
For Chef 11.10 stacks, after AWS OpsWorks installs the built-in, custom, and Berkshelf cookbooks, it merges them to a common directory in the following order:

1. Built-in cookbooks.
2. Berkshelf cookbooks, if any.
3. Custom cookbooks, if any.

When AWS OpsWorks performs this merge, it copies the entire contents of the directories, including recipes. If there are any duplicates, the following rules apply:

* The contents of Berkshelf cookbooks take precedence over the built-in cookbooks.
* The contents of custom cookbooks take precedence over the Berkshelf cookbooks.

To illustrate how this process works, consider the following scenario, where all three cookbook directories include a cookbook named mycookbook:

* Built-in cookbooks – mycookbook includes an attributes file named someattributes.rb, a template file named sometemplate.erb, and a recipe named somerecipe.rb.
* Berkshelf cookbooks – mycookbook includes sometemplate.erb and somerecipe.rb.
* Custom cookbooks – mycookbook includes somerecipe.rb.

The merged cookbook contains the following:

* someattributes.rb from the built-in cookbook.
* sometemplate.erb from the Berkshelf cookbook.
* somerecipe.rb from the custom cookbook.
```

http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-chef11-10.html

In sort, opsworks merged the cookbook. It would be great if Berks can do this so we can simulate what opsworks doing.

**Comment by sheldonh** [comment]
Just try to use any cookbook that uses the community unicorn cookbook (e.g. "https://github.com/fsultan/rackbox-cookbook), and watch AWS OpsWorks explode because it has its own unicorn recipe.

The AWS OpsWorks cookbook is here: https://github.com/aws/opsworks-cookbooks

But in my opinion, this is a bug in the AWS OpsWorks cookbook; it should rename unicorn to opsworks_unicorn. Or there should be namespace support in Chef. ;-)

**Comment by dieend** [comment]
@arsduo No, I can't exactly mimic the opsworks behavior. In the end I just uses vagrant that uses our own cookbook, + deploy cookbook from opsworks.

I agree AWS at faults here. We already create the issue some times ago: https://github.com/aws/opsworks-cookbooks/issues/217

**Comment by reset** [comment]
@sheldonh @dieend they need to change the names of the cookbooks in that repository or the project is pointless. Sorry for the pain, but they're wrong.

**Comment by jshthornton** [comment]
+1
