### ISSUE TITLE
berks vendor/package & chefignore: how to ignore files in subdirectories?

### ISSUE THREAD

**Issue by thomas-riccardi** [berkshelf/berkshelf#1317]
Hi,

The default `chefignore` file generated by `chef generate cookbook test-cookbook` (from chef-dk 0.3.0) contains the following lines:

```
# EDITORS #
###########
\#*
.#*
*~
```

Using `berks vendor` the last line excludes all files ending by `~`, but only on the root directory. 
Is this normal?
If yes, how do we ignore all files ending by `~` regardless of the directory?
`*/*~` doesn't work either.

How to reproduce:

```
$ chef generate cookbook test-berkshelf-chefignore
Compiling Cookbooks...
...
$ cd test-berkshelf-chefignore
$ echo "*/*~" >> chefignore
$ touch test1~
$ touch recipes/test2~
$ berks vendor test
Resolving cookbook dependencies...
Fetching 'test-berkshelf-chefignore' from source at .
Using test-berkshelf-chefignore (0.1.0) from source at .
$ find test -name '*~'
test/test-berkshelf-chefignore/recipes/test2~
```

**Comment by ifeltsweet** [comment]
+1
