### ISSUE TITLE
downloader for file_store that hold different cookbook version

### ISSUE THREAD

**Issue by lytao** [berkshelf/berkshelf#1343]
The current "lib/berkshelf/downloader.rb" require file_store directory to have the following structure:
e.g.
/opt/cookbooks/cookbookA
/opt/cookbooks/cookbookB
...
But we need to hold different version like,
/opt/cookbooks/cookbookA-0.0.1
/opt/cookbooks/cookbookA-0.0.2
...

Could you please handle the download from file_store more flexible? Here is the patch code:

```
148c148
<         File.join(tmp_dir, File.basename(remote_cookbook.location_path))
---
>         File.join(tmp_dir, name)
```

Leo

**Comment by thommay** [comment]
This looks like it's been fixed in the meantime. If you're still having a problem, please describe your use case and we'll take another look.
Thanks for your submission!
