### ISSUE TITLE
Berksfile shouldn't require a 'source' declaration

### ISSUE THREAD

**Issue by bryanwb** [berkshelf/berkshelf#1348]
I work in a couple environments where all the cookbooks are sourced from git and there is no supermarket, nor Internet access. My Berksfile has no cookbooks that pull from a default 'source', in these cases, Berkshelf shouldn't error out w/ the message that a cookbook source must be provided

**Comment by evandhoffman** [comment]
+1

**Comment by StFS** [comment]
+1

**Comment by petere** [comment]
see also #1281

**Comment by ruizink** [comment]
+1

**Comment by jgoldschrafe** [comment]
The CLI completes execution (but exits with a non-zero code), but this still blows up in Test Kitchen with `Berkshelf::NoAPISourcesDefined`.

**Comment by lamont-granquist** [comment]
never going to be fixed in berkshelf.  policyfiles with a chef-repo source might be a viable alternative solution.
