### ISSUE TITLE
Option to support 'global' plugins

### ISSUE THREAD

**Issue by mivok** [berkshelf/berkshelf#1354]
Hi,

I'm interested in writing an additional command (e.g. `berks foo`) for berkshelf as a plugin, but as far as I can tell, currently plugins are loaded using `extension 'foo'` from a specific Berksfile, and the extension is only loaded once the Berksfile is read.

Would it be possible to implement a way to load extensions from the global berkshelf configuration? I see the implmentation being almost identical to that for loading a plugin from the Berksfile (require 'berkshelf/#{name}') only with the list of extensions coming from the config file instead.

I'm happy to submit a PR with code to implement this. I wanted to run it by you guys first to see if it makes sense and/or if there's something obvious I'm missing.

**Comment by lamont-granquist** [comment]
Since berks is more in maintenance-phase right now, features like this should probably go into ChefDK instead.
