### ISSUE TITLE
Install "recommendations" from metadata only if the cookbook is cached

### ISSUE THREAD

**Issue by jujugrrr** [berkshelf/berkshelf#1362]
Hello,

Somehow it seems Berkshelf is adding 'recommends' dependencies from cookbook metadata but only if the cookbook is cached in Berkshelf. 

Here is an example with newrelic cookbook, you can see curl dependency is only added the second time I run berkshelf. https://gist.github.com/jujugrrr/4f08343a45b762f893db . 

Is it related to this https://github.com/berkshelf/berkshelf/blob/bad0f07e7bf0f7d59ec3d71083a246288839ccee/lib/berkshelf/cached_cookbook.rb#L37 ?

Is it an expected behavior?

Thank you!

ps : it's probably related to https://github.com/berkshelf/berkshelf/issues/1216

**Comment by sethvargo** [comment]
@reset I think we should just ignore recommendations to encourage people to stop using them...

**Comment by jujugrrr** [comment]
@sethvargo Fine with me :-)

**Comment by reset** [comment]
@sethvargo I think we should keep the original behaviour and just treat them exactly the same as depends.

@jujugrrr it is not the intended behaviour to sometimes ignore cookbooks listed as "recommended". Thanks for pointing this one out.

**Comment by martinb3** [comment]
:+1:

**Comment by 8la** [comment]
Any updates on this?

**Comment by lamont-granquist** [comment]
right now core chef development strongly recommends not using recommends at all.

foodcritic has warned about using them for over a  year:  https://github.com/acrmp/foodcritic/pull/309
