### ISSUE TITLE
Berkshelf fails to parse metadata.rb when referencing cookbook from local directory / git / github

### ISSUE THREAD

**Issue by tboloo** [berkshelf/berkshelf#1366]
Environment:
* Mac OS 10.9
* Vagrant 1.7.1
* Berkshelf 3.2.1 (from chefDK)
* vagrant-berkshelf plugin 4.0.2

If I try to reference local / git / github based cookbooks I got an error as follows:
```
stderr: An error occurred while reading the Berksfile:

  Could not parse `/Volumes/Macintosh HD/Vagrant/planq/metadata.rb': '{:path=>"~/cookbooks/xdebug"}' did not contain a valid operator or a valid version string.


It appears that you are not using the ChefDK. Please note that Vagrant Berkshelf
works best when used with the ChefDK, and other installation methods are not
officially supported.
```
despite the fact that I *do* have chefDK installed
```
joshua$ which berks
/usr/bin/berks
joshua$ ls -la /usr/bin/berks 
lrwxr-xr-x  1 root  wheel  21 Jan  2 23:00 /usr/bin/berks -> /opt/chefdk/bin/berks
```
My metadata.rb file:
```
name             'project'
maintainer       'author'
maintainer_email 'author@email.com'
license          'All rights reserved'
description      'lorem ipsum'
long_description 'lorem ipsum'
version          '0.2.0'

depends 'apache2'
depends 'php'
depends 'mysql', '~> 6.0'
depends 'database'
depends 'apt'
depends 'mysql_chef_gem'
depends 'xdebug', :path => '~/cookbooks/xdebug'
```
Also, I tried moving project files to path with no spaces, the result is the same.
Berksfile (for the record):
```
source "https://supermarket.getchef.com"
metadata
```

**Comment by sethvargo** [comment]
@tboloo that is not a valid `metadata.rb`... You cannot specify `path` locations in a `metadata.rb`. Chef only permits you to specify a name and optionally a version. 

You need to specify the `path` attribute in the `Berksfile`:

```ruby
source "https://supermarket.getchef.com"
cookbook "xdebug", path: "~/cookbooks/xdebug"
metadata
```

And then just have `depends "xdebug"` in your `metadata.rb`.

**Comment by tboloo** [comment]
Silly me... Just learning chef, berkshelf, vagrant and I must have got it confused. Thanks for your help, I got it working now.
