### ISSUE TITLE
Getting undefined method `retryable' on new v3.2.3

### ISSUE THREAD

**Issue by mwrock** [berkshelf/berkshelf#1370]
Looking at the commit log for 3.2.3, looks like retriable was bumped. I dont have time now to troubleshoot further but wanted to atleast file this.

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [undefined method `retryable' for #<Ridley::Connection:0x00000005b0ba30>]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by reset** [comment]
@mwrock this is a stack-trace from test kitchen regarding an error in Ridley. There isn't enough information for me here to diagnose the problem other than to recommend you ensure you have the latest version of Ridley in your Ruby environment. We're still waiting on a new ChefDK release which will include the latest Berkshelf, Test Kitchen, and all it's supporting libraries.

**Comment by mwrock** [comment]
ok. thats reasonable. Apologies for the randomization.

**Comment by reset** [comment]
@mwrock no problem at all, what version of Ridley is in your Ruby env?

**Comment by mwrock** [comment]
its 4.0.0 and retryable is 1.3.6 which gets bumped to 2.0.0 after doing a gem install berkshelf and upgrading to 2.3.3 from 2.3.2. Like you mentioned, likely something in dk loading 1.3.6.

**Comment by reset** [comment]
@mwrock Ridley 4.1.2 was released to coincide with the changes in Berkshelf. Install that version and hang tight for the new ChefDK release.
