### ISSUE TITLE
berks upload resolving wrong client_key path from knife.rb

### ISSUE THREAD

**Issue by cmoad** [berkshelf/berkshelf#1376]
Windows w/ChefDK 0.3.6
Berkshelf 3.2.1

All berks commands work fine until I try to upload my cookbooks. It looks like it is processing the knife.rb file incorrectly.

    E, [2015-01-24T14:49:40.124304 #14288] ERROR -- : Ridley::Errors::ClientKeyFileNotFoundOrInvalid: client key is invalid or not found at: 'C:/Users/cmoad/Source/chef/.chef/#<Proc:0x3ddc7f0@C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.0/lib/ridley/chef/config.rb:46 (lambda)>.pem'

knife.rb

    node_name                ( ENV['CHEF_USER'] || ENV['USER'] || ENV['USERNAME'] ).downcase
    client_key               "#{current_dir}/#{node_name}.pem"

I even tried hardcoding it: (doesn't work)

    node_name                "cmoad"
    client_key               "#{current_dir}/#{node_name}.pem"

This works, but doesn't allow knife.rb to be sharable:

    client_key               "#{current_dir}/cmoad.pem"

**Comment by reset** [comment]
@cmoad `node_name` is a proc being injected into a string, you'll need this instead: `client_key "#{current_dir}/#{node_name.call}.pem"
