### ISSUE TITLE
Dependancy resolution fails when using github: in cookbooks brought in via path:

### ISSUE THREAD

**Issue by cooperaj** [berkshelf/berkshelf#1379]
This is going to be a little tricky to explain but I'll give it a go. I have a web application that uses vagrant for development purposes. It uses mongo and solr and I have a set of chef cookbooks of my own devising that set those up (along with official ones I update manually every now and then). I'm attempting to convert it all to a vagrant-berkshelf driven setup to help my fellow developers.

I have a single berksfile at the root of my application (along with the vagrant file) that loads the solution specific cookbooks I have in the vagrant folder hierarchy.

```ruby
source "https://supermarket.chef.io"

cookbook "server", path: "vagrant/chef/cookbooks/server"
```

This works fine as long as the cookbook in question doesn't then try to load cookbooks from github: or git: locations. If I attempt to do this I get errors like:

```
D, [2015-01-27T15:36:19.493393 #6993] DEBUG -- :   Starting resolution...
Unable to satisfy constraints on package tomcat-solr due to solution constraint (server = 0.1.0). Solution constraints that may result in a constraint on tomcat-solr: [(server = 0.1.0) -> (tomcat-solr >= 0.1.2)]
```

In the case of above I had the following in my server cookbook

Berksfile
```ruby
source "https://supermarket.chef.io"
metadata

cookbook "tomcat-solr", github: "cooperaj/tomcat-solr"
```

metadata.rb
```ruby
...
depends "tomcat-solr", ">= 0.1.2"
...
```

I ended up resolving this by moving the cookbook line from my server cookbook up into the application Berksfile. It all then works swimmingly, if, in my opinion, a little inelegantly.

**Comment by sethvargo** [comment]
Berkshelf does not recursively evaluate Berksfiles. You need to declare those path and GitHub dependencies in each cookbook you want to use them in (even for transitive dependencies).

**Comment by cooperaj** [comment]
But other cookbooks I have that don't try to use github: or git: urls and just use the standard source appear to work fine. i.e. they go and merrily download apt and mongo and all that.

**Comment by sethvargo** [comment]
@cooperaj correct, because `path`, `github`, `svn`, etc are not artifact locations. Berkshelf will search the Supermarket or Berkshelf API servers you have defined for those artifacts.
