### ISSUE TITLE
berks package intermittently does not include lock file

### ISSUE THREAD

**Issue by donbecker** [berkshelf/berkshelf#1381]
We use berks package to package all our cookbooks up for usage with berkflow (blo install). 

Sometimes our packages are not including the lock file, even if it existed locally prior to packaging.

"blo install" works correctly, but attempting to "blo upgrade", we receive the following error: 

"<cookbookname> (<cookbookversion>) did not contain a Berksfile.lock". 

We have recently started using the debug flag with berks package (to display in the log the dependencies used), but have had cookbooks packaged with the lock file successfully in the past while using the debug flag. 

I have the console log of the entire berks package run (saved in Jenkins), please let me know if there is anything in there I should post or look for to troubleshoot this issue.

**Comment by reset** [comment]
@donbecker what operating system is building the package?

**Comment by donbecker** [comment]
@reset Ubuntu 12.04, 64bit. Berkshelf was installed via ChefDK. 

+ chef verify
Running verification for component 'berkshelf'
Running verification for component 'test-kitchen'
Running verification for component 'chef-client'
Running verification for component 'chef-dk'
Running verification for component 'chefspec'
................
---------------------------------------------
Verification of component 'berkshelf' succeeded.
Verification of component 'test-kitchen' succeeded.
Verification of component 'chef-dk' succeeded.
Verification of component 'chef-client' succeeded.
Verification of component 'chefspec' succeeded.
+ berks -v
3.2.1
+ chef -v
Chef Development Kit Version: 0.3.5
+ knife -v
Chef: 11.18.0.rc.1
+ which chef
/usr/bin/chef
+ which berks
/usr/bin/berks
+ foodcritic -V
foodcritic 4.0.0
+ which foodcritic
/usr/bin/foodcritic

**Comment by reset** [comment]
@donbecker thanks for the info. I've personally never seen this and, after reviewing the code, I don't see what would be the cause. Any debug output that you have of a run which did not properly package the lockfile would be awesome to help track this down!

**Comment by donbecker** [comment]
@reset after digging further, it appears our chefignore file in this cookbook listed the Berksfile.lock file. 

Since a cookbook packaged with "berks package" cannot be applied with "blo upgrade (berkflow)" without the lock file, could "berks package" be modified to always include the lock file, despite chefignore?

**Comment by lamont-granquist** [comment]
ignoring the chefignore is most likely very bad practice.  we're also more likely to be putting effort into policyfiles rather than this.  PRs welcome to fix this workflow, but otherwise it won't be getting any attention.
