### ISSUE TITLE
"berks upload" Leaving out a File

### ISSUE THREAD

**Issue by dmill** [berkshelf/berkshelf#1382]
I have a file in one of my cookbooks under files/default/chef-client called "validation.pem.bak". When I run  `berks upload` on this cookbook, this file is not uploaded to the chef-server and I am getting failing chef-client runs. Other files in the same directory are uploaded successfully. When I run `knife cookbook upload`, this file is uploaded just fine.

**Comment by dmill** [comment]
I am using Berkshelf version 3.1.3

**Comment by sethvargo** [comment]
Hi @dmill. Do you have a chefignore or gitignore that is ignoring that file?

**Comment by dmill** [comment]
Hmm right you are, *.bak is in the chefignore. knife doesn't see this file based on the cookbook organization we're using. This is my mistake, thanks for the quick reply @sethvargo!
