### ISSUE TITLE
How to skip strict dependency check while running 'berks install'

### ISSUE THREAD

**Issue by adheepadhi** [berkshelf/berkshelf#1385]
Hi,
I am currently using the latest version of berkshelf
We have many cookbooks dependent on other cookbooks, so instead of manually changing  the dependency in metadata.rb for each cookbook, we are using a new concept called pin.rb, which will pin the latest version of dependent cookbooks to the metadata.
So in our script(pin.rb) we are using ‘berks install’ to generate the berksfile.lock and using the GRAPH in the berksfile.lock we pin the versions.
So while running berks install  it is strictly checking for the dependent cookbooks version mentioned in metadata and hence the berksfile.lock is not getting generated. But we want to skip this dependency checking.
So is it possible to skip this strict dependency check, and to generate the berksfile.lock

**Comment by reset** [comment]
@adheepadhi no, this is not possible and it is very outside of the the primary objective of Berkshelf which is to resolve dependency constraints.

If you'd like to pin cookbook versions to ensure that they don't change between environments I would suggest relying on the Berksfile.lock. You can distribute the lockfile with your package of cookbooks and apply that to an environment.

**Comment by adheepadhi** [comment]
ok..Thanks reset
