### ISSUE TITLE
multiple depends lines for same cookbook?

### ISSUE THREAD

**Issue by kramvan1** [berkshelf/berkshelf#1386]
Trying to understand what's going on here.  Berkshelf 3.1.5

AA cookbook metadata:
```
name AA
depends 'mysql', '< 6.0.0'
```
BB cookbook metadata:
```
name BB
depends AA
depends 'mysql', '>= 6.0.13'
depends 'mysql', '< 7.0.0'
```
BB cookbook Berksfile 
```
metadata
cookbook "AA"
```
I expected this to fail as these two have conflicting version constraints.  But it worked and grabbed mysql version 5.6.1 which obviously fails the BB metadata versioning.
Not sure I understand why this would happen, if the use of the multiple depends causing confusion for Berkshelf?

**Comment by reset** [comment]
@kramvan1 the proper syntax for representing multiple constraint operators is:

```
depends "mysql", ">= 6.0.13", "< 7.0.0"
```

**Comment by kramvan1** [comment]
@reset does having it on multiple lines break it?  or just cleaner to have on a single line?

**Comment by reset** [comment]
@kramvan1 having it on multiple lines changes the definition of the dependency. You need to put it on a single line.

**Comment by kramvan1** [comment]
@reset thanks for the clarification.
