### ISSUE TITLE
berks install --without solo

### ISSUE THREAD

**Issue by facastagnini** [berkshelf/berkshelf#1387]
First let me begin saying that I like Berkshelf a lot. Is a great tool that makes my life easier.

Context: chefdk-0.4.0-1

Now the problem: According to the documentation at berkshelf.com "Adding sources to a group is useful if you want to ignore a cookbook or a set of cookbooks at install or upload time."

And then it proceed to explain how to execute "$ berks install --without solo"

When I try to run that command I get:
```
~/D/g/c/c/c/roles git:master ❯❯❯ berks install --without solo                                                                                                                      
ERROR: "berks install" was called with arguments ["--without", "solo"]
Usage: "berks install"
```

Digging the help throws light over the issue:
```
~/D/g/c/c/c/roles git:master ❯❯❯ berks install --help                                                                                                                           
Usage:
  berks install
```

The documentation needs to be updated. The install parameter takes no options. 
Is this website on github so I can submit a pull request?

Thank you all for this great tool.

**Comment by reset** [comment]
@facastagnini thanks for the issue and the kind words. This is a documentation error that I'll fix in a few minutes. You want to pass the flag `--only` or `--except`. In the case of without, that would be except.
