### ISSUE TITLE
Two cookbooks depend on the same dependency with different versions

### ISSUE THREAD

**Issue by jmaziarz** [berkshelf/berkshelf#1389]
Using Berkshelf 3.2.3 with Ruby 2.1.3p242.

I'm writing a cookbook that depends on both community cookbooks [application_python](https://supermarket.chef.io/cookbooks/application_python) and [application_ruby](https://supermarket.chef.io/cookbooks/application_ruby). Each of those cookbooks depends on different version of the [application](https://supermarket.chef.io/cookbooks/application) cookbook: `~> 4.0` and `~> 3.0` respectively.

Berksfile:
```
source "https://supermarket.chef.io"

cookbook 'application_python', '~> 3.0.0'
cookbook 'application_ruby', '~> 3.0.2'
```

Output from `berks install` or `berks update`:
```
Unable to satisfy constraints on package application due to solution
constraint (application_ruby ~> 3.0.2). Solution constraints that may
result in a constraint on application: [(application_python = 3.0.0) ->
(application ~> 3.0)], [(application_ruby = 3.0.2) -> (application ~> 4.0)]
Demand that cannot be met: (application_ruby ~> 3.0.2)
```

How do I use two cookbooks that have the same dependency with different versions?

**Comment by reset** [comment]
@jmaziarz you can't, you would need to update the cookbooks to agree upon a common version constraint. This is the exact point a dependency resolver ;)

**Comment by sethvargo** [comment]
Hi there,

You can't do that - it's a classic dependency problem. The Chef Server will return the same result if you make a cookbook with those two dependencies. There does not exist a graph which satisfies the constraints you have provided.

**Comment by sethvargo** [comment]
Blah @reset beat my by a second!

**Comment by jmaziarz** [comment]
@reset @sethvargo In this case then, I would need to use an older version of application_ruby or fork application_python and work out upgrading the application dependency `to ~> 4.0`? If it were a much more complex case (multiple cookbooks with the same dependency) it seems it could get out of hand quickly.

**Comment by reset** [comment]
@jmaziarz yes, unfortunately that is an accurate description of building software with dependencies
