### ISSUE TITLE
Can't disable SSL verification

### ISSUE THREAD

**Issue by zachsmorgan** [berkshelf/berkshelf#1390]
at least two instances of rest_open_uri in lib/berkshelf/community_rest.rb are oblivious to the ssl.verify setting in config.json. 

I have a fix I'm testing with fellow users in my company (that also touches berkshelf-api-client - I piggy-backed on a similar thread there), is it bad form to blindly submit a pull request?

**Comment by reset** [comment]
@zachsmorgan no, if there's a bug and you have a solution you should absolutely create a pull request describing the bug you're fixing ;)

**Comment by zachsmorgan** [comment]
You got it, sir. Thanks.
