### ISSUE TITLE
How do I make berkshelf fetch latest HEAD version from git repo

### ISSUE THREAD

**Issue by praste** [berkshelf/berkshelf#1392]
I have a cron job that runs `berks vendor` command every few mins.
In my Berksfile I have a cookbook that I pull from my git repo. However looks like berkshelf would not download HEAD version of the dependency cookbook from git. 

How can I force it to download latest vesion?

**Comment by jsh2134** [comment]
...also in for answers

**Comment by sethvargo** [comment]
You need to run `berks update` because the lockfile locks the version.

**Comment by praste** [comment]
yup, that is what i ended up doing

**Comment by sethvargo** [comment]
@praste that's the expected behavior. If you imagine you're working in a team, you want everyone on your team to have the same downloaded version.

**Comment by praste** [comment]
@sethvargo

Looks like you missed cron job part from my original question

Also depending on when do a developer runs berks vendor command he will still get a different version of the cookbook

**Comment by sethvargo** [comment]
@praste right, this is the intended behavior. If you always want the latest head version, you need to run `berks update` before running `berks vendor`.
