### ISSUE TITLE
[gh-pages] Vagrant+Berkshelf plugin version is not supported

### ISSUE THREAD

**Issue by bschaeffer** [berkshelf/berkshelf#1396]
So, the website for `v3.0` documents installing the `vagrant-berkshelf` plugin like so:

```bash
$ vagrant plugin install vagrant-berkshelf --plugin-version 2.0.1
```

But issue https://github.com/berkshelf/vagrant-berkshelf/issues/227 [suggests](https://github.com/berkshelf/vagrant-berkshelf/issues/227#issuecomment-60628073) that `2.x` is no longer supported. Would make a pull request if I knew whether documentation is correct or not.

**Comment by sethvargo** [comment]
It should use the newer version

**Comment by reset** [comment]
@bschaeffer thanks for the heads up. I fixed the installation instructions on the main berkshelf page.
