### ISSUE TITLE
/opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `encode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError) 

### ISSUE THREAD

**Issue by dasomx77** [berkshelf/berkshelf#1399]
Hey guys, I know this issue has already shown up somewhere before and may be got fixed for those instances but I am still seeing this. Context: I have a couple of servers that are converging under Chef which kicks off a gem. The gem in turn runs clone some cookbooks from github and tries uploading them to our chef-server using this exact command: 
         install_command_output = `sudo berks install -c #{config} 2>&1  && sudo berks upload --skip-syntax-check -c #{config} 2>&1`
the command above seems to work most of the time but quite often it throws up with the error mentioned above. I have followed all solutions I have seen online so far and none of them worked (all environment variables settings to en_US.UTF-8). Notice that whenever I have to actually upload a cookbook manually I never run into this, but am following the same process I follow in my gem. Even weirder is that one cookbook will fail uploading and a couple of minutes later (after editing the cookbook and adding a single return character for test) it will pass.
My berkshelf version is 3.2.3.
here below is the log output of my gem:
2015-03-05 15:50:08 -0500: INFO: Uploading cookbook chef_repo_processor_pi using berkshelf... 
2015-03-05 15:50:08 -0500: INFO: writing the berks config file to /tmp/chef_repo_f02f0871dd61db84387fe26282de03754d4ee815/chef_repo/.berksfile 
2015-03-05 15:50:08 -0500: INFO: executing berks command from /tmp/chef_repo_f02f0871dd61db84387fe26282de03754d4ee815/chef_repo/cookbooks/chef_repo_processor_pi 
2015-03-05 15:50:16 -0500: INFO: Resolving cookbook dependencies... 
Fetching 'chef_repo_processor_pi' from source at . 
Fetching cookbook index from https://supermarket.getchef.com... 
/opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `encode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError) 
from /opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `initialize' 
from /opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `new' 
from /opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `parse' 
from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/chef/cookbook/metadata.rb:458:in `from_json' 
from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/chef/cookbook/metadata.rb:29:in `from_json' 
from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/chef/cookbook.rb:36:in `from_path' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cached_cookbook.rb:15:in `from_store_path' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:108:in `block in cookbooks' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:98:in `collect' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:98:in `cookbooks' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/resolver/graph.rb:8:in `populate_store' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/resolver.rb:73:in `resolve' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:174:in `install_from_universe' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:39:in `run' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:371:in `install' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:143:in `install' 
from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run' 
from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command' 
from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:in `dispatch' 
from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start' 
from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:in `execute!' 
from /opt/chefdk/embedded/apps/berkshelf/bin/berks:5:in `' 
from /usr/bin/berks:37:in `load' 
from /usr/bin/berks:37:in `' 
2015-03-05 15:50:16 -0500: ERROR: failed to upload using berkshelf 
Error uploading cookbook using berkshelf... 
2015-03-05 15:50:16 -0500: ERROR: Upload failed, please see the logs above!

**Comment by kareiva** [comment]
I am bumping into the same error. In the following example I am using Hosted Chef at https://api.opscode.com/

Steps how to reproduce:

    root@chef:~/chef-repo/cookbooks# berks cookbook mywiki
    ...
    root@chef:~/chef-repo/cookbooks# echo "cookbook 'mediawiki', '~> 0.1.0'" >> mywiki/Berksfile
    ...
    root@chef:~/chef-repo/cookbooks# cd mywiki && bundle install && berks install -d
    (same error as above)

It seems that the json gem simply expects US-ASCII and gets UTF-8 instead. Here are some of my versions:

    root@chef:~/chef-repo/cookbooks/mywiki# berks --version
    3.2.3
    root@chef:~/chef-repo/cookbooks/mywiki# chef-client --version
    Chef: 12.1.2
    root@chef:~/chef-repo/cookbooks/mywiki# ruby --version
    ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-linux]

Still looking into the issue.

**Comment by kareiva** [comment]
@dasomx77 - the solution for me was to check if the system has the corresponding UTF-8 locale and generate it if missing:

    # locale -a
    C
    C.UTF-8
    POSIX
    # export LC_CTYPE=en_US.UTF-8
    -bash: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
    # locale-gen en_US.UTF-8
    Generating locales...
      en_US.UTF-8... done
    Generation complete.

Now I can `berks install` dummy cookbook without errors.

    root@chef:~/test# berks install
    Resolving cookbook dependencies...
    Fetching 'test' from source at .
    Fetching cookbook index from https://supermarket.chef.io...
    Using test (0.1.0) from source at .

**Comment by hack2learn** [comment]
@kareiva your solution with setting the LC_CTYPE variable to UTF-8 did the trick. The locale was on my Mac OS X Yosemite already generated but not set properly.

**Comment by josacar** [comment]
This is a `error` / `feature` of `ridley` gem, bug opened [here](https://github.com/reset/ridley/issues/305)
