### ISSUE TITLE
Request: --release

### ISSUE THREAD

**Issue by rbaker5** [berkshelf/berkshelf#1402]
When berks upload is used with --freeze, it will upload frozen versions of all the cookbooks depended upon.  I can see why that was done, but in my workflow, I would prefer that the dependencies for my internal cookbooks are uploaded on their own and that the projects for those control when those cookbooks are locked.

My ideal behavior from berkshelf would be like this:
1. During development I'd use `--no-freeze` with `berks upload`.  This works fine as is.
2. When `berks upload --release` is run, that cookbook should become frozen.  All internal dependencies (not from supermarket) should be required to have already been frozen before this upload.  Supermarket dependencies could be uploaded as frozen at this point.  If an internal dependency was not already frozen, it should not become frozen, but instead the whole upload should fail.

The basic purpose of this is that lets say a team has a cookbook `app` that depends on cookbook `sometool`.  One developer is working on cookbook `app` and another on `sometool`, but finish the changes to app first.  The developer working on `app` runs berks upload --freeze.  Well, his cookbook is now frozen and all it's dependencies are frozen, but unfortunately it has also frozen an unfinished version of `sometool`.  I'd prefer that that developer had received an error that let him know he needs to work with the `sometool` developer to get that finalized before he finalizes his changes.

**Comment by thommay** [comment]
I think it's extremely unlikely that this will ever get implemented unless someone from the community wants to take it on.
