### ISSUE TITLE
Long delay at "Resolving cookbook dependencies with Berkshelf 3.2.3..." during a "kitchen converge"

### ISSUE THREAD

**Issue by bgeesaman** [berkshelf/berkshelf#1403]
Using a stock chef-dk on OSX:
```
Chef-dk 0.4.0
berkshelf 3.2.3
ktichen-vagrant 0.15.0
test-kitchen 1.3.1
```

After doing a `berks cookbook test` and editing the `.kitchen.yml` file to be:
```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: recipe[test::default]
    attributes:
```
and the Berksfile is untouched:
```
source 'https://supermarket.chef.io'

metadata
```

and the `metadata.rb` is untouched:
```
name             'test'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures test'
long_description 'Installs/Configures test'
version          '0.1.0'
```
I run `kitchen converge` like so:
```
$ kitchen converge
-----> Starting Kitchen (v1.3.1)
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing solo.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-ubuntu-1404>
       Starting Chef Client, version 12.1.1
       Compiling Cookbooks...
       Converging 0 resources
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 0/0 resources updated in 1.415571397 seconds
       Finished converging <default-ubuntu-1404> (1m31.81s).
-----> Kitchen is finished. (1m33.01s)
```
Notice that it took about *93 seconds*. 91 of them were at the "Resolving cookbook dependencies with Berkshelf 3.2.3..." line.

If I remove the `metadata` line and instead reference a cookbook outside the directory e.g. `cookbook 'other', path: '~/other/cookbook'`, or if I reference one from the community e.g. `cookbook 'apt'`, `kitchen converge` takes the normal 5+ seconds.

Any help is much appreciated.  Thanks.

**Comment by bgeesaman** [comment]
Ok, so I found the problem and have a workaround that works for the moment, but it's definitely a hack.

I created a test cookbook a la `berks cookbook test`.  I then edited the `.kitchen.yml` file to run one of my baseboxes and use chef to provision/run the default recipe `recipe[test::default]`.  My `metadata.rb` file simply has the source and `metadata` (meaning this is the only cookbook and it's right here, right?).  When I run `kitchen converge`, test-kitchen copies the ubuntu VM to the `.kitchen/` directory inside the cookbook, runs it, "vendors" the cookbook by copying the entire directory to `/var/folders/random/random/folder`, and then uploads the cookbooks and runs them on the vagrant VM.

The problem is that the vagrant VM is carted over to the /var/folders along with it, so the 90 seconds is actually just waiting for cp_r to finish.

My hack was to filter out the `.kitchen` directory from the files array in the `vendor` function of `lib/berkshelf/berksfile.rb`.  e.g. `files.reject! { |file| file =~ /.kitchen/}`, but I know that's pretty bad.  I'm a beginning rubyist who just dove it and narrowed down the issue as best as I could, but I'll leave the final solution to someone who understands this code base better.

**Comment by yves-vogl** [comment]
I can confirm this issue.

**Comment by yves-vogl** [comment]
@bgeesaman Did this solve your issue?

**Comment by bgeesaman** [comment]
@yves-vogl Yes!  Thank you!

**Comment by bgeesaman** [comment]
Suggest including .kitchen in the default chefignore file created during `berks cookbook cookbookname`?

**Comment by yves-vogl** [comment]
I think that'd be useful. As far as I remember I read a tweet from @jtimberman where the stumpled upon this issue, too.
