### ISSUE TITLE
Berkshelf ignores metadata.rb dependency versions for non-community cookbooks

### ISSUE THREAD

**Issue by scmgopal** [berkshelf/berkshelf#1405]
In my metadata I have:

depends "cookbook_wrapper", "~> 1.34.6"

My Berksfile has:

cookbook "cookbook_wrapper", chef_api: :config

When I do berks install I get following:

Installing cookbook_wrapper (1.36.6) from chef_api: 'https://chef.example.com:443'

There is no Berksfile.lock in the directory and I am using Berkshelf version 2.0.18
Please suggest how this can be fixed.

**Comment by thommay** [comment]
I'm closing this since berkshelf has been more or less rewritten entirely since 2.0.18; there's almost no way this is still a valid bug. Sorry this has not been touched sooner!
