### ISSUE TITLE
cookbook gets uploaded with half name

### ISSUE THREAD

**Issue by veilig2000** [berkshelf/berkshelf#1407]
I have a few cookbooks that are all namespaced.  ine-base, ine-foo, ine-bar, etc...  when I run `berks upload` the ine-base cookbook gets renamed to `base`  without the `ine-` prefix.  All other cookbooks appear to upload correctly w/ the namespace attached.

**Comment by sethvargo** [comment]
Can you share the metadata.rb for those cookbooks please?

**Comment by veilig2000** [comment]
aha - a clue.  the name is `base` in the metadata. my fault. I should have known.  

I must have started it as `base` and then moved it to be namespaced.
