### ISSUE TITLE
Leverage non-supermarket dependencies' Berksfiles

### ISSUE THREAD

**Issue by danehammer** [berkshelf/berkshelf#1408]
In my enterprise setting, I have several cookbooks, that depend on cookbooks, that are all on internal git repos. So I can use berkshelf to test and manage my individual cookbook and resolve its dependencies, but once the dependency tree gets deeper it becomes a bit repetitive to copy my transitive dependencies and their locations into my Berksfile.

I want to add dependency resolution abilities to berkshelf to enable leveraging a dependency's Berksfile, for the case that my dependency's Berksfile already specifies where to get my transitive dependencies. The path bit could be pretty weird, so I would start by just supporting git for this feature.

This is something I would like to contribute, just looking for some feedback first. Is this something you would like to see berkshelf support directly or should I create a gem that adds this functionality as an optional dependency for folks to use next to berkshelf?

**Comment by sethvargo** [comment]
Hi @danehammer 

This is not something myself or anyone on Berkshelf core will recommend. First, I would recommend giving [Jamie's blog post on the importance of compiled metadata](http://blog.vialstudios.com/the-importance-of-compiled-metadata/) a read.

Cookbooks, must like applications, should not be treated as "code", but rather artifacts. At the SCM level (git, svn, etc), you are working with code. But once that code is ready to be moved into production, it becomes an artifact just like a Java .jar file or a Go binary. It should be versioned, checksummed, and immutable. 

Berkshelf has support for SCM and path locations purely for convenience of local development and a few edge cases, but there existence should not encourage the use of scm/path locations as the primary mechansim for Berkshelf. You may also find my [Berkshelf Workflow](https://sethvargo.com/berkshelf-workflow/) blog post helpful in understanding this flow.

Finally, dependency resolution with multiple path or scm locations is non-deterministic and poorly performant. With Supermarket or the berkshelf api server, the state of the universe is known beforehand. This allows the dependency resolver to be accurate and precise, directly mapping to how Chef Client will resolve your cookbooks when run in production. When you add scm and path locations, not only have you added new nodes to the graph (with undefined edges), but you also have no guarantee that Chef Client will resolve the cookbooks in the same manner as Berkshelf. Keep in mind that Chef Client does not support scm or path locations - the Chef Server is an artifact store for cookbooks.

**Comment by reset** [comment]
@danehammer closing since @sethvargo provided the appropriate answer
