### ISSUE TITLE
Berkshelf master != GitHub master

### ISSUE THREAD

**Issue by scassiba** [berkshelf/berkshelf#1412]
Forgive me for this. It's confusing at best, maddening at worst.

How to repeat:
% git clone https://github.com/stackforge/openstack-chef-repo.git
% cd openstack-chef-repo;chef exec rake berks_vendor

This looks like it completes just fine, saying it pulls the master branch from GitHub, everyone's happy, right? One small caveat: cloning master directly from GitHub gets me the absolute latest commit ID that has been merged, but Berkshelf pointed at the same cookbook, with the same "master" branch, gets me a copy of master from days/weeks ago, not "right now" as I would expect.

Example:
openstack-compute master from GitHub: https://github.com/stackforge/cookbook-openstack-compute/commit/a29ad4be749db9361230abbb1d207a00fdb5f8f6
openstack-compute master from GitHub via Berkshelf: https://github.com/stackforge/cookbook-openstack-compute/commit/4981877b6a7df77201f0b9f021b65f9bd9651085

When I looked in ~/.berkshelf/cookbooks, I noticed the commit IDs in the directory paths did not match the latest commit ID for "master" of a given cookbook, but it's not consistent in its inconsistency. It seems to me that Berkshelf is not getting the latest commit ID when it fetches a given branch, but somehow gets an arbitrary commit ID that it is deemed to be latest for that branch, in this case "master".

Cleaning out ~/.berkshelf/cookbooks and my vendored cookbooks did not seem to change the fact that Berkshelf is somehow giving me the wrong snapshot of code.

**Comment by sethvargo** [comment]
I think you have a Berksfile.lock. You will need to run `berks update` to get the latest version.

**Comment by scassiba** [comment]
Last night when I stumbled across this, Berkshelf was consistently giving me the wrong commit IDs from a fresh clone of openstack-chef-repo, which does not include a Berksfile.lock by default. Blowing everything away and cloning fresh gives me latest master this morning, which is still inconsistent behavior, despite the results being what I want. Madness, I say.
