### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by aaadschutz** [berkshelf/berkshelf#1413]
The documentation is not very clear about what the purpose of berkshelf is, and in many cases what the berks command does, in my opinion. After having worked with this for a bit, my understanding is a bit better. Please consider updating the website and the CLI help accordingly:

A berkshelf is a locally cached repository of cookbooks. This is used to update cookbooks on a chef server, as it isn't possible to, for example, tell chef to directly use a particular version of a community cookbook or git repository. The berkshelf provides a staging area for cookbooks.

The Berksfile provides a function similar to a Gemfile. It defines the cookbooks to be installed to the berkshelf. When berks install is run for the first time, a Berksfile.lock is created which pins installed cookbooks to particular versions. If Berksfile.lock already exists berks install will use the existing file to determine cookbook versions to install instead of creating a new one. Berksfile.lock is updated to use newer available or newly configured cookbook versions by the use of berks update. 

berks install: Installs cookbooks specified in Berksfile.lock to the local berkshelf. It does _not_ interact with the configured chef server. It reads from Berksfile creates a Berksfile.lock file if it doesn't already exist.

berks update: updates an existing Berksfile.lock file. With no cookbook parameters the file will be updated with all cookbooks configured in the Berksfile. With one or more cookbooks specified as parameters the Berksfile.lock file will be updated with refreshed versions for the specified cookbooks and their dependencies.

berks update --only <group>: Ignore all version settings in Berksfile except for those in the specified group. Ignore any dependency settings in Berksfile for cookbooks in the group, if the dependency isn't also part of the group. Overwrite the Berksfile.lock file with the group settings and dependencies only. This could be considered an issue. Honestly it's not clear at all what this is supposed to do if it isn't buggy.

berks upload: upload all cookbooks defined in the Berksfile.lock and installed to the local berkshelf to the configured chef server.

Thanks!

Austin Schutz

**Comment by reset** [comment]
@aaadschutz have you read the [homepage](http://berkshelf.com/)? I think it covers most everything you're mentioning here with the exception of a few minor implementation details.

**Comment by mrjcleaver** [comment]
I like your description, @aaadschutz 

http://berkshelf.com states updated 2014. And doesn't mention update vs install.

I'd have thought a reference to chefdk would be helpful also.
