### ISSUE TITLE
ERROR -- : Actor crashed!  found while running berks install

### ISSUE THREAD

**Issue by devendraeck** [berkshelf/berkshelf#1418]
berks version
3.2.3

source "https://supermarket.chef.io"

metadata
cookbook "mysql"
cookbook 'nginx', '~> 2.7.6'

Fetching cookbook index from https://supermarket.chef.io...
Installing apt (2.7.0)
Installing bluepill (2.3.1)
Installing build-essential (2.2.3)
Using myapp (0.1.0) from source at .
Installing mysql (6.0.21)
Installing nginx (2.7.6)
Installing ohai (2.0.1)
Installing rbac (1.0.3)
E, [2015-11-15T18:38:05.222283 #25066] ERROR -- : Actor crashed!

**Comment by gionn** [comment]
You probably need to attach the full stack-trace and steps to reproduce otherwise who knows what actually happened.

**Comment by reset** [comment]
@devendraeck what was the exit code for the CLI and do you have the full stack trace? Thanks!

**Comment by reset** [comment]
The erroneous error output of Celluloid has been silenced in more recent versions of Berkshelf. This should no longer be in your console output.
