### ISSUE TITLE
Having to re-run 'berks api' everytime I upload a cookbook to my Berks API server

### ISSUE THREAD

**Issue by cfoutsgit** [berkshelf/berkshelf#1420]
I set up a Berks API server, and am able to berks install/upload cookbooks "to" it from my Git repo. Then I can do a berks install/upload "from" my berks api server to my Chef server.

Now I berks install/upload new cookbooks, or new versions of cookbooks, from my Git server "to" my Berks API server. Now when I try to berks install/upload from the Berks API server to my Chef Server, I get a server timeout when it's trying to access http://my-berks-api.domain.com:26200" If I restart berks-api, then it works.

**Comment by cfoutsgit** [comment]
BTW, I start my berks api via

$ berks api -c ~/.berkshelf/api-server/config.json &

Note the "&" at the end. I then exit the server.

**Comment by cfoutsgit** [comment]
So if I omit the & it works fine, but then I have to keep the terminal I started the job on. How can I run berks-api as a daemon?

**Comment by lamont-granquist** [comment]
berks api is pretty much deprecated now.  there's private supermarkets, and there's the universe endpoint in chef servers, and there's minimart.  no additional work will be going into berks api.  if there's features of berks api that have not been picked up by other cases then issues should be cut against those to implement those features.
