### ISSUE TITLE
Berkshelf upload fails 

### ISSUE THREAD

**Issue by mikeyhill** [berkshelf/berkshelf#1424]
I'm having the same issues as in #1067
Differences: Chef 12.0.x, Linux/Centos6.6

    [mikey@d3v tmp] :) knife cookbook site download ntp
    Downloading ntp from the cookbooks site at version 1.8.6 to /private/tmp/ntp-1.8.6.tar.gz 
    Cookbook saved: /private/tmp/ntp-1.8.6.tar.gz

    [mikey@d3v books] :) berks upload
    Skipping apt (2.7.0) (frozen)
    E, [2015-05-15T19:51:12.118566 #50020] ERROR -- : Ridley::Errors::HTTPInternalServerError:      {"error":["internal service error"]}
    E, [2015-05-15T19:51:12.119081 #50020] ERROR -- : /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/middleware/chef_response.rb:24:in `on_complete'

**Comment by reset** [comment]
@mikeyhill per the error output you're receiving a 500 internal server error from your Chef Server. You'll need to consult the server logs to be able to track down the issue.

**Comment by mikeyhill** [comment]
@reset thanks for the reply.  It was  a new server and I could never find the issue so I re-created and all was well.  Not the best for understanding the problem but got past it.

**Comment by reset** [comment]
@mikeyhill I'm glad you sorted it out. Unfortunately that is the most complete error report we can provide. When the server issues a 500 it contains absolutely no information about what happened.
