### ISSUE TITLE
read-only Berksfile.lock from perforce breaks workflow

### ISSUE THREAD

**Issue by epu** [berkshelf/berkshelf#1425]
After moving source code from git to perforce, discovered that kitchen-converge using berks 3.2.1 and a read-only Berksfile.lock fails. No action should be taken on the lock during test coverage, but write access was attempted.

I can work around this by making the file always writable when synced from perforce, or setting the workspace to allwrite.

**Comment by epu** [comment]
With the latest 10.0 chefdk on osx, vagrant 1.8, and chef_solo deploy method, Berkshelf/vagrant-berkshelf file_syncer.rb now also fails if .kitchen.yml or other files are present in source and are read-only. The vendoring process throws 'no access' and incorrectly asserts that I am not using the ChefDK.

**Comment by lamont-granquist** [comment]
short of a PR being submitted to fix this, setting the workspace to "allwrite" is the best solution here, there's no resources right now to fix this.
