### ISSUE TITLE
Private BitBucket repository

### ISSUE THREAD

**Issue by phpPhil** [berkshelf/berkshelf#1426]
If somebody could give me a hand to get this to work, that would be fantastic.

I've spent quite a bit of time trying to get Berkshelf to download a company cookbook from our private BitBucket (git) repository. Probably relevant... this is on a Windows 8.1 host.

I'm using these [multi ssh identity instructions](https://confluence.atlassian.com/pages/viewpage.action?pageId=271943168) as a guide.
* I have generated a public key with puttygen and added it as a deployment key to Bitbucket repo. 
* I saved the private key in `C:\Users\MyUser\.ssh\mykey.ppk`.
* I added `C:\Users\MyUser\.ssh\config` with the following contents:

  `Host mycompany`
  `HostName bitbucket.org`
  `IdentityFile ~/.ssh/mykey.ppk`

* I try to include the cookbook in berksfile like this:

    `cookbook 'mycookbook', git: "git@mycompany:myteam/mycookbook.git", protocol: :ssh`

When I run `$ berks install -d` I get:

	Fetching 'mycookbook' from git@mycompany:myteam/mycookbook.git (at master)
	Enter passphrase for key '/c/Users/MyUser/.ssh/mykey.ppk':
	Git error: command `git clone git@mycompany:myteam/mycookbook.git "C:/Users/MyUser/.berkshelf/.cache/git/6d5b957656d1bda26bf05aea558176c86db263f2" --bare --no
	-hardlinks` failed. If this error persists, try removing the cache directory at 'C:/Users/MyUser/.berkshelf/.cache/git/6d5b957656d1bda26bf05aea558176c86db263f2'.Output from the command:

	Cloning into bare repository 'C:/Users/MyUser/.berkshelf/.cache/git/6d5b957656d1bda26bf05aea558176c86db263f2'...
	Permission denied (publickey).
	fatal: Could not read from remote repository.

Any idea why this is not working?

Do I have to replace 'git' in front of the @ with my user name?

Also, what I find out is that the command line asks me for the passphrase of the ppk, which I just confirm with `enter' as I left it blank. But shouldn't it just read it without prompting for it?

Any help greatly appreciated, thanks.

**Comment by phpPhil** [comment]
I figured it out - the problem was that the created key is a putty private key, not an OpenSSH private key. If anybody is having this issue... convert it by using the puttygen user interface:
 
In puttygen click `Conversions -> Export OpenSSH`and save as mykey.pub. Then change the config to `IdentityFile ~/.ssh/mykey.pub`

**Comment by rjhornsby** [comment]
@phpPhil sorry for the comment on an old/closed issue, but yours is the closest I've come to finding a solution getting `berks install` to work in Windows with a private repo. When you say that you changed the config to include `IdentityFile ...` that looks like the ssh client config, or is that a line in your berkshelf config? I can't find jack in the berkshelf docs about specifying what ssh key to use.
