### ISSUE TITLE
Feature request: ability to specify multiple Berksfiles

### ISSUE THREAD

**Issue by eric-tucker** [berkshelf/berkshelf#1430]
I know this is probably an edge case, but I would like the ability to somehow specify two or more Berksfiles (two for now).

My use case is that we have a standard Berksfile that works with a standard set of wrapper cookbooks specifying dependencies that those wrapper cookbooks use.

Whenever we write an application cookbook that uses those base dependency cookbooks, we have to copy/paste all of the Berksfile dependencies from the common Berksfile into the application Berksfile and then build on the application Berksfile for dependencies specific to that application.

Current work-arounds
* copy/paste (which we do).
* monolithic Berksfile which works for all applications we manage (this is bad and causes many cookbooks to be downloaded which are never used).
* writing our own tools to automatically merge the two Berksfiles at some point in the build/deploy phase.

I honestly have no idea how this would be implemented, but I thought I would put it out there as a possibly useful feature.  Even if it was started as reading all [Berks]files in a specific directory that would be a fantastic start.

**Comment by eric-tucker** [comment]
Note I see this is a possible solution:
http://steve-jansen.github.io/blog/2014/05/06/including-another-berksfile-in-your-berksfile/

However, something about this feels brittle.

**Comment by sethvargo** [comment]
Hi @eric-tucker 

You might be interested in [this post](https://sethvargo.com/berksfile-magic/) I authored about Berksfile tricks. In short, you can do this:

```ruby
# Berksfile
instance_eval(File.read(File.expand_path("./other-Berksfile", __FILE__)))
```

**Comment by eric-tucker** [comment]
Yeah that looks similar to the link I posted.  I'm guessing a feature like this would be completely ridiculous to try to implement and it's probably easier to just specify the include in my apps Berksfile for the common Berksfile.

**Comment by eric-tucker** [comment]
The include trick using instance_eval works.  It does complain about duplicates if both Berksfiles have the same dependency specified, but that's just Berks being safe.  Thanks for the tip.
