### ISSUE TITLE
`berks package` omitting all files except metadata.json on OS X Yosemite

### ISSUE THREAD

**Issue by stevenhaddox** [berkshelf/berkshelf#1435]
Using the latest Chef-DK (version 0.6.0 I believe) on OS X Yosemite I am unable to get `berkshelf` to properly package a cookbook. Running `berks package` on any cookbook (the one we created at Excella's Intro to Chef yesterday - https://github.com/nathenharvey/excella-intro-to-chef, or a new `berks cookbook <name>`) creates a .tar.gz file that includes only a `metadata.json` file and doesn't include the recipes or any other needed files.

Using this exact same code on an Ubuntu 14.04 laptop with the exact same cookbook code generates a properly packaged cookbook that successfully uploads to vagrant through `kitchen converge`.

Oh, both the Mac and Ubuntu are using Ruby 2.1.5 installed via `rbenv`.

Please let me know if I can provide any more details or help in any other way. I'm hoping this is just isolated to my environment, but I really can't figure out what else could be different between the two setups.

**Comment by sethvargo** [comment]
Hi @stevenhaddox 

Can you please provide the exact command you ran as well as the output of the command in debug mode?

Thanks,
Seth

**Comment by stevenhaddox** [comment]
@sethvargo sure can!
```
chef -v
#=> 
# Chef Development Kit Version: 0.6.0
# chef-client version: 12.3.0
# berks version: 3.2.4
# kitchen version: 1.4.0
```

```
git clone https://github.com/nathenharvey/excella-intro-to-chef.git
cd excella-intro-to-chef/web
cat recipes/default.rb # Verify there's content in the file
berks package
tar -zvtf cookbooks-1434461887.tar.gz
#=> 
# drwx------  0 502    20          0 Jun 16 09:38 .
# drwxr-xr-x  0 502    20          0 Jun 16 09:38 cookbooks
# drwxr-xr-x  0 502    20          0 Jun 16 09:38 cookbooks/web
# -rw-r--r--  0 502    20        505 Jun 16 09:38 cookbooks/web/metadata.json
```

**Comment by robbkidd** [comment]
```
» chef -v
Chef Development Kit Version: 0.6.0
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0
```

```
» git clone https://github.com/nathenharvey/excella-intro-to-chef.git
» cd excella-intro-to-chef
```

**Comment by stevenhaddox** [comment]
Okay, @robbkidd was especially helpful in trying to replicate this and had no problems using the same setup I have. It looks like this is likely something specific to my environment. If nobody else can replicate this easily feel free to close it out. I'm in the process of trying a few things locally to see if somehow I can fix it with a cleaner install of rbenv, etc. as well. I'll follow-up if I can get it resolved as well. Sorry for any inconvenience.

**Comment by robbkidd** [comment]
I haven't been able to reproduce. :crying_cat_face:  On a burner Mac OS 10.10.3:

* [installed rbenv](https://github.com/sstephenson/rbenv#basic-github-checkout)
* [installed ruby-build](https://github.com/sstephenson/ruby-build#installing-as-an-rbenv-plugin-recommended)
* installed ruby-2.1.5 with ruby-build
* set 2.1.5 as default ruby in `~/.rbenv/version`
* installed chefdk 0.6.0 with homebrew cask

```
burner:code $ git clone https://github.com/nathenharvey/excella-intro-to-chef.git
...

burner:code $ cd excella-intro-to-chef/web

burner:web $ chef -v
Chef Development Kit Version: 0.6.0
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0

burner:web $ which {ruby,chef,berks}
~/.rbenv/shims/ruby
/usr/bin/chef
/usr/bin/berks

burner:web $ rbenv version
2.1.5 (set by ~/.rbenv/version)

burner:web $ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

burner:web $ pwd
~/code/excella-intro-to-chef/web

burner:web $ berks package
Cookbook(s) packaged to ~/code/excella-intro-to-chef/web/cookbooks-1434474260.tar.gz
burner:web robb$ tar tvzf cookbooks-1434474260.tar.gz | grep recipes
drwxr-xr-x  0 501    20          0 Jun 16 13:04 cookbooks/web/recipes
-rw-r--r--  0 501    20        320 Jun 16 13:04 cookbooks/web/recipes/default.rb
drwxr-xr-x  0 501    20          0 Jun 16 13:04 cookbooks/web/spec/unit/recipes
-rw-r--r--  0 501    20       1005 Jun 16 13:04 cookbooks/web/spec/unit/recipes/default_spec.rb

burner:web $ tar tvzf cookbooks-1434474260.tar.gz | wc -l
      26
```

**Comment by stevenhaddox** [comment]
Okay, I nuked rbenv and re-installed and all seems to be working as expected. That was random and I have no idea what caused the issue with it, but thanks for everyone's help in identifying that it was a local issue and not an actual bug.

**Comment by stevenhaddox** [comment]
Okay, just to follow-up in case anyone else hits this issue. I had problems the next day after saying everything was good for me again. Brand new rbenv, brand new chef-dk install, and things were still very unhappy. The solution that ended up working for me finally (after a restart) was the `rbenv-chefdk` plugin (https://github.com/docwhat/rbenv-chefdk). I have no idea why everything was being picky for just me on OS X Yosemite, but it was, and this seems to do the trick. I really hope nobody else encounters this and that it remains a one-off issue for me.
