### ISSUE TITLE
Link `berks outdated` results to changelog/diff (when source_url available via API)

### ISSUE THREAD

**Issue by patcon** [berkshelf/berkshelf#1436]
```
(master ✔) ᐅ berks outdated
The following cookbooks have newer versions:
  * database (2.3.1 => 4.0.6)
  * mysql (5.6.3 => 6.0.9)
  * mysql-chef_gem (0.0.5 => 1.0.0)
  * postgresql (3.4.16 => 3.4.20)
```

For example, mysql has an api on supermarket:
https://supermarket.chef.io/api/v1/cookbooks/mysql

source_url = https://github.com/opscode-cookbooks/mysql

Could link to either CHANGELOG (simple) or the diff of versions:
https://github.com/chef-cookbooks/mysql/compare/v5.6.3...v6.0.9

Anyhow, would make auditing updates simpler, but maybe this belongs in some sort of `berks-audit` plugin :)

**Comment by kamaradclimber** [comment]
You can take inspiration from https://github.com/kamaradclimber/knife-changelog

**Comment by thommay** [comment]
We are treating berkshelf as feature complete at this time; if you'd like to submit a PR then we'd gladly review it, but we're not undertaking any further work ourselves. 
I'm going to close this ticket, thanks for your interest.
