### ISSUE TITLE
berks upload fails on ssl verify on Windows

### ISSUE THREAD

**Issue by xdl** [berkshelf/berkshelf#1439]
I can't get `berks upload` uploading to the chef server; it keeps throwing the following error:

    Ridley::Errors::ClientError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Whereas `knife cookbook upload..` works fine. I can bypass this with the `--no-ssl-verify` but this is not desirable. 

I am using chefdk v0.5.1, with berks v3.2.3. I've tried doing `set SSL_CERT_FILE=C:\opscode\chef\embedded\ssl\certs\cacert.pem` as described in this [issue](https://github.com/chef/chef-dk/issues/106), but that doesn't seem to work either. Does anyone have any other ideas?

**Comment by dougireton** [comment]
SSL verify is broken on Windows with ChefDK < 0.6.2. I reported this bug to Chef and they reproduced it. They released ChefDK 0.6.2 to fix this issue.

This is not an issue with Berkshelf. This issue should be closed.

**Comment by xdl** [comment]
@dougireton I've updated to the newest version of ChefDK 0.6.2:

    >chef -v
    Chef Development Kit Version: 0.6.2
    chef-client version: 12.3.0
    berks version: 3.2.4
    kitchen version: 1.4.0

and tried `berks upload` again, but it's giving me the same error as above :(

    E, [2015-06-30T12:12:01.440417 #4976] ERROR -- : Ridley::Errors::ClientError: SS
    L_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate
    verify failed
    E, [2015-06-30T12:12:01.456418 #4976] ERROR -- : C:/opscode/chefdk/embedded/lib/
    ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/responses.rb:29:in `value'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/calls.rb:92:in `value'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/proxies/sync_proxy.rb:33:in `method_missing'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/proxies/cell_proxy.rb:17:in `_send_'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/pool_manager.rb:41:in `_send_'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/pool_manager.rb:140:in `method_missing'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/calls.rb:26:in `public_send'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/calls.rb:26:in `dispatch'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/calls.rb:63:in `dispatch'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/cell.rb:60:in `block in invoke'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/cell.rb:71:in `block in task'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/actor.rb:357:in `block in task'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/tasks.rb:57:in `block in initialize'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/tasks/task_fiber.rb:15:in `block in create'
    (celluloid):0:in `remote procedure call'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/calls.rb:92:in `value'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/proxies/sync_proxy.rb:33:in `method_missing'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/reso
    urce.rb:132:in `raw_request'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/reso
    urce.rb:123:in `request'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/reso
    urces/cookbook_resource.rb:96:in `find'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/reso
    urces/cookbook_resource.rb:190:in `upload'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/calls.rb:26:in `public_send'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/calls.rb:26:in `dispatch'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/calls.rb:63:in `dispatch'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/cell.rb:60:in `block in invoke'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/cell.rb:71:in `block in task'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/actor.rb:357:in `block in task'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/tasks.rb:57:in `block in initialize'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/tasks/task_thread.rb:21:in `block in create'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/thread_handle.rb:13:in `block in initialize'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/actor_system.rb:32:in `block in get_thread'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/internal_pool.rb:130:in `call'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/internal_pool.rb:130:in `block in create'
    (celluloid):0:in `remote procedure call'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/calls.rb:92:in `value'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/cellulo
    id/proxies/sync_proxy.rb:33:in `method_missing'
    C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:55:in `block
     (2 levels) in upload'
    C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:51:in `each'
    
    C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:51:in `block
     in upload'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/clie
    nt.rb:38:in `open'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley.rb:5
    1:in `open'
    C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf.rb:144:in `ridley_connec
    tion'
    C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:50:in `uploa
    d'
    C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:37:in `run'
    C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:545:in `upl
    oad'
    C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:208:in `upload'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command
    .rb:27:in `run'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocat
    ion.rb:126:in `invoke_command'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:
    in `dispatch'
    C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:in `dispatch'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb
    :440:in `start'
    C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:in `execute!'
    C:/opscode/chefdk/embedded/apps/berkshelf/bin/berks:5:in `<top (required)>'
    C:/opscode/chefdk/bin/berks:43:in `load'
    C:/opscode/chefdk/bin/berks:43:in `<main>'

**Comment by rschiefer** [comment]
I'm having this issue too.  Also using ChefDK 0.6.2.

**Comment by anowak** [comment]
@rschiefer I've encountered similar problem, but it turned out to be a misconfigured proxy. Run `berks upload` with `-d` flag and refer to [this solution](http://stackoverflow.com/questions/9071976/chef-api-server-behind-apache-reverse-http-proxy-returns-http-instead-of-https-l) in case you see SSL-related errors.

**Comment by kkeane** [comment]
I also had this issue with ChefDK 0.8.0. In my case, the problem was that I had both the chef-client and ChefDK installed - which you aren't supposed to do.

I had added the CA certificate to C:\opscode\\**chef**\embedded\ssl\certs\cacert.pem, which is used by knife (part of chef-client), but it also needs to be added to C:\opscode\\**chefdk**\embedded\ssl\certs\cacert.pem, which is used by berks.

**Comment by xdl** [comment]
Thanks kkeane, it turns out that that was the issue; I had a self-signed certificate that wasn't in C:\opscode\chefdk\embedded\ssl\certs\cacert.pem. There's a zendesk article about it: https://getchef.zendesk.com/hc/en-us/articles/204831396-How-to-make-ChefDK-tools-trust-untrusted-SSL-certificates
