### ISSUE TITLE
Add tool to auto-generate .berkshelf/config.json or provide examples in the repo and on berkshelf.com

### ISSUE THREAD

**Issue by Joseph-R** [berkshelf/berkshelf#1441]
Hey guys,

I'm trying to figure out how to create a config.json.  Finding it pretty frustrating how often it is mentioned, with zero information or guidance on a) how to set it up or b) what format/flags it needs.

**Backstory:**
I'm running into an SSL error with Berkshelf on a `berks upload`, but have confirmed a valid SSL with the chef server in my `knife.rb` by running `knife ssl check`:

```
[15:08:48] (39) jreid@JoesMacBookPro:~/repo/chef-repo/cookbooks/O2O-chefserver(add_chef_server_JR)
$ berks upload
E, [2015-07-01T15:10:53.684387 #3023] ERROR -- : Ridley::Errors::ClientError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

$ knife ssl check
Connecting to host chef.production.korrelate.net:443
Successfully verified certificates from `chef.production.korrelate.net'
```

The [interwebs](http://stackoverflow.com/questions/27833419/i-have-installed-chef-dk-and-started-using-berkshelf-but-berks-upload-failed) tell me that I should either set the SSL file in my `.berkshelf/config.json` if it is, for some reason, not being picked up out of my knife.rb, or that I should flag it to ignore SSL altogether.  

Great.  I would like to at least give that a shot.  So what all needs to go in my `.berkshelf/config.json`?  Where can I find some documentation re: how to set that up, what format, any file permissions needed, etc?

Regards,
Joe Reid

**Comment by toddiuszho** [comment]
Documented [here on the main site](http://berkshelf.com/#configuring-berkshelf). Example for you would be at `~/.berkshelf/config.json`:
```
{
  "ssl": {
    "verify": false
  }
}
```

**Comment by kernelsmith** [comment]
I have to +1 this wrt auto-generating or shipping a config.json.example, but this may be because I don't fully grok how the json + buff-config + varia_model combination works yet

**Comment by kernelsmith** [comment]
oh wait, `berks configure`

**Comment by kernelsmith** [comment]
geez I suck at this, configure was deprecated.  I think just shipping a config.json.example would suffice and be easiest no?

**Comment by predatorian3** [comment]
I also have these issues with `berks upload`, either this SSL error, or its not looking in my chef_repo for my client.pem.

**Comment by cloneluke** [comment]
oldie but a goodie:

[berkshelf 2.0 ](http://berkshelf.com/v2.0/)

![image](https://user-images.githubusercontent.com/6568361/32067525-2bf60672-ba49-11e7-8a87-71ac871dd184.png)

**Comment by lamont-granquist** [comment]
berkshelf 7.0 is intended to interoperate a lot better with knife.rb and ssl/proxy issues, and the config.json at this point is almost deprecated.  PRs to improve the docs would be accepted, but i'd rather like to know why people still need t to use config.json and if we can fix those issues (which can be cut as bugs).  we're unlikely to allocate any time to working this issue.
