### ISSUE TITLE
Resolving cookbook dependencies fills up hard drive

### ISSUE THREAD

**Issue by aem** [berkshelf/berkshelf#1447]
Today I noticed that when running a `kitchen converge`, when the converge process gets to "Resolving cookbook dependencies with Berkshelf 3.2.4" Berkshelf will nearly fill up my hard drive (200GB of free space, down to about 15GB). This seems very unusual, especially considering my Berksfile is pretty simple:

```
source "https://supermarket.chef.io"

metadata

cookbook 'cygwin', '~> 0.5.0'
cookbook 'git', '~> 4.2.2'
cookbook 'java', '~> 1.31.0'
```

**Comment by sethvargo** [comment]
@aem what is in `~/.berkshelf`?

**Comment by aem** [comment]
@sethvargo 
```
$ ls -l ~/.berkshelf/cookbooks
drwxr-xr-x   8 amarkon  staff  272 Jun 17 14:06 7-zip-1.0.2
drwxr-xr-x  12 amarkon  staff  408 Jun 17 13:12 apt-2.6.1
drwxr-xr-x  28 amarkon  staff  952 Jul 22 14:33 apt-2.7.0
drwxr-xr-x  22 amarkon  staff  748 Jul 17 14:55 build-essential-2.2.3
drwxr-xr-x  11 amarkon  staff  374 Jun 17 14:06 chef_handler-1.1.9
drwxr-xr-x  11 amarkon  staff  374 Jul 17 14:44 chef_handler-1.2.0
drwxr-xr-x  10 amarkon  staff  340 Jul 17 14:44 cygwin-0.5.0
drwxr-xr-x  11 amarkon  staff  374 Jul 17 14:55 dmg-2.2.2
drwxr-xr-x  11 amarkon  staff  374 Jul 17 14:55 git-4.2.2
drwxr-xr-x  24 amarkon  staff  816 Jul 22 13:33 java-1.31.0
drwxr-xr-x  22 amarkon  staff  748 Jul 22 14:33 jenkins-2.3.1
drwxr-xr-x   7 amarkon  staff  238 Jul 17 15:08 nodejs-windows-0.10.13
drwxr-xr-x  27 amarkon  staff  918 Jul 22 14:33 packagecloud-0.0.19
drwxr-xr-x  27 amarkon  staff  918 Jul 22 14:33 runit-1.7.2
drwxr-xr-x  14 amarkon  staff  476 Jun 17 13:12 targetcli-8dfa91e2d2139b14efb83edf246082106fb7e68a
drwxr-xr-x  11 amarkon  staff  374 Jun 17 14:06 windows-1.37.0
drwxr-xr-x  19 amarkon  staff  646 Jul 17 14:44 windows_firewall-2.0.0
drwxr-xr-x  11 amarkon  staff  374 Jul 17 14:55 yum-3.6.3
drwxr-xr-x   7 amarkon  staff  238 Jul 17 14:55 yum-epel-0.6.2
```

**Comment by sethvargo** [comment]
@aem then it's definitely not Berkshelf that is filling up your harddrive. Those cookbooks are pretty minimal. Can you show the size of ~/.berkshelf? (`du -h ~/.berkshelf`)

**Comment by aem** [comment]
@sethvargo 2.3M for ~/.berkshelf. It looks like it's something that's being created in a temp directory somewhere, because as soon as the converge moves past that step the hard drive space is restored.

**Comment by sethvargo** [comment]
@aem what happens if you run Berkshelf manually? How many VMs are you testing? This doesn't really seem like a Berkshelf issue to me

**Comment by aem** [comment]
@sethvargo running Berkshelf manually works just fine. I'm testing two VMs. I agree, it seemed odd that Berkshelf would be the culprit, but I wasn't sure what else could be causing that. It's 100% reproducible using my configuration

**Comment by sethvargo** [comment]
What is in `/tmp` during the Kitchen run?

**Comment by aem** [comment]
Nothing that looks relevant
```
$ ls -l /tmp/
total 0
drwx------  3 root     wheel  102 Jul 31 10:25 KSOutOfProcessFetcher.0.KvQVA6MpDzYxvkzUKAnRQWNnZYg=
drwx------  3 amarkon  wheel  102 Jul 27 10:29 com.apple.launchd.8LvmB15rRc
drwx------  3 amarkon  wheel  102 Jul 27 10:29 com.apple.launchd.ZJpj692gnZ
```

**Comment by sethvargo** [comment]
I'm really confused. How long are these runs taking? Filling up 185GB is not a fast process. How are you monitoring this?

**Comment by aem** [comment]
I'm also confused. It'll sit on the "Resolving dependencies" step for at least a couple of minutes sometimes 5-10 minutes. I originally noticed it because my computer effectively became unresponsive and then I received an OS notification that my disk was almost out of space. Since then I've been keeping a Finder window open and watching the free space count down.

**Comment by sethvargo** [comment]
What happens if you reduce those constraints to:

```
cookbook 'cygwin', '~> 0.5'
cookbook 'git', '~> 4.2'
cookbook 'java', '~> 1.31'
```

**Comment by aem** [comment]
Reducing my Berksfile to those three lines makes the "Resolving dependencies" step happen in a second or two but the converge obviously fails because it can't find my cookbook.

**Comment by aem** [comment]
Just took this screenshot from Activity Monitor:
<img width="798" alt="screen shot 2015-07-31 at 2 28 02 pm" src="https://cloud.githubusercontent.com/assets/1909883/9014453/6f8364d6-3790-11e5-9436-004cc800fb12.png">

**Comment by sethvargo** [comment]
@aem keep the other lines in the file, just reduce the constraints.

Is this happening when you run without Test Kitchen?

**Comment by aem** [comment]
The only constraints I have in the file are cygwin, git, and java. And no, only when I use Test Kitchen

**Comment by sethvargo** [comment]
So this isn't reproducible with just Berkshelf itself? What is in your .kitchen.yml?

**Comment by aem** [comment]
Correct. .kitchen.yml:
```
---
driver:
  name: vagrant
  vm_hostname: false

provisioner:
  name: chef_solo

transport:
  name: winrm
  username: vagrant
  password: vagrant

platforms:
  - name: windows7
    driver_config:
      box: windows7
      communicator: winrm

suites:
  - name: default
    run_list:
      - recipe[win_installer]
    attributes:
```

**Comment by sethvargo** [comment]
I think this is a Test Kitchen issue or just a misunderstanding of how the VM is being managed. Windows images are inherently large, but not that large. I'm not really sure how to help you diagnose this issue, but since it's not reproducible with Berkshelf on its own, I don't think this is a berkshelf bug. I would recommend opening an issue on TK or maybe posting on the Chef mailing list. Thanks!
