### ISSUE TITLE
:git assumes ~/.ssh/id_rsa is the only valid key that the user could use

### ISSUE THREAD

**Issue by ghost** [berkshelf/berkshelf#1451]
Output:

```
$ berks install
Resolving cookbook dependencies...
Fetching 'xxxxxx-xxxxxxx' from git@bitbucket.org:xxxxxxx/xxxxx-xxxx-xxxx.git (at master)
Git error: command `git fetch --force --tags git@bitbucket.org:xxxxx/xxxxx-xxxx-xxxxx.git "refs/heads/*:refs/heads/*"` failed. If this error persists, try removing the cache directory at '/home/j/.berkshelf/.cache/git/43f3a5fcb3347676430bb97737e0856664fc6703'.Output from the command:

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I rename my key to `~/.ssh/id_rsa`; works without issue.

This is probably a feature request; but there maybe should be a `:path_key` option to specify the path to the key.

**Comment by sethvargo** [comment]
Hi @nopejpg 

We are just shelling out to git, so this is a git issue. You may need to add your key to Git somehow.

**Comment by nopejpg** [comment]
@sethvargo I see; I noticed I may be able to create a `~/.ssh/config` and then specify in the `:git` path the alias to get around this. You can close this if necessary; but there are ways to work around it I've come to find.
