### ISSUE TITLE
Berkshelf does not respect cookbook locations on dependencies of dependencies

### ISSUE THREAD

**Issue by MrTrustor** [berkshelf/berkshelf#1452]
Hello,

I am new to berkshelf and running into an issue.
I have a sshd cookbook that depends on an apt cookbook which itself depends on a resolver cookbook.
All are stored on our local gitlab. Here is the Berksfile for sshd:

     source 'https://supermarket.chef.io'
     metadata
     cookbook "apt", git: "git@my.gitlab:cookbooks/apt.git"

And the Berksfile for apt:

     source "https://supermarket.chef.io"
     metadata
     cookbook "resolver", git: "git@my.gitlab:cookbooks/resolver.git"

The problem is that berkshelf is getting the resolver cookbook from supermarket.chef.io when I am installing sshd whereas it correctly gets it from my gitlab if I install apt:

     ~/cookbooks/apt$ berks list
     Cookbooks installed by your Berksfile:
       * apt (0.1.0) from source at .
       * resolver (0.1.0) from git@my.gitlab:cookbooks/resolver.git (at master)

    ~/cookbooks/sshd$ berks list
    Cookbooks installed by your Berksfile:
      * apt (0.1.0) from git@my.gitlab:cookbooks/apt.git (at master)
      * resolver (1.3.0)
      * sshd (0.1.0) from source at .

     ~$ head -n 7 ~/.berkshelf/cookbooks/resolver-1.3.0/metadata.rb
     name              'resolver'
     maintainer        'Chef Software, Inc.'
     maintainer_email  'cookbooks@chef.io'
     license           'Apache 2.0'
     description       'Configures /etc/resolv.conf via attributes'
     long_description  IO.read(File.join(File.dirname(__FILE__), 'README.md'))
     version           '1.3.0'

Thank you for your help.

**Comment by sethvargo** [comment]
Berksfile's are not recursively evaluated. You can read more here: https://github.com/berkshelf/berkshelf/pull/304 Thanks! :smile:
