### ISSUE TITLE
berks cookbook reports conflicting chefignore file

### ISSUE THREAD

**Issue by sladiri** [berkshelf/berkshelf#1453]
Hi,

I when executing `berks cookbook test`, berks consistently reports a conflict in the file `chefignore`.
Here is part of the log output, where it happens.
If I choose yes, the overwritten chefignore contains just the line `.kitchen`, otherwise it is much longer but `.kitchen` is missing, does that line have to be in `chefignore` as well?

```
create  hey/Gemfile
create  .kitchen.yml
conflict  chefignore
Overwrite /home/sladjan/hey/chefignore? (enter "h" for help) [Ynaqdh] n
skip  chefignore
append  Thorfile
```

I use Fedora 22 with kernel `4.1.5-200.fc22.x86_64` and just installed ChefDK, berks is `3.2.4`.
On a very similar install on another laptop, but without the newest updates, kernel is `4.1.3-200.fc22.x86_64`, this the conflict is not reported, and `.kitchen` is missing from generated `chefignore` files (using `berks cookbook ...`).

Maybe this is related to asynochronous file manipulations like mentioned here?
https://github.com/berkshelf/berkshelf/issues/421

I googled for the conflict message, and it only came up on this tutorial, it is of a recent date:
https://viblo.asia/ducthien1490/posts/jdWrvw82Rw38

Regards,
Sladi

**Comment by ehaselwanter** [comment]
same here

```
berks cookbook fresh_cookbook
      create  fresh_cookbook/files/default
      create  fresh_cookbook/templates/default
      create  fresh_cookbook/attributes
      create  fresh_cookbook/libraries
      create  fresh_cookbook/providers
      create  fresh_cookbook/recipes
      create  fresh_cookbook/resources
      create  fresh_cookbook/recipes/default.rb
      create  fresh_cookbook/metadata.rb
      create  fresh_cookbook/LICENSE
      create  fresh_cookbook/README.md
      create  fresh_cookbook/CHANGELOG.md
      create  fresh_cookbook/Berksfile
      create  fresh_cookbook/Thorfile
      create  fresh_cookbook/chefignore
      create  fresh_cookbook/.gitignore
      create  fresh_cookbook/Gemfile
      create  .kitchen.yml
    conflict  chefignore
Overwrite /Users/ehaselwanter/tmp/fresh_cookbook/chefignore? (enter "h" for help) [Ynaqdh] Y
       force  chefignore
      append  Thorfile
      create  test/integration/default
      append  .gitignore
      append  .gitignore
      append  Gemfile
      append  Gemfile
You must run `bundle install' to fetch any new gems.
      create  fresh_cookbook/Vagrantfile
ehaselwanter at cora in ~/tmp using
```
berks -v
3.2.4
```

**Comment by CMeza99** [comment]
Still exists in 3.3.0

**Comment by djeremiah** [comment]
I have also seen this issue.
chefdk 0.10.0-1.el7.x86_64
berks 4.0.1
RHEL 7.1

**Comment by asnodgrass** [comment]
It appears that berks is overwriting the first iteration of chefignore with just a single line to omit `.kitchen`:

    create  .kitchen.yml
    conflict  chefignore
    Overwrite somepath/chefignore? (enter "h" for help) [Ynaqdh] d
    - # Put files/directories that should be ignored in this file when uploading
    + .kitchen
    - # or sharing to the community site.
    - # Lines that start with '# ' are comments.
    -
    - # OS generated files #
    - ######################
    - .DS_Store
    - Icon?
    - nohup.out
    - ehthumbs.db
    - Thumbs.db
    -
    - # SASS #
    - ########
    - .sass-cache
    -
    - # EDITORS #
    - ###########
    - \#*
    - .#*
    - *~
    - *.sw[a-z]
    - *.bak
    - REVISION
    - TAGS*
    - tmtags
    - *_flymake.*
    - *_flymake
    - *.tmproj
    - .project
    - .settings
    - mkmf.log
    -
    - ## COMPILED ##
    - ##############
    - a.out
    - *.o
    - *.pyc
    - *.so
    - *.com
    - *.class
    - *.dll
    - *.exe
    - */rdoc/
    -
    - # Testing #
    - ###########
    - .watchr
    - .rspec
    - spec/*
    - spec/fixtures/*
    - test/*
    - features/*
    - Guardfile
    - Procfile
    -
    - # SCM #
    - #######
    - .git
    - */.git
    - .gitignore
    - .gitmodules
    - .gitconfig
    - .gitattributes
    - .svn
    - */.bzr/*
    - */.hg/*
    - */.svn/*
    -
    - # Berkshelf #
    - #############
    - cookbooks/*
    - tmp
    -
    - # Cookbooks #
    - #############
    - CONTRIBUTING
    - CHANGELOG*
    -
    - # Strainer #
    - ############
    - Colanderfile
    - Strainerfile
    - .colander
    - .strainer
    -
    - # Vagrant #
    - ###########
    - .vagrant
    - Vagrantfile
    -
    - # Travis #
    - ##########
    - .travis.yml

**Comment by spifrancisv** [comment]
Any update on this?

**Comment by bitmonk** [comment]
@asnodgrass it sounds like perhaps this should be a bug against TestKitchen, that it needs a way to merge chefignores? Since they write out different contents, it seems like they should combine, rather than override.

**Comment by poliva83** [comment]
The berks chefignore skeleton file needs to be updated to reflect the skeleton in chefdk: https://github.com/chef/chef-dk/blob/master/lib/chef-dk/skeletons/code_generator/files/default/chefignore

Would be nice if both berks and chefdk grabbed the skeleton file from same location.

**Comment by lamont-granquist** [comment]
users should use the chef-dk generators directly.

the berks generators may become deprecated and removed.

**Comment by lamont-granquist** [comment]
`berks cookbook` has been removed.
