### ISSUE TITLE
Full Faraday/X509 implementation (patch included)

### ISSUE THREAD

**Issue by milligana** [berkshelf/berkshelf#1458]
It seems that apart from 'verify', no other .berkshelf/config.json ssl parameters get to the Faraday connection - making peer verify (ie CA certificates) impossible.

The reason for this is quite probably because rather disappointingly, Faraday expects OpenSSL::X509 objects instead of simply strings to certificate paths.

A possible working implementation (happy to discuss) which visualises all of Faraday's SSL parameters and coerces types accordingly (it presently assumes RSA private key - alas I'm not uber familiar with the OpenSSL/Ruby implementation) is appended below.

One can now assure server side peer/ca verification (and more) with the following .berkshelf/config.json:
{
  "ssl":{"verify": false, 
         "client_cert": "/etc/pki/tls/certs/lbn-alan.pem", 
         "client_key":"/etc/pki/tls/private/lbn-alan.key"}
}

--- lib/berkshelf/config.rb.orig    2015-09-08 21:53:41.157661938 +1000
+++ lib/berkshelf/config.rb 2015-09-08 23:04:45.595426170 +1000
@@ -1,4 +1,5 @@
 require 'buff/config/json'
+require 'openssl'

 module Berkshelf
   class Config < Buff::Config::JSON
@@ -45,6 +46,7 @@
         else
           new
         end
- ```
     coerce_ssl
  ```
  
     end
  
     # Reload the currently instantiated Berkshelf configuration
  @@ -54,6 +56,17 @@
       @instance = nil
       self.instance
     end
-   
-      # force proper X509 types from any configuration strings
-      #
-      # @return [Config]
-      def coerce_ssl
-        ssl = @instance.ssl
-        ssl[:ca_cert] = OpenSSL::X509::Certificate.new(File.read(ssl[:ca_cert])) if ssl[:ca_cert] && ssl[:ca_cert].is_a?(String)
-        ssl[:client_cert] = OpenSSL::X509::Certificate.new(File.read(ssl[:client_cert])) if ssl[:client_cert] && ssl[:client_cert].is_a?(String)
-        ssl[:client_key] = OpenSSL::PKey::RSA.new(File.read(ssl[:client_key])) if ssl[:client_key] && ssl[:client_key].is_a?(String)
-        @instance
- ```
   end
  ```
  
   end
  
   # @param [String] path
  @@ -131,6 +144,26 @@
     type: Buff::Boolean,
     default: true,
     required: true
-    attribute 'ssl.cert_store',
-      type: Buff::Boolean,
-      default: false,
-      required: false
-    attribute 'ssl.ca_file',
-      type: String,
-      default: nil,
-      required: false
-    attribute 'ssl.ca_path',
-      type: String,
-      default: nil,
-      required: false
-    attribute 'ssl.client_cert',
-      type: String,
-      default: nil,
-      required: false
-    attribute 'ssl.client_key',
-      type: String,
-      default: nil,
-      required: false
   attribute 'github',
     type: Array,
     default: [],
  --- lib/berkshelf/downloader.rb.orig    2015-09-08 23:14:12.620106842 +1000
  +++ lib/berkshelf/downloader.rb 2015-09-08 23:16:12.903736152 +1000
  @@ -66,9 +66,7 @@
         server_url: remote_cookbook.location_path,
         client_name: Berkshelf::Config.instance.chef.node_name,
         client_key: Berkshelf::Config.instance.chef.client_key,
-          ssl: {
-            verify: Berkshelf::Config.instance.ssl.verify
-          }
-          ssl: Berkshelf::Config.instance.ssl
       }
       # @todo  Something scary going on here - getting an instance of Kitchen::Logger from test-kitchen
       # https://github.com/opscode/test-kitchen/blob/master/lib/kitchen.rb#L99
  --- lib/berkshelf/community_rest.rb.orig    2015-09-08 23:17:07.087470101 +1000
  +++ lib/berkshelf/community_rest.rb 2015-09-08 23:17:39.701911882 +1000
  @@ -69,7 +69,7 @@
   # @option options [Float] :retry_interval (0.5)
   #   how often we should pause between retries
   def initialize(uri = V1_API, options = {})
-      options         = options.reverse_merge(retries: 5, retry_interval: 0.5, ssl: { verify: Berkshelf::Config.instance.ssl.verify })
-      options         = options.reverse_merge(retries: 5, retry_interval: 0.5, ssl: Berkshelf::Config.instance.ssl)
     @api_uri        = uri
     @retries        = options.delete(:retries)
     @retry_interval = options.delete(:retry_interval)
  --- lib/berkshelf/source.rb.orig    2015-09-08 23:11:40.502046316 +1000
  +++ lib/berkshelf/source.rb 2015-09-08 23:20:29.847216597 +1000
  @@ -10,7 +10,7 @@
   # @param [String, Berkshelf::SourceURI] uri
   def initialize(uri)
     @uri        = SourceURI.parse(uri)
-      @api_client = APIClient.new(uri, ssl: {verify: Berkshelf::Config.instance.ssl.verify})
-      @api_client = APIClient.new(uri, ssl: Berkshelf::Config.instance.ssl)
     @universe   = nil
   end

**Comment by reset** [comment]
@milligana thanks for the heads up here. If you could submit a PR with the patch in tow I'd be happy to review and merge in. We've not had a great track record on this front in the past and it'd be awesome to nail down any SSL cert issues!

**Comment by thommay** [comment]
We merged a similar PR recently, thanks!
