### ISSUE TITLE
Can no longer install 3.3.0 on Chef 11/Ruby 1.9

### ISSUE THREAD

**Issue by dpetzel** [berkshelf/berkshelf#1464]
We noticed that as of yesterday we are getting the following error:
```
Gem::InstallError: berkshelf-api-client requires Ruby version >= 2.0.0
```
We are still using Ruby 1.9 (via Chef 11) in our CI pipelines. Here is the snippet from our Gemfile:
```
gem 'berkshelf', '~> 3.1'
```
I'm not sure if this project or berkshelf-api-client is to blame, but here is how I'm seeing things.

Berkshelf version 3.3 (which we are resolving via our pessimistic constraint) is declaring a dependency of `'berkshelf-api-client', '~> 1.2'`. This is resolving now to berkshelf-api-client version 1.4.0, which was recently released (and dropped  Ruby 1.9) support.

Personally I think berkshelf-api-client should have been a *major* version bump since it dropped Ruby 1.9 support. 

This could also be fixed by updating the constraint in this project to `~> 1.3.0`.

Personally I think fixing api-client is the right approach, but since that has already shipped, perhaps a safer approach is cutting a 3.3.1 with a more specific pin?

Thoughts?

**Comment by reset** [comment]
@dpetzel oops, that's my mistake! Yes, I should have released 2.0.0 of Berkshelf-API-Client instead of 1.4.0. I'm going to do a combination of both of your suggestions to fix this.

* Release Berkshelf 3.3.1 to lock to 1.3.0.
* Release Berkshelf-API-Client 2.0.0
* Yank Berkshelf-API-Client 1.4.0

I'll get this done in the next 10 minutes or so

**Comment by dpetzel** [comment]
thanks @reset If you think its safer than yanking, maybe berkshelf api client 1.4.1 with an updated pin to avoid breaking anyone that might have managed to get 1.4.0 into their lock files already?

**Comment by reset** [comment]
@dpetzel That's a good though, but If they've got 1.4.0 in their lock already when they got to resolve their dependency it will complain that the gem no longer exists. I don't think it'll be necessary!

**Comment by reset** [comment]
@dpetzel ok you should be good to go. Thanks again for the heads up!

**Comment by dpetzel** [comment]
@reset thanks, that error has cleared for us, and we're back to pulling `Using berkshelf-api-client 1.3.0`

**Comment by reset** [comment]
@dpetzel great to hear

**Comment by dpetzel** [comment]
With that out of the way we have the same issue on https://github.com/reset/varia_model. That one is a sub 1.0 so technically you're in the right to be able to get away with a minor jump, while dropping 2.0. Is there somewhere in the dependency tree that varia_model could be pinned to 0.4.1?

**Comment by reset** [comment]
@dpetzel I'm in the middle of bumping required rubies on a lot of deps and catching things as I go so you might see a few of these today. I just fixed this by pushing Ridley `4.3.1` which will satisfy your constraint graph just fine!

Minor note - I'm not _technically_ correct, that's exactly how the spec works ;)

**Comment by dpetzel** [comment]
@reset thanks for the super responsive fixes

**Comment by justinkinney** [comment]
Seeing this as well - ```Gem::InstallError: varia_model requires Ruby version >= 2.0.0.```

**Comment by reset** [comment]
@justinkinney installing Berkshelf via gem was deprecated two years ago and is not a supported method of installation. You'll want to grab a version of ChefDK and work with that.

If you're not ready to make the jump you can blow away your lockfile. That version of Berkshelf will resolve Ridley 4.3.1 which has a constraint on Varia Model `~> 0.4.0` that supports Ruby 1.9.
