### ISSUE TITLE
Berkshelf hangs at supermarket.chef.io after adding local cookbook path to berksfile

### ISSUE THREAD

**Issue by polinakud** [berkshelf/berkshelf#1469]
Berks install works perfectly until I specify local path to a cookbook. I am not able to stop the process, it will hang indefinitely.

My versions:

```
pkud$ chef --version
Chef Development Kit Version: 0.9.0
chef-client version: 11.18.12
berks version: 4.0.1
kitchen version: 1.4.2
```

Berksfile:

```
# -*- mode: ruby -*-
source "https://supermarket.chef.io"

# GitHub Cookbooks
cookbook 'android-sdk',     :github => 'gildegoma/chef-android-sdk'
cookbook 'cassandra-dse',   :github => 'michaelklishin/cassandra-chef-cookbook'
cookbook 'users',           :github => 'opscode-cookbooks/users', :ref => 'refs/tags/v1.8.0'
cookbook 'kafka',           :github => 'hw-cookbooks/kafka'

cookbook 'auth', path:  '/Users/pkud/Projects/services/chef/auth'

# API Cookbooks
cookbook 'apt'
cookbook 'certificate'
cookbook 'consul'
cookbook 'elasticsearch', '~>0.3.14'
cookbook 'grafana', '~> 2.1.3'
cookbook 'graphite'
cookbook 'java'
cookbook 'memcached'
cookbook 'mongodb'
cookbook 'redisio'
cookbook 'route53'
cookbook 'varnish', '= 1.0.2'
cookbook 'apache_zookeeper'
cookbook 'rbenv'
```

Berks install output:

```
Fetching 'auth' from source at ../auth
Fetching cookbook index from https://supermarket.chef.io...
```

Berks install debug output:

```
D, [2015-10-29T17:55:44.982518 #21892] DEBUG -- :   Adding explicit dependency on auth (0.1.0) '/Users/pkud/Projects/services/chef/auth'
D, [2015-10-29T17:55:44.982677 #21892] DEBUG -- :   Starting resolution...
```

and it never resolves...

**Comment by northrup** [comment]
Did you ever resolve this or find a resolution? I am having the same issue.

**Comment by mrjcleaver** [comment]
+1

**Comment by goatherd** [comment]
For me it was likely a complex dependency resolution that stalled/ froze the process. After fixing a version or two it works well again - with the same sources and cookbooks.

Using a different source alone (like git instead of supermarket) did not fix the issue itself.
DNS-issues with ruby did not occur either - did some intensive testing on those.

So my guess is that the resolution complexity gets out of hand sometimes and is hard to predict for end-users as there are many influences like release-tags, metadata-depends, requirements and so on. It should be possible to create cases with runtimes up to several days or more.

**Comment by polinakud** [comment]
I fixed it a while ago, its possible that the dependancies of our own
cookbooks collided. Also deleting .bershelf folder could help with a fresh
start.

On Thu, Apr 14, 2016 at 6:55 AM, Maik Penz <notifications@github.com> wrote:

> For me it was likely a complex dependency resolution that stalled/ froze
> the process. After fixing a version or two it works well again - with the
> same sources and cookbooks.
>
> Using a different source alone (like git instead of supermarket) did not
> fix the issue itself.
> DNS-issues with ruby did not occur either - did some intensive testing on
> those.
>
> So my guess is that the resolution complexity gets out of hand sometimes
> and is hard to predict for end-users as there are many influences like
> release-tags, metadata-depends, requirements and so on. It should be
> possible to create cases with runtimes up to several days or more.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/berkshelf/berkshelf/issues/1469#issuecomment-209954630>
>



-- 


Polina Kud

**Comment by northrup** [comment]
For me when this happened I was migrating from a self maintained Chef repo to Berkshelf.  I had included all the items that I had in my Chef repo in my Berksfile, causing it to lose its mind. I then took the approach of starting from scratch and only placing things in my Berksfile that I needed (i.e. nginx, and not 'bluepill') and let Berkshelf resolve the dependencies and install them. I found that solved the issue for me.

**Comment by phillipviana** [comment]
+1

I, [2016-08-01T17:30:14.304121 #29856]  INFO -- : Reducing lockfile
D, [2016-08-01T17:30:14.304238 #29856] DEBUG -- : Current lockfile:
D, [2016-08-01T17:30:14.304278 #29856] DEBUG -- : 
D, [2016-08-01T17:30:14.304327 #29856] DEBUG -- :   DEPENDENCIES
D, [2016-08-01T17:30:14.304359 #29856] DEBUG -- :   
D, [2016-08-01T17:30:14.304387 #29856] DEBUG -- :   GRAPH
D, [2016-08-01T17:30:14.304413 #29856] DEBUG -- : 
D, [2016-08-01T17:30:14.304439 #29856] DEBUG -- : Unlocking dependencies no longer in the Berksfile
D, [2016-08-01T17:30:14.304477 #29856] DEBUG -- : Removing transitive dependencies
D, [2016-08-01T17:30:14.304525 #29856] DEBUG -- :   Checking cmselkstack (>= 0.0.0)
D, [2016-08-01T17:30:14.304560 #29856] DEBUG -- :     Skipping (not graphed)
D, [2016-08-01T17:30:14.304591 #29856] DEBUG -- :   Checking elkstack (= 0.1.1)
D, [2016-08-01T17:30:14.304617 #29856] DEBUG -- :     Skipping (not graphed)
D, [2016-08-01T17:30:14.304646 #29856] DEBUG -- : New lockfile:
D, [2016-08-01T17:30:14.304696 #29856] DEBUG -- : 
D, [2016-08-01T17:30:14.304730 #29856] DEBUG -- :   DEPENDENCIES
D, [2016-08-01T17:30:14.304758 #29856] DEBUG -- :   
D, [2016-08-01T17:30:14.304783 #29856] DEBUG -- :   GRAPH
D, [2016-08-01T17:30:14.304808 #29856] DEBUG -- : 
Resolving cookbook dependencies...
I, [2016-08-01T17:30:14.304885 #29856]  INFO -- : Checking if lockfile is trusted
D, [2016-08-01T17:30:14.304928 #29856] DEBUG -- : Checking cmselkstack (>= 0.0.0)
D, [2016-08-01T17:30:14.304959 #29856] DEBUG -- :   Not in lockfile - cannot be trusted!
I, [2016-08-01T17:30:14.304987 #29856]  INFO -- : Installing from universe
Fetching 'cmselkstack' from source at .
D, [2016-08-01T17:30:14.309093 #29856] DEBUG -- :   Creating a resolver
Fetching cookbook index from https://supermarket.chef.io...
D, [2016-08-01T17:30:15.628732 #29856] DEBUG -- : ==> parsing Chef response body as JSON
D, [2016-08-01T17:30:16.162812 #29856] DEBUG -- :   Adding explicit dependency on cmselkstack (0.1.0) '/home/phil/cookbook-dev/cmselkstack'
D, [2016-08-01T17:30:16.162986 #29856] DEBUG -- :   Starting resolution...

**Comment by lamont-granquist** [comment]
Can't replicate on berks 5.1.0

Had to comment out the "auth" cookbook since that was local and not supplied.

If anyone has the same problem with berkshelf hanging then please push up a repo to github that can be cloned and replicate the problem, and open a new bug report.

Without a replication case we can't guess what the issue might be with the depsolver that is causing hanging.
