### ISSUE TITLE
Berkshelf doesn't resolve guthub dependence

### ISSUE THREAD

**Issue by mlanin** [berkshelf/berkshelf#1471]
I have a global `Berksfile` with list of our custom cookbooks. Each in our local github:

```ruby
source "https://supermarket.chef.io"

cookbook "app", git: "git@gitlab.example.com:app-cookbooks/app.git", branch: "4.2"
cookbook "app_infra", git: "git@gitlab.example.com:app-cookbooks/app_infra.git", branch: "4.2"
cookbook "app_log", git: "git@gitlab.example.com:app-cookbooks/app_log.git", branch: "4.2"
```

`app_log` has dependency for `kibana` cookbook that is located on github. That's what we have in the `metadata.rb`:

```ruby
depends "runit"
depends "redisio"
depends "logstash"
depends "elasticsearch"
depends "nginx"
depends "kibana", "1.3.3"
```

And that is the `Berksfile`

```ruby
source "https://supermarket.getchef.com"

metadata

cookbook "kibana", git: "https://github.com/lusis/chef-kibana.git", tag: "v1.3.3"
```

Problem is that if I'll try to `berks install` for the `app_log` cookbook, everything will resolve as a charm. But if I'll try to install all my cookbooks from the global `Berksfile`, i'll have the following error:

```bash
$ berks install
Resolving cookbook dependencies...
Fetching 'app' from gitlab.example.com:app-cookbooks/app.git (at 4.2)
Fetching 'app_infra' from gitlab.example.com:app-cookbooks/app_infra.git (at 4.2)
Fetching 'app_log' from gitlab.example.com:app-cookbooks/app_log.git (at 4.2)
Fetching cookbook index from https://supermarket.chef.io...
Unable to satisfy constraints on package kibana due to solution constraint (app_log = 4.2.0). Solution constraints that may result in a constraint on kibana: [(app_log = 4.2.0) -> (kibana = 1.3.3)]
Demand that cannot be met: (app_log = 4.2.0)
Artifacts for which there are conflicting dependencies: kibana = 0.1.6 -> [(build-essential >= 0.0.0)]Unable to find a solution for demands: app (4.2.0), app_infra (4.2.0), app_log (4.2.0)
```

As you can see, Berkshelf doesn't look into the `Berksfile` of the `app_log` to resolve `kibana` cookbook from the github and still tries to find it in the supermarket.

**Comment by reset** [comment]
@mlanin this is the intended behaviour, nested Berksfiles are not supported. There's quite a bit of [discussion in the past](https://github.com/berkshelf/berkshelf/pull/304) on this that you can read up on if you'd like.

I would highly recommend not using Github/Git sources for anything other than temporary development purposes. You should consider releasing your cookbooks to a Chef server and using that, and a Berkshelf-API server as a source

**Comment by mlanin** [comment]
@reset thank you for the answer. But what can I do if I have 3 local cookbooks that point on each other?
```
app1 -> app2 -> app3
```

Each cookbook has it's own Berksfile that knows what cookbooks are local:
```
cookbook "app1", path: "../app1"
```
etc.

If I'll run `berks install` on **app3**, it will be ok. If I'll run `berks install` on **app2**, it will find **app3** and finish perfectly. But if I'll do the same on **app1**, berks will fail with an error that it can't find **app3**.

How to manage this scenarios?

Thanks in advance.
