### ISSUE TITLE
Berkshelf may compare different version of cookbook then lock's during `trusted?`

### ISSUE THREAD

**Issue by bbaugher** [berkshelf/berkshelf#1473]
I was able to get this to occur using Berkshelf 3.3.0 and 4.0.1. Its pretty simple to replicate.

Create Berksfile (effectively my Berksfile at the time)

    source 'https://supermarket.getchef.com'
    cookbook 'java'

Then `berks install` (this is to ensure java 1.36.0 or higher is installed into shelf)

Update Berksfile.lock to (this is effectively what I had in my Berksfile.lock previously)

    DEPENDENCIES
      java
    
    GRAPH
      java (1.35.0)

Then,

    berks install
    berks upload

Fails with,

    The lockfile is out of sync! Run `berks install` to sync the lockfile

Running with debug shows,

    I, [2015-11-05T12:46:56.017352 #10043]  INFO -- : Checking if lockfile is trusted
    D, [2015-11-05T12:46:56.017434 #10043] DEBUG -- : Checking java (>= 0.0.0)
    D, [2015-11-05T12:46:56.697593 #10043] DEBUG -- :   Detected there is a cached cookbook
    D, [2015-11-05T12:46:56.697672 #10043] DEBUG -- :   Cached cookbook has different dependencies - cannot be trusted!

The java cookbook recently released 1.36.0 which includes a new dependency on apt. If you delete 1.36.0 of java from shelf everything works,

    berks shelf uninstall java -f -v 1.36.0
    berks upload

Similarly if you add a version constraint to the Berksfile `= 1.35.0` this also fixes the issue even if 1.36.0 is in shelf.

Bonus points if you can make figuring this out easier (i.e. what dependencies are different, what cookbook is causing the problem, tell me without using debug?)

**Comment by bbaugher** [comment]
During `trusted?` it asks for the the [dependency's cached cookbook](https://github.com/berkshelf/berkshelf/blob/master/lib/berkshelf/lockfile.rb#L116) which doesn't seem to have its `@locked_version` set so it uses the Berskfile's version constraint `>= 0.0.0` ([here](https://github.com/berkshelf/berkshelf/blob/master/lib/berkshelf/dependency.rb#L136-L140)) and uses  `1.36.0` from cache instead. It seems like you could set the lock_version on each dependency during [Lockfile.from_berksfile(..)](https://github.com/berkshelf/berkshelf/blob/3112f37ecce14e74221f69b28941ea485665df99/lib/berkshelf/lockfile.rb#L18-L24) but I don't totally understand the consequences of that

**Comment by llibicpep** [comment]
Same on 3.2.1.
Seems like https://github.com/berkshelf/berkshelf/blob/master/lib/berkshelf/lockfile.rb#L116 completely ignore what is pinned in lockfile. So once newer dependency version available in cache and has different dependencies, it will fail. Even when for that particular cookbook that version of dependency never used (even in transitive dependencies). No idea how to fix. To me it sounds like a chicken-egg problem, we trying to get ```cached_cookbook``` at the moment we did not trust to lockfile yet and because of that we don't know what the lock would be. Or for whatever other reason ```locked_version``` is not set in ```dependency```.
