### ISSUE TITLE
berkshelf 4.0.1 doesn't want to sync from git repos take 2 ( my first take was closed swiftly )

### ISSUE THREAD

**Issue by parabolic** [berkshelf/berkshelf#1478]
Hi I am having a problem since I issued gem update and berkshelf was updated to 4.0.1. It seems that I cannot update the cookbooks that are from git. I tried removing the .cache folder , removing all the cookbooks from the cookbooks folder and still it dies when trying to fetch from git. Works fine with other cookbooks. Here's an example berks file. I've also tried the https version for github repositories and I get the same error.
```ruby
ENV['BERKSHELF_PATH'] = '.'

source "https://api.berkshelf.com"

cookbook 'elasticsearch', git: 'git@github.com:elastic/cookbook-elasticsearch'
cookbook 'java'
cookbook 'rabbitmq', git: 'git@github.com:jjasghar/rabbitmq.git'
cookbook 'nginx'
cookbook 'python'
```
when I issue
```sh
berks install -d 
```
I get the following

https://gist.github.com/parabolic/42173aa54312486757cb
ruby version 
**ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]**
berkshelf 
**berkshelf (4.0.1)
berkshelf-api-client (2.0.0)**

*Response after my issue was closed* link https://github.com/berkshelf/berkshelf/issues/1476

@reset I wish it was that easy and simple though...
I just tried although I tried before but forgot to mention it, and I am sorry about that. I still get the same output. I even tried commenting it out and it gets stuck on rabbitmq

https://gist.github.com/parabolic/456f1b3c2e91f607d8b0
Furthermore when I go to the .cache folder specified above and I try to do a git pull or git status I get:
```sh
git pull 
fatal: This operation must be run in a work tree
```
Thanks!

**Comment by reset** [comment]
@parabolic this is because you're abusing the BERKSHELF_PATH environtment variable within the Berksfile to point to `.`. You need use an absolute path or relative path which is not the single character `.`.

**Comment by parabolic** [comment]
@reset Thanks for the fast reply, it seems that that's the problem, investigating.

**Comment by parabolic** [comment]
Found it here's the fix,
```ruby
ENV['BERKSHELF_PATH'] = File.expand_path('../', __FILE__)

source "https://api.berkshelf.com"

cookbook 'elasticsearch', git: 'git@github.com:elastic/cookbook-elasticsearch.git'
cookbook 'java'
cookbook 'rabbitmq', git: 'git@github.com:jjasghar/rabbitmq.git'
cookbook 'nginx'
cookbook 'python'

```

Thanks @reset !
