### ISSUE TITLE
Feature request: change vendor location

### ISSUE THREAD

**Issue by georeith** [berkshelf/berkshelf#1479]
For testing berkshelf stuff locally with chef-zero it would be useful to change the berkshelf vendor location.

I already make use of `cookbooks` and `site-cookbooks` and would like to make a new folder like `vendor-cookbooks` that I can gitignore the contents of and vendor to that, otherwise it just fills up my cookbooks folder and modifies my non-vendored path included cookbooks.

**Comment by kuboj** [comment]
You mean something like `berks vendor vendor-cookbooks`? Because this has been already implemented.
```
$ berks vendor --help
Usage:
  berks vendor [PATH]
...
```

**Comment by reset** [comment]
@georeith - @kuboj is right, all you've got to do is specify the path as an argument to the command
