### ISSUE TITLE
`berks package` seems to include "." in the resulting tarball

### ISSUE THREAD

**Issue by adammeghji** [berkshelf/berkshelf#1483]
It appears that running `berks package` includes the current working directory `.` in the contents of the tarball:

```
ubuntu@kungfu:/tmp/t$ tar -tvf cookbooks.tgz
drwx------ 1000/1000         0 2015-11-24 17:37 .
drwxrwxr-x 1000/1000         0 2015-11-24 17:37 cookbooks
```

This is bad because it will mutate the permissions of the current working directory (or extraction target dir).

I'm using berks package with chef-solo's --recipe-url parameter via AWS user-data.sh.  Thus, the extraction happens at `/`.  Turns out, the permissions of `/.` mutate after extracting this tarball.  `/.` permissions are being modified from `drwxr-xr-x` to `drwx------`, and everything goes to hell after that.

Originally (incorrectly) reported here: https://github.com/chef/chef/issues/4186

**Comment by scaryguy** [comment]
+1

**Comment by Tensibai** [comment]
Unless I did miss something obvious, replacing `.` by `./*` [here](https://github.com/berkshelf/berkshelf/blob/master/lib/berkshelf/packager.rb#L45) should fix this issue by not including `.` in the archive.
