### ISSUE TITLE
berks init wants metadata.rb when store downloads only provide metadata.json

### ISSUE THREAD

**Issue by DarwinJS** [berkshelf/berkshelf#1488]
I downloaded a cookbook (chocolatey in this case), expanded it and ran berks init in the cookbook folder and I get:

"The resources at <blah>/chocolatey/metdata.rb' does not appear to be a valid cookbook.  Does it have a metadata.rb?"

It has a metadata.json instead.

I worked around it by using git to pull the source of the cookbook - but would like to be able to use store packages.

I am using berks 4.0.1.

Looks like this also a challenge for knife some months back.

**Comment by lamont-granquist** [comment]
another dup of #1352?

**Comment by dharee** [comment]
I'm facing the same problem. We have our own chef-server and the cookbooks uploaded using berks upload converts metadata.rb to metadata.json. When another machine tried to download the cookbook and tried to use berks install/init it gives an error message "The resources at coobook_name/metdata.rb' does not appear to be a valid cookbook. Does it have a metadata.rb?"

Is there any solution or workaround for this? I'm using berks 4.3.5

**Comment by lamont-granquist** [comment]
berks init is going to be deprecated in favor of chef-dk generators
