### ISSUE TITLE
`berks vendor` and `berks package` do not honor directories in chefignore

### ISSUE THREAD

**Issue by tknerr** [berkshelf/berkshelf#1492]
In my `chefignore` file I have this:

```
test/*
```

However, both `berks vendor` and `berks package` seem to ignore this entry and still vendor/package the `test/` directory.

If I omit the `/*` suffix, it works, but it's not as precise anymore as it would also ignore files named `test`, not only the directory `test/`

This was with berks v3.2.4 in ChefDK 0.7.0 on a Windows 7 box

Steps to reproduce:
- `chef generate cookbook foo` (generates a cookbook with a chefignore file that contains "test/*"
- `cd foo`
- `berks vendor` 
- `ls -la berks-cookbooks/foo/test` (<- it's still there)

**Comment by tknerr** [comment]
Just verified that this happens with berks 4.0.1 as well

**Comment by ifeltsweet** [comment]
please fix this

**Comment by acoulton** [comment]
This is still an issue in 6.2.2 - and was part of the reason why my chefspec suites were incredibly slow even when I thought I'd ignored a bunch of build-time directories.

**Comment by vitalis** [comment]
👍

**Comment by lamont-granquist** [comment]
dup of #1317
