### ISSUE TITLE
Dependency issue due to renamed cookbook

### ISSUE THREAD

**Issue by dobrinov** [berkshelf/berkshelf#1493]
I have the following situation: `custom_cookbook_a` _depends on_ `custom_cookbook_b` _depends on_ `collectd` [v1.2.1](https://github.com/hectcastro/chef-collectd/tree/v1.2.1).
When berks install is ran in `custom_cookbook_b` everything is ok, but when it is ran in `custom_cookbook_a` a dependency error is thrown. 

```
Unable to satisfy constraints on package collectd due to solution constraint (custom_cookbook_a = x.y.z). Solution constraints that may result in a constraint on collectd: [(custom_cookbook_a = x.y.z) -> (custom_cookbook_b = x.y.z) -> (collectd = 1.2.1)], [(custom_cookbook_b = x.y.z) -> (collectd = 1.2.1)]
Demand that cannot be met: (custom_cookbook_a = x.y.z)
Artifacts for which there are conflicting dependencies: collectd = 2.2.1 -> [(poise ~> 2.2), (poise-service ~> 1.0)]Unable to find a solution for demands: custom_cookbook_a (x.y.z), custom_cookbook_b (x.y.z)
```

It turned out that what is causing the problem is the `collectd` cookbook which was renamed to `collectd-ng`, starting from [v2.0.0](https://github.com/hectcastro/chef-collectd/blob/v2.0.0/metadata.rb#L1).

When I run `berks install` in `custom_cookbook_b` everything is OK.
When I do the same thing in `custom_cookbook_a` it contacts `api.berkshelf.com` and fails with the error message above, because there is already [another cookbook](https://supermarket.chef.io/cookbooks/collectd) with the original name there and it uses it when I tries to calculate the dependencies for `custom_cookbook_a`.

**Comment by lamont-granquist** [comment]
this feels like not a bug and i definitely can't sort out what berkshelf should do.  the conflict seems accurate.
