### ISSUE TITLE
Dependecy resolution debugging Help - Possible bug

### ISSUE THREAD

**Issue by arieb** [berkshelf/berkshelf#1494]
Hey,

We are having issues with resolving dependencies of a given cookbook using Berkshelf (version 4.0.1).
When we run both
```berks install -d```
and 
```DEBUG_RESOLVER=1 berks install -d```
it just hangs after the saying the it started the dependency resolution.

How would you recommend debugging this issue?
i've read something about trying to switch to the old "ruby" resolver, and yet i can't seem to find the proper way to do this..

Is there a way to print the dependency graph that its currently being built?

thanks

**Comment by arieb** [comment]
Im trying to use the new :ruby solver, maybe it will help, however im running into trouble running the latest berkshelf and solve versions. (i come from C and Python so im sorry if im doing newbie ruby mistakes)
I've added the Following Gemfile to my cookbook
```ruby
source 'https://rubygems.org'

gem 'berkshelf', git: "https://git@github.com/berkshelf/berkshelf'
gem 'solver', git: 'https://git@github.com/berkshelf/solve'
```

i used the following commands to run the newly downloaded version
`chef gem install bundler`
`chef exec bundle install`
`chef exec bundle exec berks install -d`

however it crashes immediately with the following error:
```ruby
/home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/lib/berkshelf/config.rb:80:in `<class:Config>': undefined method `chef_server_url' for nil:NilClass (NoMethodError)
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/lib/berkshelf/config.rb:4:in `<module:Berkshelf>'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/lib/berkshelf/config.rb:3:in `<top (required)>'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/lib/berkshelf/cookbook_generator.rb:3:in `require_relative'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/lib/berkshelf/cookbook_generator.rb:3:in `<class:CookbookGenerator>'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/lib/berkshelf/cookbook_generator.rb:2:in `<module:Berkshelf>'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/lib/berkshelf/cookbook_generator.rb:1:in `<top (required)>'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/lib/berkshelf.rb:200:in `require_relative'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/lib/berkshelf.rb:200:in `<top (required)>'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/lib/berkshelf/cli.rb:1:in `require'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/lib/berkshelf/cli.rb:1:in `<top (required)>'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/bin/berks:3:in `require'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bundler/gems/berkshelf-ea9d87d44292/bin/berks:3:in `<top (required)>'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bin/berks:23:in `load'
        from /home/arie/.chefdk/gem/ruby/2.1.0/bin/berks:23:in `<main>'

```
however i have config.rb and knife.rb (this happens if i use BERKSHELF_CHEF_CONFIG to make sure it reads the file) and they have the chef_server_url attributes inside them.

**Comment by arieb** [comment]
I've confirmed the aformentioned bug occurs in ridley 4.4.0, but does not occur in version 4.3.2, so i guess it might be a bug there

**Comment by erran-r7** [comment]
@arieb :+1: I'm seeing this in some of our builds too. Worked around it by pinning ridley to `v4.3.2` in the meantime.

**Comment by erran-r7** [comment]
> @arieb  I'm seeing this in some of our builds too. Worked around it by pinning ridley to v4.3.2 in the meantime.

Sorry, to clarify I am seeing the `berks package` failure relating to [the removal of the chef_server_url](https://github.com/berkshelf/ridley/compare/v4.3.2...v4.4.0#diff-ae02933bcda1a5eb6175fb378e606f16L47) method.

**Comment by arieb** [comment]
This seems to be a big issue, my colleague's vagrant-berkshelf plugin stopped working due to the same error. i had to manually delete the ridley-4.4.0 gem from the .vagrant.d directory.

ill open a relevant ticket for this in ridley (in case no one already did)

**Comment by erran-r7** [comment]
@arieb see also https://github.com/berkshelf/berkshelf/issues/1495.

**Comment by arieb** [comment]
Yes i was just about to post this.
ill close this issue then

**Comment by erran-r7** [comment]
@arieb actually the ridley issue link is https://github.com/berkshelf/ridley/issues/330. (just to get it on here) Cool :+1: I'll be tracking that too.
