### ISSUE TITLE
Ridley::Chef::Config doesn't have chef_server_url method (and more)

### ISSUE THREAD

**Issue by b-dean** [berkshelf/berkshelf#1495]
I have a `Gemfile` with

```ruby
source 'https://rubygems.org'
gem 'berkshelf', '~> 4.0'
```
When it installs it gets berkshelf 4.0.1 and ridley 4.4.0

Ridley 4.4.0 seems to have broken its API since version 4.3.2 (semantic versions are for chumps) and `Ridley::Chef::Config` no longer has a `#chef_server_url` method. See the following error:

```
2.1.8 :001 > require 'berkshelf'
NoMethodError: undefined method `chef_server_url' for #<Ridley::Chef::Config:0x000000034a2790>
	from /home/foo/.rvm/gems/ruby-2.1.8@chef-repo/gems/berkshelf-4.0.1/lib/berkshelf/config.rb:80:in `<class:Config>'
	from /home/foo/.rvm/gems/ruby-2.1.8@chef-repo/gems/berkshelf-4.0.1/lib/berkshelf/config.rb:4:in `<module:Berkshelf>'
	from /home/foo/.rvm/gems/ruby-2.1.8@chef-repo/gems/berkshelf-4.0.1/lib/berkshelf/config.rb:3:in `<top (required)>'
	from /home/foo/.rvm/gems/ruby-2.1.8@chef-repo/gems/berkshelf-4.0.1/lib/berkshelf/cli.rb:2:in `require_relative'
	from /home/foo/.rvm/gems/ruby-2.1.8@chef-repo/gems/berkshelf-4.0.1/lib/berkshelf/cli.rb:2:in `<top (required)>'
	from /home/foo/.rvm/gems/ruby-2.1.8@chef-repo/gems/berkshelf-4.0.1/lib/berkshelf.rb:195:in `require_relative'
	from /home/foo/.rvm/gems/ruby-2.1.8@chef-repo/gems/berkshelf-4.0.1/lib/berkshelf.rb:195:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1
	from /home/foo/.rvm/rubies/ruby-2.1.8/bin/irb:11:in `<main>'
```
It doesn't seem to matter whether or not I have a `~/.chef/knife.rb` file or not. `Ridley::Chef::Config` just doesn't have those methods anymore. Since `Berkshelf.chef_config` is a `Ridley::Chef::Config`, all these methods are completely broken now: https://github.com/berkshelf/berkshelf/blob/v4.0.1/lib/berkshelf/config.rb#L78-L101

**Comment by b-dean** [comment]
seems to be related to berkshelf/ridley#325
@reset, @lamont-granquist, and @smith: Is this how it's supposed to work?

**Comment by reset** [comment]
We follow semantic versioning and try our best - mistakes happen.

/cc @jkeiser

**Comment by reset** [comment]
Closing in favor of the issue in the appropriate repository: https://github.com/berkshelf/berkshelf/issues/1495
