### ISSUE TITLE
Does Berkshelf support using a path on local file system as a default source?

### ISSUE THREAD

**Issue by funcode** [berkshelf/berkshelf#1498]
My Berksfile begins with:
source "https://api.berkshelf.com"

However, I need to run it on a environment where internet is not reachable.
May I download all the cookbooks(including dependency) and put it into a local folder, and change the source to something like file:///.... ?

Thanks

**Comment by louis-gounot** [comment]
Hello,

When I need this, I use 
source "http://localhost:65535/"
Not really clean, but it does the trick.

Feature asked in #1348 (source being optional in berksfile).

**Comment by reset** [comment]
@funcode as @louis-gounot mentioned, this was requested in #1348. I'd be more than happy to merge a PR which makes the source optional instead of required, but additionally prints to the console a warning letting you know that you haven't provided a source

closing becuase dup
