### ISSUE TITLE
chef_version setting in cookbook metadata 

### ISSUE THREAD

**Issue by cyberflow** [berkshelf/berkshelf#1499]
If i set chef_version in cookbook metadata then i have error:
```
An error occurred while reading the Berksfile:

  Could not parse `~/cookbooks/test/metadata.rb': undefined method `chef_version' for #<Ridley::Chef::Cookbook::Metadata:0x007fc55a4f24d8>
```

**Comment by madeddie** [comment]
@cyberflow which version of Berkshelf are you using?

I see the same problem using Berkshelf 3.2.0 on AWS OpsWorks (using Chef 11.04)

```
[2016-02-24T11:05:42+00:00] ERROR: Could not read /opt/aws/opsworks/current/merged-cookbooks/openresty into a Chef object: undefined method `chef_version' for #<Chef::Cookbook::Metadata:0x007f8287ddd7e8>
```

**Comment by lamont-granquist** [comment]
fixed in ridley

**Comment by tas50** [comment]
Just a heads up for anyone reading this. Chef 11 does not support the chef_version property in the metadata. Using that property in a metadata call makes it a Chef 12.4+ cookbook
