### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by ThisGuyCodes** [berkshelf/berkshelf#1504]
So I notice you simply direct people to berkshelf.com for usage instructions
![screenshot 2016-01-28 at 03 55 25](https://cloud.githubusercontent.com/assets/450860/12641063/17c4dcc2-c573-11e5-9bff-c3844951714d.png)
But uh....
![screenshot 2016-01-28 at 03 56 41](https://cloud.githubusercontent.com/assets/450860/12641076/2a5013e8-c573-11e5-99f0-dfec0dc2e51c.png)
The site says "v2.0", and the most recent version of 2.0 was...
![screenshot 2016-01-28 at 03 58 14](https://cloud.githubusercontent.com/assets/450860/12641132/6a1d5210-c573-11e5-909c-28bc4c34cdb9.png)
Over 18 months ago? And two major revisions, as the latest release was:
![screenshot 2016-01-28 at 03 57 19](https://cloud.githubusercontent.com/assets/450860/12641090/40434bac-c573-11e5-981c-411b85964678.png)
In fact:
![screenshot 2016-01-28 at 04 00 11](https://cloud.githubusercontent.com/assets/450860/12641179/a70dd492-c573-11e5-8aa2-b8adce238cb0.png)
The site appears to not have been updated at all in over a year (or else just no one noticed the copyright).

But I'm not here to complain. I'm just genuinely curious: are those _actually_ the most up to date usage instructions?
If yes:
- The site should have updated version/year numbers to avoid ambiguity.

If no, then either:
- Update the usage instructions (and the version/year numbers). Or
- Instead point people at somewhere where there are up to date instructions.

In fact, that site is also where [chef itself](https://docs.chef.io/berkshelf.html) directs people for documentation!

**Comment by kernelsmith** [comment]
there's always `berks -h` as well

**Comment by reset** [comment]
@conslo the instructions are up to date but the styling and header/footer on the site haven't been touched in quite a while. I'll update this when I get a free moment, thanks for the reminder!

**Comment by conslo** [comment]
:+1:

**Comment by jzohrab** [comment]
@conslo - maybe https://github.com/berkshelf/berkshelf/pull/1520 also addresses part of this, I had the same questions as you.

**Comment by conslo** [comment]
@jzohrab It does indeed help! But one would still never be guided to view that document.

**Comment by jzohrab** [comment]
Yup, I'm waiting for feedback from the Berkshelf team.  I think it belongs _somewhere_ in the official code/docs, will look to the team to determine where it should go and how people will find it.

**Comment by EugenMayer** [comment]
The issue with the page-header is quiet severe, also i was looking for 3.0+ docs and was not able to found them - until i found this issue wich states the docs are up to date, just the header is not. @reset any chance you make this little change there so people do not get frustrated? Thanks!

**Comment by thommay** [comment]
@EugenMayer we're working on an update to the site that would remove these problems.

**Comment by thommay** [comment]
berkshelf.com now redirects to https://docs.chef.io/berkshelf.com which is up to date, and easier to keep updated.

**Comment by EugenMayer** [comment]
@thommay not working for me 
![image](https://cloud.githubusercontent.com/assets/136934/20883931/e1a25ed2-bae8-11e6-95da-7739c39a50a8.png)

**Comment by thommay** [comment]
typo in my comment. The redirect is fine.

**Comment by EugenMayer** [comment]
@thommay the docs are great! All the path/source explaination, metadata keyword and general structure - that would have helped me a lot while i was starting / adjusting so i am sure beginners will have a lot joy with it.

Thank you for your work!

**Comment by thommay** [comment]
Thanks :)
