### ISSUE TITLE
Allow using a test cookbook from a subpath of another cookbook

### ISSUE THREAD

**Issue by patcon** [berkshelf/berkshelf#1505]
I would have thought this would allow me to reuse a test cookbook:

```rb
# Berksfile
cookbook 'acme_server',
  github: 'schubergphilis/letsencrypt',
  path: 'test/fixtures/cookbooks/acme_server'
```

But instead, I get this error:

```
In your Berksfile, you have:

  cookbook 'acme_server'

But that cookbook is actually named 'letsencrypt'

This can cause potentially unwanted side-effects in the future.

NOTE: If you do not explicitly set the 'name' attribute in the metadata, the name of the directory will be used instead. This is often a cause of confusion for dependency solving.
```

This wouldn't be so bad if I could just change the cookbook name to `letsencrypt`, but I also need to add that cookbook.

Is this something I should expect Berkshelf to be able to handle? (Sorry, I've had experience where I later found out something wasn't an intended use-case, so I feel I need to ask before starting work.)

Thanks!

**Comment by reset** [comment]
@patcon Apologies if you know this already, but this error means that the `name` attribute of the cookbook (which is defined in the `metadata.rb` file at the root) is set to `letsencrypt` but the name of the cookbook you're telling Berkshelf to look for is `acme_server` as indicated by the first parameter passed to `cookbook()` in your Berksfile.

I'm not quite sure what you mean by "I could change the cookbook name to `letsencrypt`, but I also need to add that cookbook". What do you mean by, "add that cookbook"?

I'm also not 100% sure why/what for you are re-using your test fixture.

I think I can get you in the right spot if you can answer those things for me!

**Comment by patcon** [comment]
heh thanks, but I did already understand your clarifications, so it was definitely me being unclear.

To rephrase: I have a cookbook of my own (ie. `mycookbook`) in which I have a `Berksfile` that I'm trying to include:

```rb
# Berksfile (mycookbook)
cookbook 'letsencrypt'
cookbook 'acme_server',
  github: 'schubergphilis/letsencrypt',
  path: 'test/fixtures/cookbooks/acme_server'
```

I'm trying to do this because I'm also implementing the letsencrypt setup in a non-standard way in my own cookbook, and want to reuse the server recipe. (There's not really clarity in what the "standard way" is just yet, so it's not an unreasonable thing.)

**Comment by reset** [comment]
@patcon I'm still not clear on what you're attempting, but now that I'm reading this in the afternoon instead of later at night I'm also noticing that you have specified both `path: #[val}` and `github: #{val}` locations for the `acme_server` cookbook. What are you attempting to do with that?

**Comment by patcon** [comment]
Attempting to reuse a fixture cookbook from `letsencrypt` to test `mycookbook`, which leverages `letsencrypt` but does enough new stuff to need new integration tests :)

**Comment by reset** [comment]
@patcon ok, I undersatnd exactly what you are doing now.

You can't name the fixture cookbook `letsencrypt`, you'll need to name it `letsencrypt-fixture` or something similar to that. This is working as intended as we would expose undefined behaviour if we allowed multiple cookbooks of the same name/version in the resolution chain

**Comment by patcon** [comment]
Hm. But... I believe I was following that advice already -- I was trying to call it `acme_server`, but it seems I was hitting this error in the base:
https://github.com/berkshelf/berkshelf/blob/master/lib/berkshelf/locations/base.rb#L73-L75

So even if I try to resolve without the actual letsencrypt cookbook, instead opting just for using the fixture (ie. surely no name clash), Berkshelf seems throw the error I first mentioned. So it's lapparently reading the root metadata.rb (which says "I'm called `letsencrypt`"), even though I'm pointing it to the path where the metadata says "acme_server".

```rb
# Berksfile
cookbook 'acme_server',
  github: 'schubergphilis/letsencrypt',
  path: 'test/fixtures/cookbooks/acme_server'
```

The error again, from above (sorry to repeat):

```
In your Berksfile, you have:

  cookbook 'acme_server'

But that cookbook is actually named 'letsencrypt'

This can cause potentially unwanted side-effects in the future.

NOTE: If you do not explicitly set the 'name' attribute in the metadata, the name of the directory will be used instead. This is often a cause of confusion for dependency solving.
```

**Comment by reset** [comment]
@patcon the path you are pointing to doesn't matter, the `metadata.rb` contains an attribute `name` which specifies the name of the cookbook. The cookbook at `test/fixtures/cookbooks/acme_server` has it's value set to `letsencrypt` and not `acme_server`.

You can fix this by changing the first argument to `cookbook()` to `letsencrypt` or change the value of the `name` attribute of the cookbook to `acme_server`

**Comment by reset** [comment]
Note: I should mention that the path *used* to matter. It took a number of years, but In Chef 12 the name attribute is now required

**Comment by patcon** [comment]
But it doesn't...?
https://github.com/schubergphilis/letsencrypt/blob/master/test/fixtures/cookbooks/acme_server/metadata.rb#L1

**Comment by reset** [comment]
@patcon This isn't a common path so it's likely a bug somewhere in our validation code that is ignoring the value of `path:` and checking the very root of the git repository being pulled down

**Comment by patcon** [comment]
Ok, good to know I'm not crazy. Doing a workaround atm, but I'll try to come back to it later

**Comment by louis-gounot** [comment]
@patcon, I think you should use :rel instead of :path.
Can you give a try and feedback ?

**Comment by patcon** [comment]
That is *really* helpful @louis-gounot! thanks!

I ended up splitting the test cookbook into it's own thing, as I imagine others will want to use it for testing letsencrypt. But if this comes up again, I would def prefer the `rel:` approach, rather than duplicating code in my git repo tbh :)

thanks again!
