### ISSUE TITLE
Authenticated universe endpoint in new Chef Server 12.4

### ISSUE THREAD

**Issue by joerg** [berkshelf/berkshelf#1511]
The latest chef server release includes a universe endpoint [1] which is in my eyes a really cool feature. Unfortunately, this endpoint is not public but needs to be authenticated. Currently bershelf (or the be exatct the berkshelf-api-client) does not support this, but having this feature would be great since I (and probably many others) don't want to install a full blown supermarket for this.

**Comment by reset** [comment]
@joerg I think you're right, it would be awesome to be able to use the Chef Server's endpoint in place of  an API server. If you want to submit a PR for it I'd be glad to merge!

**Comment by martinisoft** [comment]
This just landed in 4.3.0 #1527

**Comment by reset** [comment]
@martinisoft thanks for helping clean up the issue tracker ;)
