### ISSUE TITLE
Berks vendor should not delete the contents of the destination folder

### ISSUE THREAD

**Issue by eric-tucker** [berkshelf/berkshelf#1514]
Running this:
```
berks vendor --berksfile=<path to Berksfile> <destination path for vendored cookbooks>
```
deletes any existing files in the vendor path.  I've not sure why someone would want this behaviour by default.  This is like rsync having --delete as default behaviour.

As a result, I'm forced to vendor to a dummy path, then rsync to the destination path where I have existing cookbooks.

My use case is that I'm building a Chef Zero repo path and I'd like to vendor directly to the cookbooks folder but since berks vendor deletes all contents in the cookbooks folder before vendoring, I cannot do this.

**Comment by reset** [comment]
@eric-tucker I'm about 95% sure this is the behaviour because of another PR/Issue requesting for it to automatically delete the destination. That was a few years back so I can't recall exactly what the case was, but I'm pretty sure that it shouldn't delete the destination by default.

If you want to change the behaviour and add the option for a `--delete` flag I'd be more than happy to merge that PR in

**Comment by vinyar** [comment]
+1000
 This has bitten me more than once, and again just now, when it nuked a cookbook I was working on.

Following the core principle of chef - default is always the positive behavior. (service - start; file - create; etc..) The "Delete" should be an optional behavior, and default should not nuke the entire folder.

**Comment by vinyar** [comment]
Actually, now that I think about it, this is a very dangerous default behavior.

What if someone type `berks vendor ~` and presses return too fast. The results would be disastrous.

**Comment by eric-tucker** [comment]
Agree with the above. Default behavior should never be destructive.

**Comment by rponnoju1** [comment]
+100
This is a much required feature.

**Comment by ravisponnoju** [comment]
+100
berks vendor not deleting the existing files on destination would make life easier to directly add them to generic cookbooks folders (for community cookbooks) under version control while working on Chef Workstation.

Also, it would be useful if this command only puts the dependent cookbooks excluding the cookbook under construction/customization. This way, we can have customized cookbooks in one folder and site/community cookbooks in other folder without having a need to manually move the original cookbooks back to customized cookbooks folder. 
 
I'm speaking w.r.t below chef-repo structure:
Chef-repo
 |
 |-- cookbooks (original/customized cookbooks folder)
 |
 |-- site-cookbooks (dependent cookbooks pulled in from community)

**Comment by hal58th** [comment]
Why is this being ignored? It's not even labeled.

**Comment by reset** [comment]
@hal58th I responded above

**Comment by eric-tucker** [comment]
@reset I understand the response initially given but now that the community has pointed out the potentially disastrous results that can occur if berks vendor is run against the wrong location by mistake this is something that the berks team should be addressing, not the community.

I'm glad to see the labels have been added.
