### ISSUE TITLE
Unable to satisfy constraints on package due to solution constraint

### ISSUE THREAD

**Issue by grobinson-blockchain** [berkshelf/berkshelf#1515]
I have an issue with Berkshelf that I just cannot resolve.

I have a wrapper cookbook, `acmecorp_consul` with the following solution constraints in `metadata.rb` (I've renamed the prefix to the placeholder `acmecorp` for the posting of posting this issue):

```
depends 'consul', '~> 1.4.3'
depends 'consul-template', '~> 0.9.4'
depends 'sudo', '~> 2.7.2'
```

whose versions are defined in the Berksfile:

```
cookbook 'consul', '~> 1.4.3', git: 'git@github.com:johnbellone/consul-cookbook.git'
cookbook 'consul-template', '~> 0.9.4', git: 'git@github.com:adamkrone/chef-consul-template.git'
```

In addition, I have a second cookbook whose sole dependency is `acmecorp_consul`:

```
depends 'acmecorp_consul', '~> 0.1.15'
```

with the following definition in the Berksfile:

```
cookbook 'acmecorp_consul', '~> 0.1.15', :git => 'git@github.com:acmecorp/consul-cookbook.git'
```

However, when I run `berks install` I get the following error:

```
Unable to satisfy constraints on package consul-template due to solution constraint (acmecorp_consul = 0.1.15). Solution constraints that may result in a constraint on consul-template: [(acmecorp_consul = 0.1.15) -> (consul-template ~> 0.9.4)], [(test_cookbook = 0.0.1) -> (acmecorp_consul = 0.1.15) -> (consul-template ~> 0.9.4)]
Demand that cannot be met: (acmecorp_consul = 0.1.15)
Artifacts for which there are conflicting dependencies: consul-template = 0.7.0 -> [(ark >= 0.0.0), (golang ~> 1.4.0), (runit >= 0.0.0)]Unable to find a solution for demands: acmecorp_consul (0.1.15), test_cookbook (0.0.1)
```

However, I see no dependency on consul-template 0.7.0 in any of the `Berksfile.lock` files. What could be the issue here?

**Comment by Sauraus** [comment]
https://github.com/chef/dep-selector-libgecode/issues/43

**Comment by nozpheratu** [comment]
I'm running into this precise issue... it's driving me nuts!

**Comment by nozpheratu** [comment]
The "fix" that worked for me was to be as explicit as possible with version dependencies and to mirror the failing dependency in the 2nd cookbook.  E.g., in the second cookbook you would have:

```ruby
cookbook 'consul-template', '~> 0.9.4', git: 'git@github.com:adamkrone/chef-consul-template.git'
cookbook 'acmecorp_consul', '~> 0.1.15', :git => 'git@github.com:acmecorp/consul-cookbook.git'
```

The dependency solver needs to be spoon fed.

**Comment by lamont-granquist** [comment]
this is the transitive deps issue, it will likely never be fixed in berkshelf
