### ISSUE TITLE
Chef Test Kitchen (Berkshelf Issue): Message: Failed to complete #converge action: [SSL_connect returned=1 errno=0 state=error: certificate verify failed]

### ISSUE THREAD

**Issue by preston3271** [berkshelf/berkshelf#1524]
`Chef Development Kit Version: 0.11.0 `
`chef-client version: 12.7.2    `      
`berks version: 4.1.1               `  
`kitchen version: 1.5.0   `

`---           `                                                  
`driver:                                                         `
`  name: vagrant                       `                          
`  driver_config:                            `                    
`   http_proxy: "http://proxy.x.a.com:80"     `               
`   https_proxy: "https://proxy.x.a.com:80"            `      
                                                                
`provisioner:                                                    `
`  name: chef_zero                                               `
`  http_proxy: "http://proxy.x.a.com:80"                     `
 ` https_proxy: "https://proxy.x.a.com:80"                   `
`  chef_omnibus_url: "https://www.chef.io/chef/install.sh"       `
`platforms:                                                      `
`  - name: ubuntu-14.04            `                              
`  - name: centos-7.1                `                            
`  - name: centos65                  `                            
`    driver:                                  `                   
`     box: learningchef/centos65          `                       
`     box_url: learningchef/centos65       `                      
`  - name: centos65-1C                `                           
`    driver:                                     `                
`        box: learningchef/centos65     `                            
`        box_url: learningchef/centos65      `                       
`  - name: centos65-1D                         `                  
`    driver:                                              `       
`        box: learningchef/centos65            `                     
`        box_url: learningchef/centos65     `

`suites:`
`  - name: default`
`    run_list:`
`    - recipe[motd::default]`
`      attributes:`
`        chef-client:`
`           config:`
`             http_proxy: "http://proxy.x.a.com:80"`
`             https_proxy: "https://proxy.x.a.com:80"`

Scenario:  Setting up and configuring Test Kitchen to work behind a proxy (Successful Yaml File).

Error: Message: 
*Failed to complete #converge action: [SSL_connect returned=1 errno=0 state=error: certificate verify failed]*

` -----> Converging <default-centos65-1C>... `
`       Preparing files for transfer`
     `  Preparing dna.json`
    `   Resolving cookbook dependencies with Berkshelf 4.1.1...`
`>>>>>> ------Exception-------`
`>>>>>> Class: Kitchen::ActionFailed`
`>>>>>> Message: Failed to complete #converge action: [SSL_connect returned=1 errno=0 state=error: certificate verify failed]`
`>>>>>> ----------------------`

Fix gathered from: https://github.com/berkshelf/berkshelf/issues/1237     
 (Seth Vargo)

Original Berkfile:
-------------------------------------------------------
source 'https://supermarket.chef.io'

metadata
------------Changed To---------------------------
source 'http://api.berkshelf.com'

metadata
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Result:

`########################################### [100%]`
`          1:chef`
`########################################### [100%]`
      Thank you for installing Chef!
       Transferring files to <default-centos65-1C>
       Starting Chef Client, version 12.7.2
       Creating a new client identity for default-centos65-1C using the validator key.
       resolving cookbooks for run list: ["motd::default"]
       Synchronizing Cookbooks:
         - motd (0.1.0)
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: motd::default
   `      * cookbook_file[/etc/motd] action create`
    `       - update content in file /etc/motd from a7620c to b5d037`
      `     --- /etc/motd        2014-12-04 21:51:54.363631846 +0000`
     `      +++ /etc/.motd20160303-2398-v1ioki   2016-03-03 16:37:22.218060309 +0000`
    `       @@ -1,2 +1,9 @@`
`           -Welcome to your Packer-built virtual machine.`
       `    +         _______________________________________________`
     `      +        < YOU ARE ON A SIMULATED CHEF NODE ENVIRONMENT! >`
  `         +     -----------------------------------------------`
  `        +            \       ^__^`
   `        +             \      (oo)\___`
     `      +                    (__))\/\    \  `
        `   +                         ||----W|  `
      `     +                         ||       ||  `

`       Running handlers: `
`       Running handlers complete `
  `     Chef Client finished, 1/1 resources updated in 02 seconds '
 '      Finished converging <default-centos65-1C> (0m48.92s). '
 ' -----> Kitchen is finished. (0m53.14s)  `

Not sure why this change worked but it did.

**Comment by preston3271** [comment]
I Apologize for the formatting issues above.

**Comment by Ghento** [comment]
Hi

Thanks you saved my day...

**Comment by preston3271** [comment]
No problem.

On Fri, Apr 15, 2016 at 7:11 AM, Ghento <notifications@github.com> wrote:

> Hi
>
> Thanks you saved my day...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/berkshelf/berkshelf/issues/1524#issuecomment-210459728>
>



-- 
Thank you.

*Louis Preston Thornton III*
*Software Engineer*
*Proud Graduate Of*
*Colorado Technical University*
----------------------------------------------------
*Cell Phone:         (720) 879-2001*
*Voice Phone:      (720) 378-8165*

*Skype:                   preston4life**Alternate Email:
  louis3271@gmail.com <louis3271@gmail.com>*


*oice Phone:   (734) 335-0816*

**Comment by lamont-granquist** [comment]
looks like a standard ssl verification error -- either update the ca certs on the host doing the authentication, fix the busted SSL cert on the proxy or turn off SSL verification as appropriate.
