### ISSUE TITLE
Feature Request: add issues_url and source_url

### ISSUE THREAD

**Issue by majormoses** [berkshelf/berkshelf#1526]
Would love to see these added to cookbook metadata so that when I create a cookbook I dont have to add this in to get: http://www.foodcritic.io/#FC007 to pass.

**Comment by majormoses** [comment]
actually after looking I  might just need to add `--foodcritic` to my creation command. I am not sure on the validity of this feature request, would love some clarity on the matter.

**Comment by lamont-granquist** [comment]
closing in favor of chef-dk generators
