### ISSUE TITLE
Group feature not honouring defined groups

### ISSUE THREAD

**Issue by BitBrit** [berkshelf/berkshelf#1531]
I am using "berks vendor" in Berkshelf 3.3.0 (this is the version included with ChefDK 0.11.0) to collect cookbooks into a directory. However, I only want to do it on a per application cookbook basis. Each app has its own cookbook but also shares some common cookbooks so I needed a way to group the cookbooks required by each app.

Here is my resultant Berksfile:

``` ruby
source 'https://api.berkshelf.com'

group :app1 do
  cookbook 'cr', path: 'CR'
  cookbook "app1", path: 'app1'
end

group :app2 do
  cookbook 'cr', path: 'CR'
  cookbook 'app2', path: 'app2'
end
```

At this point there is no Berksfile.lock file. I use the following command:
**berks vendor app1.vendor -o app1**

``` bash
Resolving cookbook dependencies...
Fetching 'app1' from source at app1
Fetching cookbook index from https://api.berkshelf.com...
Using chef-sugar (3.3.0)
Using app1 (1.0.0) from source at app1
Using firewall (2.4.0)
Vendoring chef-sugar (3.3.0) to app1.vendor/chef-sugar
Vendoring firewall (2.4.0) to app1.vendor/firewall
Vendoring app1 (1.0.0) to app1.vendor/app1
```

This is when it seems to go wrong. Where is the 'cr' cookbook?  It correctly collected all the dependencies for the app1 cookbook but didn't include 'cr'.  I tried the same again for app2.

**berks vendor app2.vendor -o app2**

``` bash
Resolving cookbook dependencies...
Fetching 'cr' from source at CR
Fetching 'app2' from source at app2
Fetching cookbook index from https://api.berkshelf.com...
Using line (0.6.3)
Using app2 (1.0.0) from source at app2
Using hostsfile (2.4.5)
Using chef-sugar (3.3.0)
Using limits (1.0.0)
Using firewall (2.4.0)
Using cr (1.0.0) from source at CR
Vendoring chef-sugar (3.3.0) to app2.vendor/chef-sugar
Vendoring cr (1.0.0) to app2.vendor/cr
Vendoring app2 (1.0.0) to app2.vendor/app2
Vendoring firewall (2.4.0) to app2.vendor/firewall
Vendoring hostsfile (2.4.5) to app2.vendor/hostsfile
Vendoring limits (1.0.0) to app2.vendor/limits
Vendoring line (0.6.3) to app2.vendor/line
```

This worked fine; all remote and local cookbook dependancies accounted for.  To test this a little further I swapped the positions of the group definitions in the Berksfile so it became:

``` ruby
source 'https://api.berkshelf.com'

group :app2 do
  cookbook 'cr', path: 'CR'
  cookbook 'app2', path: 'app2'
end

group :app1 do
  cookbook 'cr', path: 'CR'
  cookbook "app1", path: 'app1'
end
```

And reran berks vendor:

**berks vendor app1.vendor -o app1**

``` bash
Resolving cookbook dependencies...
Fetching 'cr' from source at CR
Fetching 'vmr' from source at vmr
Fetching cookbook index from https://api.berkshelf.com...
Using vmr (1.0.0) from source at vmr
Using firewall (2.4.0)
Using cr (1.0.0) from source at CR
Using chef-sugar (3.3.0)
Vendoring chef-sugar (3.3.0) to app1.vendor/chef-sugar
Vendoring cr (1.0.0) to app1.vendor/cr
Vendoring firewall (2.4.0) to app1.vendor/firewall
Vendoring vmr (1.0.0) to app1.vendor/vmr
```

Worked. So it looks like cookbooks which appear in more than one group file are disassociated from a previous group and only associated with the final group in which they are defined.  I am not sure how dependency resolution works in Berkshelf but does this mean that groups can only be made up of a set of distinct cookbooks?  If so then this somewhat limits the usefulness of the groups feature as I would then have to do something like:

``` ruby
group :common do
  cookbook 'cr', path: 'CR'
end

group :app1 do
  cookbook 'app1', path: 'app1'
end

group :app2 do
  cookbook "app2", path: 'app2'
end
```

And run it with:

**berks vendor app1.vendor -o common app1**

Another workaround would be to group my cookbooks in a separate file and then read that file from the Berksfile which would build the 'cookbook' lines based on the contents of that file.  I am hoping that this isn't necessary and it's just me doing something wrong or perhaps just an unintended bug?  I can provide  debug output if necessary or any other information.  

Any help much appreciated.

**Comment by lamont-granquist** [comment]
dup of #1378
