### ISSUE TITLE
metadata precedence

### ISSUE THREAD

**Issue by ameir** [berkshelf/berkshelf#1536]
I was pulling my hair out trying to resolve a dependency issue, and it turned out that the problem was due to a rogue cookbook that had _both_ a metadata.rb and a metadata.json, each at different versions.  The metadata.rb was at 0.6.6, the metadata.json at 0.6.3.  When I'd do a `berks install`, things would look good, but any subsequent command would fail, complaining that 0.6.3 of the cookbook was not available.

I know this isn't common, but if a warning can be thrown if both files exist, or if metadata.rb (or metadata.json) was referenced _always_, then that'd be ideal.  I think throwing a warning (or failing entirely) is ideal, just like with cookbooks without the name attribute in the metadata.

**Comment by joerg** [comment]
I also just stumbled upon this when trying to create the dependency graph with "berks viz" of a vendored cookbook from the supermarket. In my case the was no metadata.rb at all and in this case berks gave an error that the metadata.rb does not exist. The nasty thing is, if I create a metadata.rb with just the name in it berks will still work and resolve all dependencies defined in the metadata.json.

Not sure which approach fits best here but from my point of view berks should definitely work with just a JSON _or_ RB and if both exist a warning should be issued about the precedence.

**Comment by lamont-granquist** [comment]
might be fixed by #1352

**Comment by joerg** [comment]
Yes, judging from the code this looks good. But the discussion and the failing checks don't make it very likely that this gets merged...

**Comment by kamaradclimber** [comment]
We have a use case (https://github.com/criteo/cookbook-release) where we add some code in the metadata.rb to detect version based on git tag.
The behavior is based on the fact that berkshelf did not vendor metadata.rb (before #1652) which allow to use the version compiled during `berks vendor`.

It would be really important for us to have the choice in the priority order (of course we'll have to configure for each tool since I know that chef-zero prefers .rb over .json)

**Comment by lamont-granquist** [comment]
@kamaradclimber are you still bug dependent upon this?  the bugs in cheffs and chef-zero were fixed back in jan / chef-12.19.x so that they favor json over rb

**Comment by kamaradclimber** [comment]
I think it's ok indeed. I've relaxed every chef related constraints we have inour environment and will see if we encounter the same bug. Thanks!
