### ISSUE TITLE
Unable to satisfy constraints on package memcached

### ISSUE THREAD

**Issue by MrPink** [berkshelf/berkshelf#1537]
Hi,

Getting a strange issue when using the Memcached cookbook and a custom cookbook. 

"Error message: Unable to satisfy constraints on package memcached, which does not exist, due to solution constraint (foo >= 0.0.0). Solution constraints that may result in a constraint on memcached: [(foo = 0.4.1) -> (memcached >= 0.0.0)]

I haven't pinned to any particular version and have also removed any old cookbooks, my Berksfile.lock looks like

  foo (0.4.1)
    memcached (>= 0.0.0)

Using berkshelf (4.0.1)

Any pointers appreciated 

Thanks

**Comment by cheeseplus** [comment]
What does the metadata.rb look like for foo?

**Comment by lamont-granquist** [comment]
can't reproduce this
