### ISSUE TITLE
Cannot create cookbook using berks command

### ISSUE THREAD

**Issue by ephracis** [berkshelf/berkshelf#1538]
I cannot create cookbooks using the `berks` command on OS X. Here's what happens:

```
$ berks --version
4.3.1
$ berks cookbook registry
      create  registry/files/default
      create  registry/templates/default
      create  registry/attributes
      create  registry/libraries
      create  registry/providers
      create  registry/recipes
      create  registry/resources
      create  registry/recipes/default.rb
      create  registry/metadata.rb
      create  registry/LICENSE
      create  registry/README.md
      create  registry/CHANGELOG.md
Invalid configuration:
  vagrant.vm.box Expected attribute: 'vagrant.vm.box' to be a type of: 'String'
  vagrant.vm.box A value is required for attribute: 'vagrant.vm.box'
  ssl.verify Expected attribute: 'ssl.verify' to be a type of: 'Buff::Boolean'
  ssl.verify A value is required for attribute: 'ssl.verify'
```

**Comment by coalwater** [comment]
I'm getting this exact error, but when using `berks init .`

**Comment by cheeseplus** [comment]
Have you tried `--skip-vagrant`?

**Comment by cheeseplus** [comment]
And while this is anecdotal, most folks in the Chef community have moved to using ChefDK (or the gem itself if you wanted) which comes with a robust `chef generate cookbook NAME` command and modifiable templates. Not to say you can't still use `berks init` it's just not the goto mechanism.

**Comment by coalwater** [comment]
@cheeseplus `--skip-vagrant` didn't change much for me, and the only reason I'm using `berks init` is that I'm studying from the opsworks guide, and it suggested using that.
Using `chef generate` though fixed the issue for me.
I'm currently using the chef gem not ChefDK because chefdk installs a lot of gems on the system and I'm using chruby (a ruby version manager) so I wanted the gems to be under the user not the system.

Thanks for your help. :smile:

**Comment by gravitystorm** [comment]
@ephracis were you using ruby 2.3? You were getting the same error message as I was, see #1513

**Comment by ephracis** [comment]
Don't know what I did but I recently tried the same command and now it works. Running ruby 2.3. I have been reinstalling ChefDK and most chef-related gems because of a multitude of conflicts between them. Guess it was something in there that fixed the issue. Sorry I can't provide more info than that.
