### ISSUE TITLE
chef_server source does not work as documented.

### ISSUE THREAD

**Issue by dgarstang** [berkshelf/berkshelf#1540]
The berkshelf documentation says:

"If a source is configured with the location :chef_server, then Berkshelf will use the configured Chef Server as an API source. This requires Chef Server 12.4.0 or newer, or Hosted Chef."

I have the latest version of berkshelf installed, 4.3.1, and attempting to use 'source :chef_server' in the Berksfile yields:

```'chef_server' is not a valid Berkshelf source URI. Can't convert Symbol into String..```

**Comment by Kgirthofer** [comment]
What was your solution - I'm currently getting this as well
