### ISSUE TITLE
No such command "berks configure"

### ISSUE THREAD

**Issue by spuder** [berkshelf/berkshelf#1549]
The documentation states that you can generate a berks config by running `berks configure`
http://berkshelf.com/v2.0/

Yet, no configure command exists. 

```
sowens-MBP:nd-web sowen$ chef --version
Chef Development Kit Version: 0.13.21
chef-client version: 12.9.41
berks version: 4.3.2
kitchen version: 1.7.3
sowens-MBP:nd-web sowen$ berks configure
Could not find command "configure".
```

**Comment by reset** [comment]
@spuder that's the documentation for Berkshelf 2.0 which is almost 3 years old. The up to date documentation is at `http://berkshelf.com`

**Comment by spuder** [comment]
Thanks for clarifying. I assumed that was the latest since the documentation has a link to it that says "current version" 

![screenshot 2016-04-27 12 28 21](https://cloud.githubusercontent.com/assets/242382/14863604/a054004e-0c73-11e6-83f2-599bdbfe49ec.png)
