### ISSUE TITLE
Getting an error while uploading a new cookbook.

### ISSUE THREAD

**Issue by Gautami007** [berkshelf/berkshelf#1551]
here was an error connecting to the Chef Server
E, [2016-05-02T10:06:22.269339 #31616] ERROR -- : Cookbook file files/halite_gem/poise/helpers/subresources/child.rb has a ruby syntax error:
E, [2016-05-02T10:06:22.269689 #31616] ERROR -- : /var/lib/jenkins/.berkshelf/cookbooks/poise-2.7.0/files/halite_gem/poise/helpers/subresources/child.rb:240: syntax error, unexpected tLABEL
E, [2016-05-02T10:06:22.269784 #31616] ERROR -- : ...ef parent_attribute(name, type: Chef::Resource, optional: fa...
E, [2016-05-02T10:06:22.269862 #31616] ERROR -- : ...                               ^
E, [2016-05-02T10:06:22.269947 #31616] ERROR -- : /var/lib/jenkins/.berkshelf/cookbooks/poise-2.7.0/files/halite_gem/poise/helpers/subresources/child.rb:240: dynamic constant assignment
E, [2016-05-02T10:06:22.270023 #31616] ERROR -- : ...ute(name, type: Chef::Resource, optional: false, auto: true,...
E, [2016-05-02T10:06:22.270124 #31616] ERROR -- : ...                               ^
E, [2016-05-02T10:06:22.270206 #31616] ERROR -- : /var/lib/jenkins/.berkshelf/cookbooks/poise-2.7.0/files/halite_gem/poise/helpers/subresources/child.rb:240: syntax error, unexpected tLABEL, expecting '='
E, [2016-05-02T10:06:22.270291 #31616] ERROR -- : ...type: Chef::Resource, optional: false, auto: true, default: ...
E, [2016-05-02T10:06:22.270363 #31616] ERROR -- : ...                               ^
E, [2016-05-02T10:06:22.270456 #31616] ERROR -- : /var/lib/jenkins/.berkshelf/cookbooks/poise-2.7.0/files/halite_gem/poise/helpers/subresources/child.rb:240: Can't assign to false
E, [2016-05-02T10:06:22.270576 #31616] ERROR -- : ...hef::Resource, optional: false, auto: true, default: nil)
E, [2016-05-02T10:06:22.270628 #31616] ERROR -- : ...                               ^
E, [2016-05-02T10:06:22.270714 #31616] ERROR -- : /var/lib/jenkins/.berkshelf/cookbooks/poise-2.7.0/files/halite_gem/poise/helpers/subresources/child.rb:240: Can't assign to true
E, [2016-05-02T10:06:22.270797 #31616] ERROR -- : ...e, optional: false, auto: true, default: nil)
E, [2016-05-02T10:06:22.270894 #31616] ERROR -- : ...                               ^
E, [2016-05-02T10:06:22.271009 #31616] ERROR -- : /var/lib/jenkins/.berkshelf/cookbooks/poise-2.7.0/files/halite_gem/poise/helpers/subresources/child.rb:276: syntax error, unexpected keyword_end, expecting $end
E, [2016-05-02T10:06:22.277567 #31616] ERROR -- : Ridley::Errors::CookbookSyntaxError: Invalid ruby files in cookbook: poise (2.7.0).

**Comment by lamont-granquist** [comment]
the ruby version you're uploading on probably doesn't support the syntax being used in that cookbook.
