### ISSUE TITLE
transitory dependencies 

### ISSUE THREAD

**Issue by westdart** [berkshelf/berkshelf#1552]
I am developing cookbooks for which some have community cookbook dependencies. All these cookbooks are available in a single cookbooks directory (I will call these internal cookbooks).

My problem is that where I have dependencies on Internal cookbooks I have to add an entry to the Berksfile stating the path where it can be found. This all works fine until there is a transitive dependency relying on this feature.

For example, I created three cookbooks; 'a', 'b' and 'c' with 'a' depending on 'b' and 'b' depending on 'c'.
I added the following line to 'a/Berksfile':
>  cookbook 'b', path: '../b'

and also added the dependency to the 'metadata.rb' file

Likewise in 'b/Berksfile':
>  cookbook 'c', path: '../c'

(plus dependency in 'metadata.rb')

Now when I execute the command:
> berks install -b cookbooks/a/Berksfile

I get: 

> Unable to satisfy the following requirements:
> `c (>= 0.0.0)` required by `b-0.1.0`
> Unable to find a solution for demands: a (0.1.0), b (0.1.0)

If I execute:
> berks install -b cookbooks/b/Berksfile

 it is successful, as it honours the directive in the b/Berksfile

Why is this not honoured when executing against a/Berksfile?

(Also if I remove the 'depends c' line in b/metadata.rb it also works)

I also looked at '--except' to exclude certain cookbooks but could not get that to work.

Any help would be appreciated.

**Comment by westdart** [comment]
I have found a way around this by duplicating the dependency declaration in the parent Berksfile, e.g. from the example I gave above; the 'a' cookbook Berksfile needs its immediate dependency ('b') declared and the transitory dependency ('c'):
> cookbook 'b', path: '../b'
> cookbook 'c', path: '../c'

**Comment by lamont-granquist** [comment]
dup of many other tickets.  bundler does not transitively read Gemfiles either.  this would overly complicate dep solving.
