### ISSUE TITLE
cookbook generation patterns?

### ISSUE THREAD

**Issue by gliptak** [berkshelf/berkshelf#1555]
I might have missed this in the documentation, but ```cookbook patterns``` ```environment, application, library, wrapper``` do not seem to have details offered on. Thanks

```
$ berks cookbook --help
...
Options:
  -p, [--pattern=PATTERN]                              # Modifies the generated skeleton based on the given pattern.
                                                       # Default: application
                                                       # Possible values: environment, application, library, wrapper
```

**Comment by gliptak** [comment]
https://github.com/berkshelf/berkshelf/pull/955 links to http://blog.vialstudios.com/the-environment-cookbook-pattern/

**Comment by lamont-granquist** [comment]
closing generator issues in favor of chef-dk's generators

**Comment by gliptak** [comment]
https://docs.chef.io/ctl_chef.html#chef-generate-app

Reading the documentation, ```chef generate``` does seem to generate ```berks``` scaffolding
