### ISSUE TITLE
Berks init . fails with Invalid Configuration

### ISSUE THREAD

**Issue by cody-adams** [berkshelf/berkshelf#1556]
I'm trying to do a `berks init .` in a newly created cookbook
I used: `knife cookbook create nginx` to create it, then when i cd into it and try to setup the berkshelf it fails.
I created a berkshelf in another cookbook perfectly fine 2 days ago with this same method. 
```
Invalid configuration:
  vagrant.vm.box Expected attribute: 'vagrant.vm.box' to be a type of: 'String'
  vagrant.vm.box A value is required for attribute: 'vagrant.vm.box'
  ssl.verify Expected attribute: 'ssl.verify' to be a type of: 'Buff::Boolean'
  ssl.verify A value is required for attribute: 'ssl.verify'
```
This is what it gives me. I feel like it would be an easy way to solve it but I can't even find the config file that this is apparently trying to pull from. `berks configure` is also not available. I have downloaded and installed the latest Chef DK. Not sure where to turn at this point.

**Comment by lehn-etracker** [comment]
I got the same error. Any news on this issue?

**Comment by lamont-granquist** [comment]
use chefdk and `chef generate cookbook`
