### ISSUE TITLE
Berkshelf cookbook command fails with validation error on an empty gemset

### ISSUE THREAD

**Issue by bob2build** [berkshelf/berkshelf#1559]
I ran 

```
gem install berkshelf
berks -v
berks cookbook sample
```

Here are the logs

```
[bob@dhcppc4 cookbooks]$ berks -v
4.0.1

[bob@dhcppc4 cookbooks]$ berks cookbook sample
      create  sample/files/default
      create  sample/templates/default
      create  sample/attributes
      create  sample/libraries
      create  sample/providers
      create  sample/recipes
      create  sample/resources
      create  sample/recipes/default.rb
      create  sample/metadata.rb
      create  sample/LICENSE
      create  sample/README.md
      create  sample/CHANGELOG.md
Invalid configuration:
  vagrant.vm.box Expected attribute: 'vagrant.vm.box' to be a type of: 'String'
  vagrant.vm.box A value is required for attribute: 'vagrant.vm.box'
  ssl.verify Expected attribute: 'ssl.verify' to be a type of: 'Buff::Boolean'
  ssl.verify A value is required for attribute: 'ssl.verify'

I am getting the following error.
Invalid configuration:
  vagrant.vm.box Expected attribute: 'vagrant.vm.box' to be a type of: 'String'
  vagrant.vm.box A value is required for attribute: 'vagrant.vm.box'
  ssl.verify Expected attribute: 'ssl.verify' to be a type of: 'Buff::Boolean'
  ssl.verify A value is required for attribute: 'ssl.verify'
```

It also fails in version 4.3.1

**Comment by barryku** [comment]
see my comments at https://github.com/berkshelf/berkshelf/issues/1560

**Comment by gravitystorm** [comment]
@bob2build Are you running ruby 2.3? See #1513 . You're getting the same error message as I was.

**Comment by bob2build** [comment]
@barryku  I tried moving the berks exeutable to /tmp folder and deleted the symlink, Even then I am getting the same error. 

```
sudo mv /opt/chefdk/bin/berks /tmp/.
[sudo] password for bob: 
[bob@localhost gpnv]$ sudo rm /usr/bin/berks 
[bob@localhost gpnv]$ rm -rf hello
[bob@localhost gpnv]$ berks cookbook hello
      create  hello/files/default
      create  hello/templates/default
      create  hello/attributes
      create  hello/libraries
      create  hello/providers
      create  hello/recipes
      create  hello/resources
      create  hello/recipes/default.rb
      create  hello/metadata.rb
      create  hello/LICENSE
      create  hello/README.md
      create  hello/CHANGELOG.md
Invalid configuration:
  vagrant.vm.box Expected attribute: 'vagrant.vm.box' to be a type of: 'String'
  vagrant.vm.box A value is required for attribute: 'vagrant.vm.box'
  ssl.verify Expected attribute: 'ssl.verify' to be a type of: 'Buff::Boolean'
  ssl.verify A value is required for attribute: 'ssl.verify'
```

@gravitystorm Yes, I am using 2.3.

**Comment by barryku** [comment]
@bob2build , I am now running the version at /opt/chefdk/bin/berks, not the other way around.  So for me, I did mv ~/.rvm/gems/ruby-2.3.0/gems/berkshelf-4.3.3/bin/berks ~/.rvm/gems/ruby-2.3.0/gems/berkshelf-4.3.3/bin/berks.bk

I use rvm to switch to older 1.x ruby as needed, but my primary version is 2.3.0.  When I did "which berks" it was pointing to the above one, now it's back to the soft link created by ChefDK at /usr/local/bin/berks.

**Comment by bob2build** [comment]
Yup, berks command from chefdk works. However, berks gem of the same version as that in chefdk doesn't work on an empty gemset. I am writing some pipeline scripts, which needs to use berkshelf installed as a gem. I wanted to use the same for development for consistent experience.

**Comment by lamont-granquist** [comment]
this was a bug somewhere in buff-extensions/varia_model/buff-config related to ruby 2.3.0 which got fixed along time ago, somewhere in the linked to issues there should be a link to a link to the thing that actually fixed it...
