### ISSUE TITLE
Error while creating Cookbook using Berks

### ISSUE THREAD

**Issue by ashutosh-webonise** [berkshelf/berkshelf#1560]
create  test/files/default
      create  test/templates/default
      create  test/attributes
      create  test/libraries
      create  test/providers
      create  test/recipes
      create  test/resources
      create  test/recipes/default.rb
      create  test/metadata.rb
      create  test/LICENSE
      create  test/README.md
      create  test/CHANGELOG.md
**Invalid configuration:
  vagrant.vm.box Expected attribute: 'vagrant.vm.box' to be a type of: 'String'
  vagrant.vm.box A value is required for attribute: 'vagrant.vm.box'
  ssl.verify Expected attribute: 'ssl.verify' to be a type of: 'Buff::Boolean'
  ssl.verify A value is required for attribute: 'ssl.verify'**

**Comment by barryku** [comment]
For my case, it's caused by installing berkself using gem after it's installed by ChefDK.  To resolve the issue, rename the berks executable created by gem installation, so it runs /usr/local/bin/berks which links to ChefDK's version.

**Comment by gravitystorm** [comment]
@ashutosh-webonise are you running ruby 2.3.0? See #1513 . I was receiving the same error message.

**Comment by lamont-granquist** [comment]
#1591 #1592
