### ISSUE TITLE
Berkshelf not reading config.json in ruby >= 2.3.0

### ISSUE THREAD

**Issue by viggeh** [berkshelf/berkshelf#1563]
So, I've been having problems with using berkshelf with ruby 2.3.1 where it is not respecting my configuration files.

At the top of my Berksfile, I have
```
source :chef_server
source "https://supermarket.chef.io/"
```

and in ```$(pwd)/.berkshelf/config.json```, I have
```json
{
   "chef": {
     "chef_server_url" : "my_chef_server_url",
     "node_name": "client_name",
     "client_key": "path_to_client_key"
   }
 }
```

It does not matter if I put this config file in

- ```$(pwd)/.berkshelf/config.json```
- ```$(pwd)/config.json```
- ```~/.berkshelf/config.json```
- ```~/config.json```

The contents are never read and used, even if I supply it on the command line with the ```-c``` flag. Berkshelf will instead try to download from localhost which is probably some default value. 

Now, if i switch over to ruby 2.2.5, everything starts working as expected.

**Comment by viggeh** [comment]
This might be related to https://github.com/berkshelf/berkshelf/issues/1513

**Comment by lamont-granquist** [comment]
#1591 #1592
