### ISSUE TITLE
"can't create Thread: Resource temporarily unavailable (ThreadError)" when using test-kitchen

### ISSUE THREAD

**Issue by dougli1sqrd** [berkshelf/berkshelf#1573]
Hello!
We are using berkshelf 4.0.1 along with test-kitchen 1.8.0, and (if relevant) kitchen-openstack 3.0.0. On our local development environment we use Vagrant and chef_solo to provision machines before putting them in the cloud. I'm using test-kitchen to create cloud servers in an openstack environment and provision cookbooks without uploading first to the Chef Server. On the Vagrant VM this is all fine, and works as expected: 

```
Resolving cookbook dependencies with Berkshelf 4.0.1...
D      Using Berksfile from /path/to/my/berksfile
       Removing non-cookbook files before transfer
       Preparing data_bags
D      Using data_bags from /tmp/databags
       Preparing solo.rb
...
etc
```

Cookbook dependencies and databags get uploaded to cloud server and provisioning happens.

When I do the same thing _in_ a cloud (openstack) server environment (_not_ my local Vagrant VM) I get  the error in the title:
[berkshelf_trace.txt](https://github.com/berkshelf/berkshelf/files/312857/berkshelf_trace.txt)

I've looked at both https://github.com/bundler/bundler/issues/4367 and https://github.com/berkshelf/berkshelf/issues/1224 for explanations or solutions. One thing we tried to at least reproduce it on the local Vagrant VM was what was suggested in this comment: https://github.com/bundler/bundler/issues/4367#issuecomment-215975065 but that didn't seem to have any affect. 

I've looked into various nproc settings on the openstack cloud machine and on the local Vagrant VM and everything seems reasonable, so far as I can tell, but I still might have missed something. The workaround suggested in the linked berkshelf issue (#1224) of just repeating the berkshelf command until all the cookbooks download or resolve is not an option for me as this ideally will be run through an automated process (like bamboo CI). Additionally, the workaround didn't seem to work for me. After repeating the command dozens of times, it still failed in the same place. 

I appreciate any help you can offer!
Thanks!

**Comment by lamont-granquist** [comment]
looks like a celluloid error which no longer exists as a berkshelf dep.  if this problem persists in berkshelf > 7.0 please open a new issue.
