### ISSUE TITLE
berks install refers to older cookbook name after rename

### ISSUE THREAD

**Issue by 141984** [berkshelf/berkshelf#1577]
Hi,

I had to rename my cookbook from A to B and after this berks install/update still refers to the old cookbook name.

I tried install/updated after removing the Berksfile.lock file and also made sure that the old cookbook name is not mentioned in any of the files in my cookbook folder. But every time i do an update/install it still gets the old cook name and creates the Berksfile.lock with it.

I also tried deleting the ~/.berkshelf folder, but this too didn't help. 

Why is this happening? where is berks picking up the cookbook name from?

Is re-naming a cookbook not recommend ?

Chef Development Kit Version: 0.14.25
chef-client version: 12.10.24
berks version: 4.3.3
kitchen version: 1.10.2

**Comment by reset** [comment]
Renaming a cookbook is perfectly acceptable but you may still be pulling it in as a dependency of a dependency. I would look at the dependency graph and do some digging to see where it's coming from

**Comment by 141984** [comment]
I tried to get the dependency graph using `berks viz` command, but its need graphviz installed and looks like www.graphviz.org is down. What options do i have now to get graphviz / get the dependency graph

i'm running OS X 10.11.5

**Comment by 141984** [comment]
I re-created the metadata.rb file and then ran berks update. This solved the issue for me.
