### ISSUE TITLE
Berks shows the wrong version of a cookbook

### ISSUE THREAD

**Issue by jorhett** [berkshelf/berkshelf#1603]
During dependency resolution Berks shows the correct (and only)  version of a cookbook. However, it writes a different, non-existent version to Berksfile.lock

Details shown at https://gist.github.com/jorhett/dd5d695c37d1e957ff862a4033a7dcd8

This would seem to be related to `:chef_server` resolution, as I've never seen this problem before.

**Comment by jorhett** [comment]
Note that there are zero cookbooks with a lock on that version (as shown in the debug) and this cookbook works perfectly fine when run by chef clients from the chef server.

**Comment by jorhett** [comment]
So it turns out this is a display problem. Downloading the cookbook from the server, I found that it has both a metadata.rb and a metadata.json and they disagree on version numbers. Removing the metadata.json and uploading it back to the server solved the problem.

However, the results shown by Berks when this occurs were not helpful in that diagnosis. If it's going to write version 0.0.2 to the file, it should show version 0.0.2 in the output and debug.

**Comment by lamont-granquist** [comment]
we'd accept a PR, but this is too low of a priority to keep open
