### ISSUE TITLE
possible bug in ruby resolver 

### ISSUE THREAD

**Issue by igorfraa** [berkshelf/berkshelf#1607]
We have two cookbooks, both have dependency on community poise-python cookbook. 

In one there is a version specified:
`depends 'poise-python', '= 1.4.0'`
Another is meant to depend on any available version:
`depends           "poise-python"`

While the default resolver works fine, the ruby resolver produces following output:
`Unable to satisfy the following requirements:
- `poise-languages (~> 1.3)` required by `poise-python-1.4.0`
- `poise-languages (~> 2.0)` required by `poise-python-1.4.0``

If we put the same `depends 'poise-python', '= 1.4.0'` instead of `depends           "poise-python"` the ruby resolver is fine.

Is it expected behaviour? Could we do something to alter this?

Looks we could manually track similarity of dependency versions in all the cookbooks.

**Comment by lamont-granquist** [comment]
i can't replicate this bug.  hopefully this has been fixed by bumping the molinillo versions similarly to #1616
