### ISSUE TITLE
Ruby resolver ignores constraints

### ISSUE THREAD

**Issue by b-dean** [berkshelf/berkshelf#1616]
I've tested this with Berkshelf 5.x and 4.x and I get the same results with both. For some reason it's ignoring a dependency I explicitly set in my `Berksfile`

``` ruby
source "https://supermarket.chef.io"
cookbook 'nginx', '~> 2.7'
cookbook 'mercurial'
cookbook 'windows', '< 2'
```

But for some reason it installs version `2.0.2` of the `windows` cookbook. Even though I said `< 2` _and_ there are versions of `windows` that would satisfy the other cookbook's dependencies as well.

Here's the whole `Berkshelf.lock`

```
DEPENDENCIES
  mercurial
  nginx (~> 2.7)
  windows (< 2.0.0)

GRAPH
  7-zip (1.0.2)
    windows (>= 1.2.2)
  apt (2.9.2)
  bluepill (2.4.3)
    rsyslog (>= 2.0)
  build-essential (2.4.0)
    7-zip (>= 0.0.0)
  compat_resource (12.14.6)
  mercurial (2.0.4)
    build-essential (>= 0.0.0)
    python (>= 0.0.0)
    windows (>= 0.0.0)
  nginx (2.7.6)
    apt (~> 2.2)
    bluepill (~> 2.3)
    build-essential (~> 2.0)
    ohai (~> 2.0)
    runit (~> 1.2)
    yum-epel (~> 0.3)
  ohai (2.1.0)
  packagecloud (0.2.5)
  python (1.4.6)
    build-essential (>= 0.0.0)
    yum-epel (>= 0.0.0)
  rsyslog (4.0.1)
    compat_resource (>= 0.0.0)
  runit (1.8.0)
    packagecloud (>= 0.0.0)
    yum-epel (>= 0.0.0)
  seven_zip (2.0.2)
    windows (>= 1.2.2)
  windows (2.0.2)
  yum (4.0.0)
  yum-epel (0.7.1)
    yum (>= 3.6.3)
```

I got the same results with Berkshelf 5.1.0, 4.3.5, and 4.2.3.

**Comment by b-dean** [comment]
Also why is `seven_zip` in there at all? It's not in the dependency tree that I can see.

**Comment by smedefind** [comment]
I'm seeing this problem too.

I had to revert back to Berkshelf 4.0.1 to get around it.

**Comment by Sauraus** [comment]
Have you tried bumping the version for the cookbook you are modifying?

**Comment by b-dean** [comment]
@Sauraus, I'm not sure I follow. I have a cookbook that depended on `'windows', '~> 1.34'` and also depended on `'mercurial'`. When I run `berks install` it completely ignores the windows cookbook restriction because the mercurial cookbook has `'windows', '>= 0'` and somehow that wins.

I'm not sure what increasing the version of my cookbook would accomplish. I can pick any version of my cookbook and this happens. The example I gave above actually doesn't even *have* a cookbook, it's just a `Berksfile` that I created to demonstrate the bug.

Certainly I can modify my cookbook to start using windows cookbook 2.x, and I have done that to work around this bug (since I had no choice since Berkshelf refused to install the older windows cookbook). But again, that's not the point. The point is, I tell Berkshelf to do something (something which has an *obvious* solution), and it won't do it.

**Comment by Sauraus** [comment]
What is the name of your cookbook? I am going out on a limb here but I believe Berkshelf changed its behaviour with regards to how much 'value' it puts on the information it gets from supermarket.

This feels like it is related: https://github.com/berkshelf/berkshelf/issues/1377

**Comment by b-dean** [comment]
For the sake of this case, *there is no cookbook*. Just look at the `Berksfile` and resulting `Berksfile.lock` in my initial issue. There is no local anything for Berkshelf to prefer over the supermarket. It has one source of cookbooks, the supermarket. Just look at that lock file, it says it installed such that the dependency `'windows', '< 2'` is satisfied by the windows v2.0.2 cookbook. That's just incorrect

**Comment by Sauraus** [comment]
Ok sorry to waste your time, good luck as I am not sure what it could be then.

**Comment by lamont-granquist** [comment]
If you run `berks install` berkshelf wlll only read Berksfile.lock and will ignore the Berksfile.  If you update the Berksfile you have to regenerate the Berksfile.lock with `berks update`.

Its not clear to me if you're doing this or not, but this is the documented API, and is identically analogous to bundler / Gemfile / Gemfile.lock in the ruby world...

**Comment by lamont-granquist** [comment]
okay, i see the "windows (< 2.0.0)" in the Berksfile.lock

but i can't replicate that case, with that Berksfile i get '1.44.3' for the windows cookbook.

if i try to generate a Berksfile.lock with 2.0.2 selected in it and then add the constraint to the Berksfile and `berks install` i get this:

```
Berkshelf could not find compatible versions for cookbook 'windows':
  In Berksfile:
    windows (< 2.0.0)

  In Berksfile.lock:
    windows (2.0.2)

Try running `berks update windows`, which will try to find 'windows' matching '< 2.0.0'.
```

then running 'berks update` pins it back to 1.44.3 in the lockfile.

**Comment by lamont-granquist** [comment]
are you using the ruby resolver and could this be something like  #1607 ?

**Comment by b-dean** [comment]
@lamont-granquist, The `Berksfile.lock` in my original post is the result of doing the `berks install`. It did not exist before the install.

As for if I'm using the ruby resolver ... ¯\_(ツ)_/¯ ... I'm using whatever the default is. There is no `.berkshelf/config.json` involved. So, if that's the ruby resolver, then I'm using it; if not, then I'm not.

I created [b-dean/berkshelf-1616](https://github.com/b-dean/berkshelf-1616) with all the code I used to reproduce the error. I used Ruby 2.3.1 and my OS is Ubuntu 14.04.5, although I somehow doubt that matters.

**Comment by lamont-granquist** [comment]
yeah if you add `gem "dep_selector"` to your Gemfile (and wait a long time while dep_selector_libgecode is installed when you re-bundle) then I think it works?

**Comment by lamont-granquist** [comment]
```
 BERKSHELF_PATH=.berkshelf bundle exec berks install
Resolving cookbook dependencies...
Fetching cookbook index from https://supermarket.chef.io...
Using 7-zip (1.0.2)
Using bluepill (2.4.3)
Installing chef_handler (2.0.0)
Using compat_resource (12.14.7)
Using mercurial (2.0.4)
Using apt (2.9.2)
Using build-essential (2.4.0)
Using nginx (2.7.6)
Using ohai (2.1.0)
Using python (1.4.6)
Using packagecloud (0.2.5)
Using rsyslog (4.0.1)
Using runit (1.8.0)
Installing windows (1.44.3)
Using yum (4.0.0)
Using yum-epel (0.7.1)
```

**Comment by aburger11** [comment]
I ran into this issue myself today and did some digging. I believe this may be arising because of a [commit to the solve gem](https://github.com/berkshelf/solve/commit/f8f60746f9c9983e898889a7cc8b2cf1ef3b92a6), which bumped its molinillo gem requirement from ~> 0.2.3 to ~> 0.4.2.

In my cookbook's Gemfile I'm able to break/fix this by switching molinillo's version:
```
# gem 'molinillo', '= 0.2.3' #<- works
# gem 'molinillo', '~> 0.5.0' #<- works
# gem 'molinillo', '~> 0.4.0' #<- BREAKS!
```

**Comment by lamont-granquist** [comment]
this is working with at least berkshelf 5.2.0 and molinillo 0.5.4 and was some kind of upstream bug in molinillo

**Comment by chaim1221** [comment]
erm, same problem, `berks version` == 5.6.4. Wat?
