### ISSUE TITLE
berks vendor path duplicates cookbooks in berks cache folder

### ISSUE THREAD

**Issue by ghost** [berkshelf/berkshelf#1618]
Hi,
When we use 
berks vendor some_path 
berks download required cookbooks from repos/supermarket to some_path and duplicates them to folder:
~/.berkshelf/cookbooks/

How can we deprecate berks to cache cookbooks in folder
~/.berkshelf/cookbooks/

**Comment by lamont-granquist** [comment]
The cache is fairly fundamental to how berkshelf works, and currently there's no way to bypass it.  We might accept a PR to bypass the cache for vendoring cookbooks when given a flag or something, but we're unlikely to take on this work.  This might technically be a 'help wanted' ticket, but closing this as i suspect it is unlikely to be patched.
