### ISSUE TITLE
Berkshelf::Berksfile::vendor crashes if files contains unix sockets

### ISSUE THREAD

**Issue by esmil** [berkshelf/berkshelf#1627]
The FileUtils.cp_r call fails hard if it encounters any named unix sockets. This might happen if you're using kitchen-qemu to test a cookbook and you forgot to add the .kitchen directory to a chefignore file.

**Comment by lamont-granquist** [comment]
we might accept a PR that fixed this behavior, but otherwise the workaround here is the solution and .kitchen always needs to be chefignore'd as best practice
