### ISSUE TITLE
actor.rb:345:in `each': task was terminated (Celluloid::Task::TerminatedError)

### ISSUE THREAD

**Issue by lioramilbaum** [berkshelf/berkshelf#1633]
Randomly, I hit an error uploading cookbooks to the hosted chef server. To overcome it, I run my script again and again, till it works.
Any idea what is the root cause of this error?

/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each': task was terminated (Celluloid::Task::TerminatedError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:321:in `handle_crash'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:166:in `rescue in run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/uploader.rb:55:in `block (2 levels) in upload'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/uploader.rb:51:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/uploader.rb:51:in `block in upload'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/ridley-5.1.0/lib/ridley/client.rb:38:in `open'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/ridley-5.1.0/lib/ridley.rb:56:in `open'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf.rb:145:in `ridley_connection'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/uploader.rb:50:in `upload'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/uploader.rb:37:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/berksfile.rb:593:in `upload'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/cli.rb:208:in `upload'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/cli.rb:52:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/cli.rb:27:in `execute!'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.2.0/bin/berks:5:in `<top (required)>'
	from /usr/local/bin/berks:49:in `load'
	from /usr/local/bin/berks:49:in `<main>'

**Comment by bronzdoc** [comment]
This just happened to me  after `berks upload`

**Comment by lioramilbaum** [comment]
It might be a networking issue when uploading huge cookbook files.

**Comment by docwhat** [comment]
@lioramilbaum: I get this too, and the cookbook is small and the network is up.  I'm using chef-server 12.12.0

The only log message I see is:

```
==> /var/log/opscode/opscode-erchef/current <==
2017-02-06_19:23:33.38263 [error] {<<"method=GET; path=/organizations/myorg/cookbooks/mycookbook/7.2.6; status=404; ">>,"Not Found"}
```

Version 7.2.6 is the new cookbook version I'm trying to upload.

Is there a work-around for this?

**Comment by MaRuifeng** [comment]
I encountered this issue when `knife cookbook upload` command also failed due to connection issue to the Chef server (improperly configured port number in my case). It's gone after I resolved the issue. There are exceptions rising in `ridley_connection` as shown in the error log. So most likely it's a connection problem to the Chef server. Are you able to upload the cookbook via knife?

**Comment by docwhat** [comment]
In my case it was a server issue.  The message is cryptic: can it be improved? If not, hopefully the comment can help some one.

**Comment by gcristof** [comment]
what was your server issue? We're seeing this as well, and am trying to fix it.
Thanks!

**Comment by lioramilbaum** [comment]
As soon as I reduced the size of the cookbook. The issue was resolved.
