### ISSUE TITLE
Dependency resolution fails when referencing a cookbook which has a git-dependency

### ISSUE THREAD

**Issue by EugenMayer** [berkshelf/berkshelf#1634]
Assume we have a cookbook `parent` with a dependency on 

```
cookbook bestcookbook, git: github/super/duper
```

and assume, this cookbook also exists on supermarket.io under "bestcookbook".

When using berks package in `parent`, it uses the local Berksfile and things go well, the git repo is used to resolve the dependency, not the one from supermarket.io

------ 
It gets broken when we have a cookbook `child` referencing `parent` as a dependency

```
cookbook parent, git: somegit/parent
```

when packing now, the cookbook from supermarket is used, thus i have to add 

```
cookbook bestcookbook, git: github/super/duper
```

to my clients/Berksfile to enforce it. But thats not what we want, we want a proper dependency resolution.

Thanks

**Comment by joestump** [comment]
Last I knew Berkshelf didn't recusively look through `Berksfile`'s found in other dependencies.

**Comment by lamont-granquist** [comment]
Dup of many other tickets.  I'm trying to focus on making PolicyFile workflow better here, nobody will be working on fixing this in berkshelf.

**Comment by EugenMayer** [comment]
So berkshelf is more or less replaced by policyfile?
