### ISSUE TITLE
Berkshelf has issues when cookbooks are named after Supermarket cookbooks

### ISSUE THREAD

**Issue by joestump** [berkshelf/berkshelf#1637]
**I fully understand what is going on in this use case is not ideal. Just looking for a path forward.**

So we have some cookbooks in our monolithic Chef repository that share the same name as cookbooks in the Supermarket. I'm doing my best to refactor away from these cookbooks and, in part, trying to get Berkshelf up and running.

The problem seems to be that Berkshelf will ignore a local `path:` cookbook if one exists on Supermarket with the same name. So if the Supermarket version `datadog` depends on `yum` Berkshelf will attempt to resolve dependencies based on _it's_ `metadata.rb` rather than the locally vendored on.

Anyone else see this? Any workaround? This isn't entirely unrelated to #1625 only I'd like Berkshelf to defer to locally vendored cookbooks instead of Supermarket when there's a name conflict.

**Comment by joestump** [comment]
This is the error I keep getting:

```
/Users/josephstump/.gem/ruby/2.2.3/gems/solve-3.1.0/lib/solve/ruby_solver.rb:81:in `block in resolve': undefined method `name' for nil:NilClass (NoMethodError)
	from /Users/josephstump/.gem/ruby/2.2.3/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `each'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `inject'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `resolve'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/solve-3.1.0/lib/solve.rb:64:in `it!'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/berkshelf-5.2.0/lib/berkshelf/resolver.rb:78:in `resolve'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/berkshelf-5.2.0/lib/berkshelf/installer.rb:175:in `install_from_universe'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/berkshelf-5.2.0/lib/berkshelf/installer.rb:39:in `run'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/berkshelf-5.2.0/lib/berkshelf/berksfile.rb:422:in `install'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/berkshelf-5.2.0/lib/berkshelf/berksfile.rb:631:in `block in vendor'
	from /Users/josephstump/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/berkshelf-5.2.0/lib/berkshelf/berksfile.rb:629:in `vendor'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/berkshelf-5.2.0/lib/berkshelf/cli.rb:399:in `vendor'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/berkshelf-5.2.0/lib/berkshelf/cli.rb:52:in `dispatch'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/berkshelf-5.2.0/lib/berkshelf/cli.rb:27:in `execute!'
	from /Users/josephstump/.gem/ruby/2.2.3/gems/berkshelf-5.2.0/bin/berks:5:in `<top (required)>'
	from /Users/josephstump/.gem/ruby/2.2.3/bin/berks:23:in `load'
	from /Users/josephstump/.gem/ruby/2.2.3/bin/berks:23:in `<main>'
```

**Comment by joestump** [comment]
Okay, no idea what's going on. I switched over to `solver :gecode` and this somehow worked out upstream dependencies correctly. I then kept adding in local dependencies until `berks vendor /path/to/cookbooks` worked without incident. 

Going to close this for now with the following warning:

**Weird things might happen when `Berksfile.lock`, Supermarket, and `path:` cookbooks are out of sync.**

**Comment by StephenKing** [comment]
I am getting the same error when having two berkshelf endpoints (supermarket and ours) defined in `Berksfile`.
The only solution is to temporarily remove one of them. Gecode solver has unfortunately other issues, as well (runs endless when using to endpoints).

**Comment by oberones** [comment]
I'm seeing the same issue as @StephenKing when using the latest ChefDK on a Windows host. Commenting out on of the endpoints prevented the error, but not a real solution because it cant resolve the dependencies without both endpoints. I checked our local supermarket and the public and there are no duplicate cookbooks on either.

**Comment by StephenKing** [comment]
@joestump can you please re-open this? At least having some guidance how to fix one's setup would be helpful for me and probably others. Even better would be, if it works like it did before ;-)

**Comment by joestump** [comment]
I don't think I ever figured this particular issue out. I did run into an issue where basically Berkshelf won't work with `path:` if that cookbook shares a name with a Supermarket cookbook. 

This could possibly be causing the issue with two Berkshelf endpoints. I believe Supermarket always wins. I opened a bug on this but it was closed with basically, "Use Policy files. Berkshelf isn't going to get fixed."

So I ended up declaring bankruptcy on our old Chef setup and creating a single cookbook with _all_ dependencies listed in `metadata.rb` _except_ the few wherein I need it to go directly to GitHub. This basically means putting your usual dependencies in `metadata.rb` and then _not_ putting any dependencies that you need to get from somewhere other than Supermarket into your `Berksfile`.

I never have tried with > 1 source URLs so I'm not sure how they might related.

**Comment by StephenKing** [comment]
Yes, this also just happened to me.
