### ISSUE TITLE
berkshelf.com certificate mismatch

### ISSUE THREAD

**Issue by rjhornsby** [berkshelf/berkshelf#1647]
The TLS certificate for https://berkshelf.com is presenting itself as the wildcard cert for *.github.com, which results in a hostname mismatch and browsers calling the cert invalid.

```
$ curl -iv https://berkshelf.com
* Rebuilt URL to: https://berkshelf.com/
*   Trying 192.30.252.154...
* Connected to berkshelf.com (192.30.252.154) port 443 (#0)
...
* Server certificate:
* 	 subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.com
* 	 start date: Mar 23 00:00:00 2015 GMT
* 	 expire date: Mar 27 12:00:00 2017 GMT
* 	 subjectAltName does not match berkshelf.com
* SSL: no alternative certificate subject name matches target host name 'berkshelf.com'
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name 'berkshelf.com'
```
<img width="400" alt="screenshot 2016-12-14 14 13 03" src="https://cloud.githubusercontent.com/assets/5077610/21199594/c5e61af8-c209-11e6-9f67-07bf3dbc1775.png">

**Comment by LTangaF** [comment]
Just ran into this too when looking for Berkshelf docs. Having a bad certificate is one of the things that I use to avoid sites.

**Comment by lamont-granquist** [comment]
berkshelf.com has been replaced by https://docs.chef.io/berkshelf.html, nobody was maintaining the old berkshelf.com site.
