### ISSUE TITLE
Running this commend Kitchen converge i am getting error alreddy installed berkshelf

### ISSUE THREAD

**Issue by gopinath18** [berkshelf/berkshelf#1664]
Kitchen : >>>>>> ------Exception-------
At line:1 char:1
+ Kitchen converge
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (>>>>>> ------Exception-------:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Could not load or activate Berkshelf (Unable to activate berkshelf-5.5.0, because 
thor-0.19.4 conflicts with thor (< 0.19.2, ~> 0.19))
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by RafPe** [comment]
Hi @gopinath18 
had the same problem when playing around with gems. So what I have done is uninstalled the troublesome version by running 
```
gem uninstall thor 
```
and selecting that I would like to remove **thor-0.19.4**

Should work
