### ISSUE TITLE
berks vendor failing with berkshelf gem version 5.6.1

### ISSUE THREAD

**Issue by debashis1982** [berkshelf/berkshelf#1671]
Actually even version command fails:
/opt/chef/embedded/bin/berks --version

Here is the error:

/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- hashie/logger (LoadError)
	from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.1/lib/berkshelf.rb:4:in `<top (required)>'
	from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.1/lib/berkshelf/cli.rb:1:in `<top (required)>'

**Comment by lamont-granquist** [comment]
what version of chefdk and what version of hashie?

**Comment by debashis1982** [comment]
This is what I am doing :
Installing latest version of chef which is 12.18.31 
Using chef's ruby binaries to install berkshelf gem and then running berks vendor to download some cookbooks. I did not have to install hashie. Is that a dependency with the latest version of berkshelf?

**Comment by lamont-granquist** [comment]
its probably better to use chefdk that bundles berkshelf with chef to avoid these kinds of issues.

hashie should be getting installed by one of the berkshelf dependencies.  either its not getting installed or the version getting installed is too old, but i can't tell from the output.

**Comment by thomasv314** [comment]
I'm also experiencing this issue. 

My use case is a tad bit different:

- Using berkshelf v5.6.1 in a gem I maintain
- Gem gets mounted in applications where elasticsearch-persistence is used (which has hashie v3.4.3 as a dependency)
- `hashie/logger` doesn't exist in hashie v3.4.3
- LoadError is raised from `require 'berkshelf'`

I had created a branch and then noticed that #1673 already has a PR attached which fixes the issue.

**Comment by lamont-granquist** [comment]
so in general using berkshelf as a library leads to pain, and you should shell out and use berks on the command line to avoid dep conflicts caused by the diamond dependency issue.

test-kitchen uses berks as a library and i consider that a bug and need to fix it at some point to fork and exec berks instead.

but...

this is easy enough to fix...

**Comment by thomasv314** [comment]
duly noted! thanks for the swift reply.
