### ISSUE TITLE
List locked dependencies that are outdated with `berks outdated`

### ISSUE THREAD

**Issue by jeroenj** [berkshelf/berkshelf#1678]
If you call `berks outdated` now you get a list of dependencies that have new versions available that satisfy their constraints.

It would be handy if it also included (optionally) locked dependencies that have new versions available. We have repositories with locked dependencies where it would be handy if you get an overview of all outdated dependencies (including the locked ones). A bit like how `bundle outdated` works. But I understand that it should not be the default (or forced) behaviour. :)

**Comment by lamont-granquist** [comment]
would probably accept a PR, but this is unlikely to get done.
