### ISSUE TITLE
Berksfile.lock has the wrong file extension for its purpose

### ISSUE THREAD

**Issue by grv87** [berkshelf/berkshelf#1686]
See argumentation on the same issue for Bundler: https://github.com/bundler/bundler/issues/694

Bundler now supports `gems.rb` and `gems.locked`. I think that Berkshelf could do the same.

**Comment by lamont-granquist** [comment]
policyfiles uses `PolicyFile.rb` and `Policyfile.lock.json` for this reason.

while we agree in principle, we're not going to do this work for berkshelf.

if you care deeply about this, submitting a pull request so we can just hit merge would work (as long as it is fully backwards compat)
