### ISSUE TITLE
Berks Upload Fails (504 error) using a proxy with a port

### ISSUE THREAD

**Issue by HolyGeneralK** [berkshelf/berkshelf#1687]
Hello,
I am having an issue with Berks Upload failing due to the following error:

`ERROR -- : Ridley::Errors::ClientError: connect to ssl proxy failed with status 504 Unknown Host`

I am using a Windows 7 x64 with ChefDK 1.3.40 (chef client 12.19.36, berks 5.6.4). I have a corporate proxy that so far I have been working around using knife.rb parameters. The proxy has the form of http://theproxy.thecompany:port. 

A `berks install` works perfectly fine and can retrieve cookbooks from the Chef public supermarket without issue. The issue is only uploads to the chef server with Berks. Knife has no issues (but I'm not sure how to upload the dependency cookbooks through knife). 

I think the root cause of my issue (just from reading logs) is that the :port is being stripped from the proxy request. If you look at the log file, where it is requesting the proxy, it doesn't have any indication that the port is coming into play. 

```
DEBUG -- : ==> performing authenticated Chef request as 'me'
DEBUG` -- : request env: #<struct Faraday::Env method=:get, body=nil, url=#<Addressable::URI:0x2735ef8 URI:https://CHEFSERVER:443/organizations/foo/cookbooks/compat_resource/12.19.0>, request=#<Faraday::RequestOptions **proxy=#<Faraday::ProxyOptions uri=#<URI::HTTP http://THEPROXY.THECOMPANY>>>**, request_headers={"Accept"=>"application/json", "Content-Type"=>"application/json", "X-Chef-Version"=>"11.4.0", "User-Agent"=>"Ridley v5.1.0", "X-OPS-SIGN"=>"algorithm=sha1;version=1.0;", "X-OPS-USERID"=>"ME", "X-OPS-TIMESTAMP"=>"2017-04-18T20
:23:15Z", "HOST"=>"CHEFSERVER:443"}, ssl=#<Faraday::SSLOptions cert_store=#<OpenSSL::X509::Store:0x4e8b2c0 @verify_callback=nil, @error=nil, @error_string=nil, @chain=nil, @time=nil, @_httpclient_cert_store_items=["C:/opscode/chefdk/embedded/ssl/certs/cacert.pem"]
>>, parallel_manager=nil, params=nil, response=nil, response_headers=nil, status=nil>
ERROR -- : Ridley::Errors::ClientError: connect to ssl proxy failed with status 504 Unknown Host
E, ERROR -- : C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/responses.rb:29:in `value' 
```

I'm not sure if the problem is with Ridley, or if it's in the inputs to Ridley, and I'm trying to get a debugging environment setup to help out with the issue/develop a workaround. 

If I take the http_proxy setting out of of my knife.rb file and let powershell run with environment variables for the proxy, then I can work around it, but I will have other issues. 

Please let me know if I can provide additional input (all of which will have to be scrubbed, unfortunately, due to InfoSec requirements. 

I appreciate it!

**Comment by lamont-granquist** [comment]
ridley is gone as of berkshelf 7.0 so this bug will need to get revalidated against that version once its released and opened as a new issue if it still persists.
