### ISSUE TITLE
berks vendor to existing directory leaves files from older cookbook versions

### ISSUE THREAD

**Issue by acoulton** [berkshelf/berkshelf#1727]
If you `berks vendor` to a directory, then later update the cookbook version and `berks vendor` again, files that were removed from the newer cookbook are not deleted from the vendor directory.

This leaves the vendored cookbook in an inconsistent state, with a mix of files from old and new versions.

This can cause visible issues - eg library files from `mysql2_chef_gem` that were removed in 2.0 cause a fatal error with newer versions of chef.

Or, worse, it can cause hidden issues - eg deprecated recipes were removed from the `apache2` cookbook, but these will be present and continue to converge without warning if an older version has previously been vendored to the same location. The error will only appear the first time the dependencies are vendored to a clean directory.

## To reproduce

```bash
#!/bin/bash
set -o nounset
set -o errexit
TMPDIR="/tmp/bstest"
mkdir $TMPDIR
pushd $TMPDIR

echo "source 'https://supermarket.chef.io'" > ./Berksfile
echo "cookbook 'mysql2_chef_gem', '~>1.0'" >> ./Berksfile

echo "Vendor original cookbooks"
berks vendor ./vendor-cookbooks

ls -l ./vendor-cookbooks/mysql2_chef_gem/libraries
# Set custom mtime to make the no-change obvious
touch -t 199912310000 ./vendor-cookbooks/mysql2_chef_gem/libraries/z_provider_mapping.rb


# Update the dependency
# Remove the lockfile to simplify the reproduction case : its presence / absence
# doesn't make any difference.
rm ./Berksfile.lock
echo "source 'https://supermarket.chef.io'" > ./Berksfile
echo "cookbook 'mysql2_chef_gem', '~>2.0'" >> ./Berksfile

echo "Vendor updated cookbooks"
berks vendor ./vendor-cookbooks

ls -l ./vendor-cookbooks/mysql2_chef_gem/libraries
```

## Expected

The second file list contains only `matchers.rb` which is the only file under libraries/ in the 2.0 version of mysql2_chef_gem

## Actual

Other files from the 1.0 cookbook are still present and their modification times are unchanged - eg z_provider_mapping.rb

**Comment by lamont-granquist** [comment]
It looks like this strictly conflicts with everyone's wishes in #1400 who didn't want `berks vendor` to obliterate the target dir.  I tend to agree that in your workflow you should create a new / blank tmpdir and we should not blow away the target because if someone manages to do `berks vendor ~` or `berks vendor /` through a code bug they're potentially going to have a really shitty day.
