### ISSUE TITLE
SSL exception gives little diagnostic information

### ISSUE THREAD

**Issue by CVTJNII** [berkshelf/berkshelf#1731]
While attempting a "berks install' I'm getting the following error:

```
Using managed_directory (0.2.1)
/opt/chefdk/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
        from /opt/chefdk/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
<Snip many lines of trace>
```

This is not particularly notable in and of itself, however this error is a bit frustrating as it omits what server it is trying to connect to.  It's clearly trying to connect to a remote server and there is an issue trusting that SSL cert, however from the error I don't know what server it's trying to connect to and as such cannot easily troubleshoot the issue.

I would like to request that Berkshelf rescue these exceptions, add what server it's attempting to connect to to the exception message, and rethrow.  This would make troubleshooting much easier, and may cut down on SSL errors being reported as bugs which appears to happen with some regularity.  Thanks.

**Comment by lamont-granquist** [comment]
Since broken functionality will always queue starve superficial bugs like this, I'm going to close this issue rather than allowing any false hopes.  Pull requests to fix the issue would be accepted.
