### ISSUE TITLE
Plugin is broken in WSL after Windows 10 Fall Creators Update

### ISSUE THREAD

**Issue by poma** [berkshelf/berkshelf#1734]
When Ubuntu is installed from the App Store it gives the following error:

```
    homestead-7: /tmp/vagrant-chef/3c87ec80ba1f244bd8a309748dc7991f/cookbooks => /root/.berkshelf/vagrant-berkshelf/shelves/berkshelf20171022-18024-1spu6ki-homestead-7
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 v-csc-c77bf3bcf /tmp/vagrant-chef/3c87ec80ba1f244bd8a309748dc7991f/cookbooks

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: Protocol error
```

Which is likely caused by the fact that VirtualBox mounts 

```
\\?\C:\Users\Poma\AppData\Local\lxss\root\.berkshelf\vagrant-berkshelf\shelves\berkshelf20171022-18024-1spu6ki-homestead-7
```

folder which does not exist because now Windows supports multiple Linux installations and path to this folder is different

**Comment by poma** [comment]
For the reference the new location is

```
C:\Users\Poma\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs
```

But this may be different from other Linux distrbutions

**Comment by poma** [comment]
Temporary workaround - create a directory junction in the old location

```
mklink /J C:\Users\%username%\AppData\Local\lxss C:\Users\%username%\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs
```

Should be executed from elevated command prompt

**Comment by poma** [comment]
Maybe instead of trying to detect where new linux filesystem is located it is better to vendor cookbooks to `/mnt/c/Users/%username%/.berkshelf/....`? It is generally a bad practice to access WSL filesystem from within windows.

**Comment by thommay** [comment]
If you're talking about the vagrant berkshelf plugin, that is stored in a [separate repository](https://github.com/berkshelf/vagrant-berkshelf), and it's deprecated due to lack of maintainers. If you'd like to take a pass at fixing this, I'd be glad to merge a PR.

**Comment by poma** [comment]
Opps, indeed I intended to post this in vagrant plugin repo.
