### ISSUE TITLE
berkshelf no longer pulling in cookbook dependencies recursively with `depends`

### ISSUE THREAD

**Issue by haidangwa** [berkshelf/berkshelf#1738]
I think this is similar to #1404, except I can repro the issue with `depends` in my cookbook metadata. In our cookbook, we have a cookbook with dependencies on [chef-client 8.1.8](https://supermarket.chef.io/cookbooks/chef-client/versions/8.1.8) and [chef_client_updater 3.0.4](https://supermarket.chef.io/cookbooks/chef_client_updater/versions/3.0.4). Every cookbook that depends on our wrapper cookbook do not automatically pull in the dependencies of chef-client and chef_client_updater. This seemed to have recently changed.

To workaround this issue, we've had to add explicit cookbooks declared in Berkfile, like so:
```
# these dependencies are inherited from upstream;
# berkshelf no longer pulls them in recursively
%w[apt-chef chef_client_updater cron ubuntu windows].each do |cb|
  cookbook cb
end
```

Without these declared, chefspec will fail with the following error for each cookbook not declared:
```
================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Missing Cookbooks:
------------------
No such cookbook: windows

```

**Comment by xmik** [comment]
I am hitting this too.
```
$ berks --version
6.3.0
```

**Comment by xmik** [comment]
Those issues were helpful to find a solution:
   * https://github.com/berkshelf/berkshelf/issues/1723
   * https://github.com/berkshelf/berkshelf/issues/1728

I am no longer hitting this issue with `berkshelf 6.3.1` and its dependency: `solve 4.0.0`.

**Comment by lamont-granquist** [comment]
reasonably certain this was a dup of all the issues that drove solve 4.0.0
