### ISSUE TITLE
Berkshelf is building wrong dependency graph

### ISSUE THREAD

**Issue by vigri** [berkshelf/berkshelf#1743]
While creating myself cookbooks for learning purposes, I think I found a bug.

## Problem
Berkshelf is building wrong dependency graph

## Environment
```
chef --version
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

## How to reproduce
I've the following cookbooks (all are self-written).
The chef-recipes can be empty.

atlassian_crowd (0.1.0) ---- (depends) -- > apache2_proxy (0.1.0) ---- (depends) -->  apache2 (0.1.0)

1. apache2
**metadata.rb**
`nothing modified`
**Berksfile**
`nothing modified`

2. apache2_proxy
**metadata.rb** 
`depends 'apache2'`
**Berksfile**
```
# frozen_string_literal: true
source 'https://supermarket.chef.io'

cookbook 'apache2', path: '../apache2'

metadata
```

3. atlassian_crowd
**metadata.rb** 
`depends 'apache2_proxy'`
**Berksfile**
```
# frozen_string_literal: true
source 'https://supermarket.chef.io'

cookbook 'apache2_proxy', path: '../apache2_proxy'

metadata
```

Now when I run `kitchen test` the dependency graph inside Berksfile.lock is wrong:

```
DEPENDENCIES
  apache2_proxy
    path: ../apache2_proxy
  atlassian_crowd
    path: .
    metadata: true

GRAPH
  apache2 (5.0.1)
  apache2_proxy (0.1.0)
    apache2 (>= 0.0.0)
  atlassian_crowd (0.1.0)
    apache2_proxy (>= 0.0.0)
```

The first line in the graph should **not** be apache2 (5.0.1). Berkshelf is pulling the `apache2` cookbook from supermarket and not using the local one.

This is the Berksfile.lock for `apache2_proxy`:
```
DEPENDENCIES
  apache2
    path: ../apache2
  apache2_proxy
    path: .
    metadata: true

GRAPH
  apache2 (0.1.0)
  apache2_proxy (0.1.0)
    apache2 (>= 0.0.0)
```
This one is okay.

## What I tried to do
1. deleting the `Berksfile.lock` doesn't solve the problem. A new file appears with the same wrong graph
2. generated a new cookbook `test1` with command `chef generate cookbook test1` and modified `Berksfile` and `metadata.rb` - content as above

## Additional information
When I modify inside `atlassian_crowd`
**metadata.rb** 
```
depends 'apache2'
depends 'apache2_proxy'
```
**Berksfile**
```
# frozen_string_literal: true
source 'https://supermarket.chef.io'

cookbook 'apache2', path: '../apache2'
cookbook 'apache2_proxy', path: '../apache2_proxy'

metadata
```
The dependency graph has **no error**
```
DEPENDENCIES
  apache2
    path: ../apache2
  apache2_proxy
    path: ../apache2_proxy
  atlassian_crowd
    path: .
    metadata: true

GRAPH
  apache2 (0.1.0)
  apache2_proxy (0.1.0)
    apache2 (>= 0.0.0)
  atlassian_crowd (0.1.0)
    apache2 (>= 0.0.0)
    apache2_proxy (>= 0.0.0)
```

Please let me know if you need further information.

Best regards

**Comment by thommay** [comment]
This is berkshelf behaving correctly - It does not check berksfiles in other cookbooks, just the data you provide in `metadata.rb`, which is all that's available on the chef server.

**Comment by vigri** [comment]
Thanks for your reply @thommay 

So there's right now no way to realize such a structure of cookbooks?

**Comment by thommay** [comment]
With berkshelf? no. With [policyfiles](https://docs.chef.io/policyfile.html), yes - you can specify in the policy that your preferred source is your path, and then use supermarket as a fall back.
