### ISSUE TITLE
berks apply fails with 405

### ISSUE THREAD

**Issue by kitchen** [berkshelf/berkshelf#1794]
I'm trying to `berks apply` against hosted chef and getting a 405 error message:

```
--- Development/dreamground ‹master› » berks apply _default
E, [2018-08-18T19:45:06.468991 #20718] ERROR -- : Net::HTTPServerException: 405 "Method Not Allowed"
E, [2018-08-18T19:45:06.469101 #20718] ERROR -- : /opt/chefdk/embedded/lib/ruby/2.5.0/net/http/response.rb:122:in `error!'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/http.rb:152:in `request'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/http.rb:123:in `put'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/environment.rb:275:in `save'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.4/lib/berkshelf/lockfile.rb:224:in `block in apply'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.4/lib/berkshelf/ridley_compat.rb:54:in `new_client'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.4/lib/berkshelf.rb:172:in `ridley_connection'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.4/lib/berkshelf/lockfile.rb:215:in `apply'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.4/lib/berkshelf/cli.rb:221:in `apply'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.4/lib/berkshelf/cli.rb:47:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.4/lib/berkshelf/cli.rb:23:in `execute!'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.4/bin/berks:5:in `<top (required)>'
/usr/local/bin/berks:272:in `load'
/usr/local/bin/berks:272:in `<main>'
There was an error connecting to the Chef Server
```

In my searching, it seems that PUT is no longer a supported method. https://github.com/chef/chef-zero/issues/29 / https://tickets.opscode.com/browse/CHEF-4435

The offending code is in chef proper: https://github.com/chef/chef/blob/9c14c5838c02c4ff889d2f48b1b191ad2cac0b51/lib/chef/environment.rb#L273-L281

Relevant versions:
```
Chef Development Kit Version: 3.1.0
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.1.72
```

**Comment by praste** [comment]
I am also having the same issue.

**Comment by lamont-granquist** [comment]
those old issues are unrelated since they're about data bags, this is about environments.  and the code in chef/chef looks correct, if chef-server doesn't support puts on environments that is bizzare, and `knife environment from file` calls save and would similarly call put and should have been broken.

**Comment by lamont-granquist** [comment]
from the chef-zero code it looks like put is supported, but modifying the `_default` environment is not supported:

https://github.com/chef/chef-zero/blob/master/lib/chef_zero/endpoints/environment_endpoint.rb#L20

if that's what you're doing, you need to use a different environment name.

if that's not what you're trying to do, then we need a lot more information about what you're doing, what the environment looks like, ideally some full debug output from `-d`, etc.

**Comment by lamont-granquist** [comment]
oh yeah that is what you're trying to do:  "berks apply _default"

i think the solution is to use any other environment name other than "_default"
