### ISSUE TITLE
Berkshelf does not work on FIPS enabled machines

### ISSUE THREAD

**Issue by frezbo** [berkshelf/berkshelf#1802]
One a FIPS enabled machine, using `berkshelf` fails

```
[frezbo@localhost berks_test]$ bundle exec berks install  --debug
I, [2018-11-30T12:37:26.644226 #2206]  INFO -- : Reducing lockfile
D, [2018-11-30T12:37:26.644343 #2206] DEBUG -- : Current lockfile:
D, [2018-11-30T12:37:26.644383 #2206] DEBUG -- : 
D, [2018-11-30T12:37:26.644477 #2206] DEBUG -- :   DEPENDENCIES
D, [2018-11-30T12:37:26.644514 #2206] DEBUG -- :     java
D, [2018-11-30T12:37:26.644546 #2206] DEBUG -- :   
D, [2018-11-30T12:37:26.644578 #2206] DEBUG -- :   GRAPH
D, [2018-11-30T12:37:26.644609 #2206] DEBUG -- :     homebrew (5.0.8)
D, [2018-11-30T12:37:26.644638 #2206] DEBUG -- :     java (3.1.1)
D, [2018-11-30T12:37:26.644661 #2206] DEBUG -- :       homebrew (>= 0.0.0)
D, [2018-11-30T12:37:26.644684 #2206] DEBUG -- :       windows (>= 0.0.0)
D, [2018-11-30T12:37:26.644732 #2206] DEBUG -- :     windows (5.2.2)
D, [2018-11-30T12:37:26.644762 #2206] DEBUG -- : 
D, [2018-11-30T12:37:26.644792 #2206] DEBUG -- : Unlocking dependencies no longer in the Berksfile
D, [2018-11-30T12:37:26.645520 #2206] DEBUG -- :   Checking java (3.1.1)
D, [2018-11-30T12:37:26.645568 #2206] DEBUG -- :     Skipping unlock for java (exists in the Berksfile)
D, [2018-11-30T12:37:26.645599 #2206] DEBUG -- : Removing transitive dependencies
D, [2018-11-30T12:37:26.645636 #2206] DEBUG -- :   Checking java (>= 0.0.0)
RuntimeError Unsupported digest algorithm (MD5).
	/usr/share/ruby/openssl/digest.rb:40:in `initialize'
	/usr/share/ruby/openssl/digest.rb:40:in `block (3 levels) in <class:Digest>'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/digester.rb:53:in `new'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/digester.rb:53:in `generate_md5_checksum_for_file'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/digester.rb:49:in `generate_md5_checksum_for_file'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook_version.rb:80:in `checksum_cookbook_file'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook_manifest.rb:307:in `checksum_cookbook_file'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook_manifest.rb:238:in `block in generate_manifest'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook_manifest.rb:233:in `each'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook_manifest.rb:233:in `generate_manifest'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook_manifest.rb:104:in `manifest'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook_manifest.rb:175:in `files_for'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook_version.rb:177:in `fully_qualified_recipe_names'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook/metadata.rb:374:in `recipes_from_cookbook_version'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook_version.rb:154:in `metadata='
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook/cookbook_version_loader.rb:100:in `block in cookbook_version'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook/cookbook_version_loader.rb:98:in `tap'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/chef-14.7.17/lib/chef/cookbook/cookbook_version_loader.rb:98:in `cookbook_version'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cached_cookbook.rb:75:in `cookbook_version'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cached_cookbook.rb:83:in `metadata'
	/usr/share/ruby/forwardable.rb:223:in `cookbook_name'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cached_cookbook.rb:61:in `initialize'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cached_cookbook.rb:39:in `new'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cached_cookbook.rb:39:in `from_path'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cached_cookbook.rb:20:in `from_store_path'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cookbook_store.rb:89:in `cookbook'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/dependency.rb:138:in `cached_cookbook'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/lockfile.rb:438:in `block in reduce!'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/lockfile.rb:419:in `each'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/lockfile.rb:419:in `reduce!'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/installer.rb:35:in `run'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/berksfile.rb:405:in `install'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cli.rb:131:in `install'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cli.rb:47:in `dispatch'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cli.rb:23:in `execute!'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/gems/berkshelf-7.0.6/bin/berks:5:in `<top (required)>'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/bin/berks:23:in `load'
	/home/frezbo/berks_test/vendor/bundle/ruby/2.5.0/bin/berks:23:in `<top (required)>'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/home/frezbo/.gem/ruby/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
	/home/frezbo/bin/bundle:23:in `load'
	/home/frezbo/bin/bundle:23:in `<main>'
[frezbo@localhost berks_test]$ 
```

**Comment by frezbo** [comment]
More info:

```
[frezbo@localhost berks_test]$ ruby -e "require 'openssl'; puts OpenSSL.fips_mode"
true
[frezbo@localhost berks_test]$ ruby -e "require 'openssl'; puts OpenSSL::OPENSSL_VERSION"
OpenSSL 1.1.1 FIPS  11 Sep 2018
[frezbo@localhost berks_test]$ ruby -e "require 'openssl'; puts OpenSSL::OPENSSL_FIPS"
true
[frezbo@localhost berks_test]$ 
[frezbo@localhost berks_test]$ 
[frezbo@localhost berks_test]$ /opt/chefdk/embedded/bin/ruby -e "require 'openssl'; puts OpenSSL.fips_mode"
false
[frezbo@localhost berks_test]$ /opt/chefdk/embedded/bin/ruby -e "require 'openssl'; puts OpenSSL::OPENSSL_VERSION"
OpenSSL 1.0.2p  14 Aug 2018
[frezbo@localhost berks_test]$ /opt/chefdk/embedded/bin/ruby -e "require 'openssl'; puts OpenSSL::OPENSSL_FIPS"
true
[frezbo@localhost berks_test]$
```

seems chef dk uses a non-FIPS version of OpenSSL

**Comment by lamont-granquist** [comment]
You need to set the config.rg value `fips` to true (and you cannot use berkshelf's config.json which will get deprecated)

**Comment by frezbo** [comment]
@lamont-granquist Am I doing it wrong:

```
[frezbo@localhost berks_test]$ /opt/chefdk/embedded/bin/ruby -e "require 'openssl'; puts OpenSSL.fips_mode"
false
[frezbo@localhost berks_test]$ cat ~/.chef/knife.rb 
fips=true
[frezbo@localhost berks_test]$ cat ~/.chef/config.rb 
fips=true
[frezbo@localhost berks_test]$ bundle exec berks
RuntimeError Unsupported digest algorithm (MD5).
[frezbo@localhost berks_test]$ 

```
Still getting the error

**Comment by frezbo** [comment]
@lamont-granquist Seems when executing `berks` standalone `Chef::Config.init_openssl` is never called which fails to set fips mode.

**Comment by lamont-granquist** [comment]
nifty, okay that's a legit bug then

**Comment by lamont-granquist** [comment]
does #1803 fix you?

**Comment by frezbo** [comment]
@lamont-granquist #1803 still doesn't fix the issue, getting new FIPS error now:


```
[ec2-user@ip-10-17-142-203 berkshelf]$ bundle exec bin/berks -b /tmp/Berksfile 
Resolving cookbook dependencies...
Fetching cookbook index from https://supermarket.chef.io...
md5_dgst.c(82): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!
Aborted
[ec2-user@ip-10-17-142-203 berkshelf]$
```

**Comment by frezbo** [comment]
@lamont-granquist https://github.com/chef/chef/blob/master/chef-config/lib/chef-config/config.rb#L1132, this is wrong usage, on ruby compiled with OpenSSL FIPS `Digest::MD5` would also not work.

```
[ec2-user@ip-10-17-142-203 berkshelf]$ irb
2.4.4 :001 > require 'digest'
 => true 
2.4.4 :002 > Digest::MD5.new
md5_dgst.c(82): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!
Aborted
[ec2-user@ip-10-17-142-203 berkshelf]$ 
```

**Comment by frezbo** [comment]
Ref: https://github.com/chef/chef/issues/8009

**Comment by lamont-granquist** [comment]
i think that line of code is only forcefully defining the ruby constant.

https://github.com/chef/chef/blob/master/lib/chef/cookbook_version.rb#L77-L84

that seems to be the root of the problem, which is that we always use MD5 for cookbook checksums, which makes me not understand how we can have a fips-compliant chef-client build at all.

**Comment by lamont-granquist** [comment]
hmm didn't mean to close this yet, but really it should move over to #chef/chef#8009

**Comment by lamont-granquist** [comment]
Does berkshelf in fips mode work (with the fix in #1803) from an omnibus-chefdk install?

Because it is possible that for our fips mode to work correctly it may be tightly coupled to how our omnibus rubies are built, and may not work on a hand-built ruby (like it kind of looks like you're using).

Although if `knife cookbook upload` does work then that might indicate a problem where the hacky rewriting of the OpenSSL const in chef is being overwritten by berkshelf calling `require "openssl"` somewhere lazily later.

The third option is that something happened in ruby to block our clever workaround and fips mode is globally broken.

**Comment by lamont-granquist** [comment]
yeah i suspect your ruby is compiled with "-DMD5_USE_OPENSSL"?  i'm not able to replicate either on my rvm based ruby or on the omnibus chefdk ruby.

**Comment by frezbo** [comment]
@lamont-granquist Let me give full context:

- All chefdk embedded binaries work fine, even before the FIPS fix #1803 (The `berks` file in chefdk calls `berkshelf` in a very different way)
- Seems you are right where `berkshelf` lazily does `require 'openssl'`, I see in it some places.
- Regarding ruby the OS is a standard STIGGED RHEL 7 machine with ruby installed with RVM (It uses system openssl. `rvm install 2.4`.)

I will try to remove the `require 'openssl'`, and let you know the results.

**Comment by frezbo** [comment]
@lamont-granquist removing `require 'openssl'` from the berkshelf still seems not to have solved the issue as it still calls `Digest::MD5` for any `OpenSSL::Digest::MD5` which would still fail.

**Comment by robbkidd** [comment]
Berkshelf is only really supported as a component of ChefDK and Chef Workstation. If it's working as a part of one of those installs, that's the result of the Central Yak Shaving processes in place to produce a working install, to include FIPS builds.

Regarding MD5, [chef-config redefines `OpenSSL::Digest::MD5`](https://github.com/chef/chef/blob/master/chef-config/lib/chef-config/config.rb#L1132) to use the Ruby standard library's MD5. During an audit of Chef code for its initial FIPS-spirit-of-the-law release, it was demonstrated that Chef does not use MD5 for crypto for secrets management, only for checksumming data, so this use was allowed.

> still calls `Digest::MD5` for any `OpenSSL::Digest::MD5` which would still fail

**Comment by frezbo** [comment]
@robbkidd as per the first snippet, `berks` fails when using with `bundler` on a FIPS enabled host with ruby compiled against system `openssl`. The `Digest::MD5` is not allowed on openssl. This is on a latest RHEL7 ec2 instance with FIPS enabled. Anything more I can do to help?

**Comment by lamont-granquist** [comment]
Yeah I think the point is that we can't support fips mode against the distro ruby in RHEL7.  It has to be run against omnibus-chef/chefdk ruby builds.

**Comment by robbkidd** [comment]
I'll confirm. I've been wrestling with FIPS recently, so have test host's available.

**Comment by frezbo** [comment]
I agree with @lamont-granquist and @robbkidd that this only works with omnibus ruby, not the system ruby. We are mostly using Berks as a library and the FIPS mode causes it to fail. I'm currently forced to monkey-patch the berks code to set `OpenSSL.fips_mode = false` just for any `Berkshelf` API and re-enable it back later. I'm happy to provide any debug info or help in fixing the code base not to use MD5.

**Comment by frezbo** [comment]
Closing in favor of https://github.com/chef/chef/issues/8009

**Comment by frezbo** [comment]
@lamont-granquist Can you release a version with #1803 fix?

**Comment by frezbo** [comment]
@robbkidd / @lamont-granquist Can we have a new release please?

**Comment by caarlos0** [comment]
Hi!

I think I have a similar issue.

I have a jenkins instance which runs several jobs (yeah, I know that the start of this story is already bad), some of them call chef, berks and etc.

We already had a very weird issue related to kitchen docker driver and the container naming, which we worked around without understanding what's happening. [+info](https://stackoverflow.com/questions/49035866/very-strange-behaviour-with-ruby-openssl-unicorn-systemd-gcloud)

Anyway, when we start jenkins through systemd and run a job that calls berks, it fails with the same error (`Unsupported digest algorithm (MD5)`).

Weirdly enough, if I just run the same java cmd line outside systemd, it works.

I spent the entire morning trying to figure this out, eventually gave up and now have jenkins running in a `screen` session.

I can give you any details you need, if it somehow helps... I can also open a new issue, but I guess that maybe the patch on #1803 helps this too... 


---

FWIW:

```
[Pipeline] { (debug)
[Pipeline] sh
+ openssl version
OpenSSL 1.0.2q  20 Nov 2018
[Pipeline] sh
+ ruby -ropenssl -e p OpenSSL::OPENSSL_VERSION
"OpenSSL 1.0.2q  20 Nov 2018"
[Pipeline] sh
+ ruby -ropenssl -e p OpenSSL::X509::DEFAULT_CERT_FILE
"/opt/chefdk/embedded/ssl/cert.pem"
```

Its a ubuntu 16.04 running on GCP.

Happy to give more info and/or try whatever you think may help.

Cheers!

**Comment by robbkidd** [comment]
Hi, @caarlos0!

Because your digest error is not specifically `OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!`, it is likely not a FIPS-related problem. I am confident the fix in #1803 that [enables FIPS-mode](https://github.com/chef/chef/blob/28a0dfcd332cffebdf92f897dfe3729ec482a0d5/chef-config/lib/chef-config/config.rb#L586-L590) would not resolve the systemd-running-Jenkins-running-Chef problem.

I recommend posting the information you provided here to [the mailing list/forum](https://discourse.chef.io/c/chef) where folks can maybe help suss out what is different about the runtime environment of the systemd-spawned Jenkins process and your shell. You can also find helpful people in [the Chef Community Slack](http://community-slack.chef.io/). (But posts and answers to the mailing list are durable.)

**Comment by frezbo** [comment]
@robbkidd `Unsupported digest algorithm (MD5)` is actually an OpenSSL error. On machines with latest openssl like Fedora 29 with FIPS, openssl throws this error when trying to use `MD5`, rather than: `OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!`

**Comment by caarlos0** [comment]
> Hi, @caarlos0!
> 
> Because your digest error is not specifically `OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!`, it is likely not a FIPS-related problem. I am confident the fix in #1803 that [enables FIPS-mode](https://github.com/chef/chef/blob/28a0dfcd332cffebdf92f897dfe3729ec482a0d5/chef-config/lib/chef-config/config.rb#L586-L590) would not resolve the systemd-running-Jenkins-running-Chef problem.
> 
> I recommend posting the information you provided here to [the mailing list/forum](https://discourse.chef.io/c/chef) where folks can maybe help suss out what is different about the runtime environment of the systemd-spawned Jenkins process and your shell. You can also find helpful people in [the Chef Community Slack](http://community-slack.chef.io/). (But posts and answers to the mailing list are durable.)

oh yeah, I posted here and was then reading the code, found out it won't help but forgot to feedback here, sorry. 

Will try that out, thanks!

**Comment by caarlos0** [comment]
> @robbkidd `Unsupported digest algorithm (MD5)` is actually an OpenSSL error. On machines with latest openssl like Fedora 29 with FIPS, openssl throws this error when trying to use `MD5`, rather than: `OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!`

yeah, I'm using chefdk distribution and it seems ruby is getting the right openssl and etc (which comes with chefdk)... systemd is probably doing something funky somehow...

**Comment by robbkidd** [comment]
> `Unsupported digest algorithm (MD5)` is actually an OpenSSL error. On machines with latest openssl like Fedora 29 with FIPS, openssl throws this error when trying to use `MD5`, rather than: `OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!`

Well, that's cool. 😐 Noted. Thanks for the extra information, @frezbo!
