### ISSUE TITLE
Should Berksfile.lock be checked into version control?

### ISSUE THREAD

**Issue by FooBarWidget** [berkshelf/berkshelf#1819]
Different people I've spoken to disagree about whether Berksfile.lock should be checked into version control. Is there an official best practice surrounding this topic?

My opinion is that yes, Berksfile.lock should be in version control, in order to make `berks install` reproducible (i.e. the same reason why Gemfile.lock, package-lock.json, etc should be checked into version control).

But I'm wondering what the Berkshelf authors think?

**Comment by reset** [comment]
Yes, the `Berksfile.lock` is intended to be committed to version control

**Comment by FooBarWidget** [comment]
Thanks for the answer.
