### ISSUE TITLE
berks upload is not respecting --skip-syntax-check

### ISSUE THREAD

**Issue by vsingh-msys** [berkshelf/berkshelf#1835]
berks upload option `--skip-syntax-check` is not respecting. it always raises ruby syntax error while attempting to upload the cookbook.

```
berks upload -d --skip-syntax-check
I, [2020-01-26T08:12:26.985128 #19150]  INFO -- : Checking if lockfile is trusted
D, [2020-01-26T08:12:26.985191 #19150] DEBUG -- : Checking aix (>= 0.0.0)
D, [2020-01-26T08:12:27.090163 #19150] DEBUG -- :   Detected there is a cached cookbook
D, [2020-01-26T08:12:27.090346 #19150] DEBUG -- :   Checking transitive dependencies for aix (2.3.2)
I, [2020-01-26T08:12:27.105407 #19150]  INFO -- : Uploading cookbooks
D, [2020-01-26T08:12:27.105460 #19150] DEBUG -- :   No names given, using all cookbooks
D, [2020-01-26T08:12:27.105484 #19150] DEBUG -- :   Looking up dependencies for aix
I, [2020-01-26T08:12:27.106577 #19150]  INFO -- : Starting upload
D, [2020-01-26T08:12:27.136855 #19150] DEBUG -- :   Uploading aix
[2020-01-26T08:12:27+05:30] FATAL: Cookbook file recipes/nim_master_setup.rb has a ruby syntax error:
```

**Comment by vsingh-msys** [comment]
In order to fix this issue we can think of the following way:

1. Add the required changes so that it can honor the `--skip-syntax-check`.

OR

2. Remove `--skip-syntax-check` option and enforce the user to fix all ruby syntax errors. As `cookstyle` majorly for this purpose so that the user should follow best practices.

@tas50 & @lamont-granquist any comments?

**Comment by lamont-granquist** [comment]
removing skipping it would be a breaking change.

there's probably reasons that people would use that because people do crazy things with their cookbooks and the syntax checking may be too strict (particularly non-ruby files in attributes directories and other things that i've encountered -- they expect to be able to throw a json file in there and JSON.parse() and stuff like that)

**Comment by vsingh-msys** [comment]
Yes, this could happen, thanks for pointing it out.

**Comment by Vasu1105** [comment]
Somehow I don't feel its good to not check syntax errors in ruby files and skip those. The question is, Will keeping any syntax unchecked in ruby files will execute those file correctly ? And currently its failing when the call goes to Chef to upload_cookbooks and it https://github.com/chef/chef/blob/master/lib/chef/cookbook_uploader.rb#L50
https://github.com/chef/chef/blob/master/lib/chef/cookbook_uploader.rb#L146
