### ISSUE TITLE
berks install not working as expected

### ISSUE THREAD

**Issue by samratBasra** [berkshelf/berkshelf#1849]
Hi all. I am trying to learn Chef, but i got this issue with "berks install". Any help would be appricaited.

Resolving cookbook dependencies...
Fetching 'cms' from source at .
Fetching cookbook index from http://local-berkshelf-server.com...
Unable to satisfy constraints on package chef_version, which does not exist, due to solution constraint (cms = 0.0.0). Solution constraints that may result in a constraint on chef_version: [(cms = 0.0.0) -> (chef_version ~> 12.4.0)]
Missing artifacts: chef_version
Demand that cannot be met: (cms = 0.0.0)
Unable to find a solution for demands: cms (0.0.0)

Here is my metadata.rb:

name             'cms'
maintainer       'xxxxxxxx'
maintainer_email 'xxxxxxxxxxxxxxxxxxx'
license          'Do what ever ya want!'
description      'Installs xxxxxx'
long_description 'Installs xxxxx'
version          "#{ENV['BUILD_NUMBER'] || '0.0.0'}"
depends			 'chef_version', '~> 12.4.0'
depends			 'windows', '=2.0.2'
depends			 'mrgreen-windows'
depends			 'mrgreen-nuget'
depends			 'apt', '~> 7.3.0'
depends			 'mrgreen-apt', '~> 0.2.85'

here is my Berksfile:
source "local-berkshelf-server.com"

metadata

**Comment by rmoriz** [comment]
invalid. Please read the error message. Your private cookbook 'chef_version' is not available on your server.
