### ISSUE TITLE
Include Gem dependency lock inside Berksfile.lock

### ISSUE THREAD

**Issue by aminclip** [berkshelf/berkshelf#1860]
## Description

If cookbooks metadata.rb can contain gem dependencies, why Berksfile.lock doesn't lock gems version. Those are part of cookbooks.

## Berkshelf Version

Any version. 

## Platform Version

Any platform.

## Replication Case

Run `berks vendor cookbooks` on a cookbook that depends on one or multiple gems. It generates `Berksfile.lock` which doesn't contain any gem dependency tree.
## Berks Output

```
A `Berksfile.lock` file without gem dependencies.
```

## Stacktrace

None.

**Comment by lamont-granquist** [comment]
gem declarations in the metadata.rb are discouraged and may be deprecated, they have poor edge conditions and should not be used.

development of features on berkshelf is also not supported, that would be a better feature request for policyfiles.
