### ISSUE TITLE
`berks package` 7.2 adds the temporary file path to the resulting tar file on macOS

### ISSUE THREAD

**Issue by twasink** [berkshelf/berkshelf#1861]
## Description
When you run `berks package` on a Mac (running BigSur, anyway), the resulting `cookbooks.tar.gz` has the full path to the temp folder included. As such, it can not be installed on a server.

## Berkshelf Version
This is a regression in 7.2.0; it works fine in 7.1.0

## Platform Version
macOS 11.2.1, Ruby 2.6.0

## Replication Case

Run `berks _7.2.0_ package cookbooks.tar.gz` and inspect the contents of the output.

## Berks Output

Heres the output for v7.10 and v7.20 respectively

```
#### HAPPY CASE; V7.1.0
$ berks _7.1.0_ package cookbooks.tar.gz 

Cookbook(s) packaged to [redacted]/chef_cookbook/cookbooks.tar.gz

$ tar tvf cookbooks.tar.gz | head -n 1  
drwxr-xr-x  0 501    20          0  5 Mar 10:28 cookbooks

#### SAD CASE; V7.2.0
$ berks _7.2.0_ package cookbooks.tar.gz

Cookbook(s) packaged to [redacted]/chef_cookbook/cookbooks.tar.gz

$ tar tvf cookbooks.tar.gz | head -n 1  
drwxr-xr-x  0 501    20          0  5 Mar 10:29 /var/folders/hj/dzrhw5790p9_5818m3qj6b680000gn/T/d20210305-58302-1t4elw4/cookbooks
```

**Comment by twasink** [comment]
At a guess, I'd say it was this change, which took out the use of 'chdir' to make the tar get made from inside the temp directory.

https://github.com/berkshelf/berkshelf/commit/3634ce389f456e59113c0b740388d8488eafeb12#diff-2a8c7e74c8bee8af57470c02681fbe1e1d51041fffdb929eb1214a410d5e0b13

**Comment by inopinatus** [comment]
duplicate of #1857; my PR at #1858 has a possible fix, and I'll leave https://github.com/inopinatus/berkshelf/tree/relative_path_archive available until there's a gem release with resolution.

**Comment by twasink** [comment]
Yep; it's a duplicate.
