### ISSUE TITLE
empty cookbook files after Docker update

### ISSUE THREAD

**Issue by eireneapostol** [berkshelf/berkshelf#1865]
Recently, across our company everyone started experiencing the same issue.
When vendoring the dependencies, the cookbook we vendor the dependencies for has empty files ( 0 bytes ). All the other dependencies, that are installed from supermarket are fine.
There are no errors while vendoring.

Docker Desktop version `3.1.0` , 
CLI `Docker version 20.10.6`,
Berks `7.1.0` and `7.2.0`
MacOS `10.14.6` but tested with various MacOS versions
OS in Docker `CentOS Linux release 7.9.2009`

```Resolving cookbook dependencies...  
Fetching 'our_cookbook' from source at .  
Fetching cookbook index from https://our-artifactory/artifactory/api/chef/chef-supermarket...
Using our_cookbook (1.0.0) from source at .
Vendoring our_cookbook (1.0.0) to /home/user/our_cookbook
```

When testing with Docker Desktop `2.3.0.2` and CLI version `19.03.8` it works as expected.
Also, after browsing the internet, I tried unchecking in Docker preferences `Use gRPC FUSE for file sharing` and used the legacy osxfs files sharing instead, but didn't solve the problem.

**Comment by gmoreira** [comment]
Did you find a solution to this @eireneapostol?

**Comment by tas50** [comment]
The workaround has been merged to master and I'm about to ship the fix
