### ISSUE TITLE
Berks update does not update cookbook to latest version.

### ISSUE THREAD

**Issue by zsxking** [berkshelf/berkshelf#273]
I was having 

```
depends "artifact", "~> 0.10.7"
```

in my `metadata.rb`

When I do `berks update`, nothing updated. 

Then I try to change the line to 

```
depends "artifact"
```

and update, still nothing.

Then I change the line to 

```
depends "artifact", "~> 0.11.5"
```

Berks update finally picking up the new version and its dependencies.

**Comment by araza142** [comment]
berks upload --force

**Comment by peterhel** [comment]
I made a shell script to solve this issue since I can't find any berks blog posts after 2013.

`npm i -g berks-update`
