### ISSUE TITLE
Vagrant 1.1 Support

### ISSUE THREAD

**Issue by skorfmann** [berkshelf/berkshelf#416]
I'm trying to setup this with the recently release Vagrant 1.1. It doesn't seem to work properly. 

Is there a known way to make it work?

**Comment by lodotek** [comment]
@chulkilee  - the link you posted returns a 404.
I am having the same issue as @milosgajdos83 .

**Comment by chulkilee** [comment]
Looks like it is moved to berkshelf/vagrant-berkshelf#6
