### ISSUE TITLE
Berkshelf uses old versions of cookbooks even when new ones are available

### ISSUE THREAD

**Issue by mconigliaro** [berkshelf/berkshelf#781]
I have a `Berksfile` that looks like this:

```
chef_api :config
site :opscode

cookbook 'foo', '~> 0.1.0'
```

The `foo` cookbook has a Berksfile that looks like this:

```
chef_api :config
site :opscode

cookbook 'bar', '~> 0.1.0'
```

When I push a minor update to the `bar` cookbook (e.g. bringing it to version 0.1.1), I find that Berkshelf is content to continue using 0.1.0, even though 0.1.1 is available. 

My first thought was that I just needed to run `berks update` to update my `Berksfile.lock`, but I found that the old version continued to be used. As an experiment, I tried manually updating `Berksfile.lock` with the newer version, but I found that `berks install` rewrote my `Berksfile.lock` with the old version again. Finally, I tried deleting the old cookbook from the shelf. This worked, and was the only way I could find to force Berkshelf to download the newer version. 

Is this the expected behavior? My understanding (at least when it comes to Ruby gems) is that the `update` command is supposed to update your lock file with the newest versions it's allowed to use according to your version constraints. With a constraint on `bar` for `~> 0.1.0`, my assumption was that `berks update` would have seen that the newer `0.1.1` was available and satisfies the constraint, so it should have used that one instead. Or am I missing something?

**Comment by pritibiyani** [comment]
We are facing similar issue and my berks version is `5.3.6`
