### ISSUE TITLE
Allow one to "berks apply" to a json environment file

### ISSUE THREAD

**Issue by cjerdonek** [berkshelf/berkshelf#875]
Currently, `berks apply` lets you apply the cookbook version information in `Berksfile.lock` to an environment in Chef server.  This issue is to let you do the same to a json environment file (i.e. a file of the form you get from `knife environment show ENV -F json`).

Doing this would give users a way to store in source control the state of the environment hash after uploading the new cookbook environment data.  (Users could `berks apply` to a file, check the file into source control, and then run `knife environment from file`.)  The approach of running [`knife environment show`](http://docs.opscode.com/knife_environment.html#show) after `berks apply` is susceptible to a race condition as I mentioned in [this comment](https://github.com/RiotGames/berkshelf/issues/846#issuecomment-26662505) to issue #846.

**Comment by jsirex** [comment]
Vote for something like this. 
In my case I want to have an environment file which keeps some environment attributes and also keeps cookbooks version constraints from `berks apply` command.

**Comment by martinb3** [comment]
I'd love to have this feature -- even if it wasn't under `apply`. Maybe `berks show -Fj`

**Comment by iiro** [comment]
+1 for this one as well.

**Comment by mpaf** [comment]
+1, this would be great to have

**Comment by reset** [comment]
Closing via https://github.com/berkshelf/berkshelf/pull/1512
